import type { AssetDefinition } from "./types";

export const assetManifest: AssetDefinition[] = [
  { id: "logo-main", kind: "logo", shape: "crest-logo", size: 256, palette: ["#fff4d0", "#ff8a5c", "#2a1734"], glow: "#ffb36d" },
  { id: "player-runner", kind: "sprite", shape: "player-runner", size: 64, palette: ["#fff0d0", "#5af2ff", "#2f6fff"], glow: "#8be9ff" },
  { id: "enemy-rootling", kind: "sprite", shape: "thorn-beast", size: 48, palette: ["#a4ff8f", "#417b39", "#0f2016"], glow: "#98ff7e" },
  { id: "enemy-racer-mite", kind: "sprite", shape: "skitter", size: 40, palette: ["#f7ff85", "#5d942f", "#18220d"], glow: "#fff374" },
  { id: "enemy-mire-brute", kind: "sprite", shape: "brute", size: 56, palette: ["#f8a85b", "#7d3f26", "#311814"], glow: "#ff9b54" },
  { id: "enemy-spore-thrower", kind: "sprite", shape: "caster", size: 48, palette: ["#f39cff", "#783f98", "#261437"], glow: "#d6a4ff" },
  { id: "enemy-glass-lancer", kind: "sprite", shape: "lancer", size: 46, palette: ["#a4ffe5", "#3d8e83", "#102626"], glow: "#a1fff0" },
  { id: "enemy-gloom-wisp", kind: "sprite", shape: "wisp", size: 42, palette: ["#8fbcff", "#4c52c9", "#1a173c"], glow: "#b4d4ff" },
  { id: "enemy-seed-pod", kind: "sprite", shape: "pod", size: 52, palette: ["#ffe28f", "#936a24", "#32220a"], glow: "#ffd27c" },
  { id: "enemy-rootling-elite", kind: "sprite", shape: "thorn-beast-elite", size: 56, palette: ["#f9ffe3", "#97ff7f", "#183021"], glow: "#e5ff9e" },
  { id: "enemy-mire-brute-elite", kind: "sprite", shape: "brute-elite", size: 64, palette: ["#fff1cc", "#ff9361", "#3b1a15"], glow: "#ffc98c" },
  { id: "enemy-spore-thrower-elite", kind: "sprite", shape: "caster-elite", size: 58, palette: ["#fff0ff", "#db86ff", "#351346"], glow: "#f2b2ff" },
  { id: "boss-mire-titan", kind: "sprite", shape: "boss-titan", size: 88, palette: ["#fff0d3", "#b87e4a", "#2e1610"], glow: "#ffb67b" },
  { id: "boss-ash-monarch", kind: "sprite", shape: "boss-monarch", size: 90, palette: ["#fff5da", "#ff7d59", "#321824"], glow: "#ffae7c" },
  { id: "boss-glacier-revenant", kind: "sprite", shape: "boss-revenant", size: 92, palette: ["#f4fbff", "#77d4ff", "#13254d"], glow: "#8ceaff" },
  { id: "boss-night-seraph", kind: "sprite", shape: "boss-seraph", size: 88, palette: ["#fff6fd", "#cd8dff", "#221146"], glow: "#f5bbff" },
  { id: "boss-hundredth-dawn", kind: "sprite", shape: "boss-final", size: 104, palette: ["#fff7df", "#ffd166", "#ff6b6b", "#211033"], glow: "#ffd990" },
  { id: "weapon-ember-darts", kind: "sprite", shape: "dart", size: 32, palette: ["#fff8ce", "#ffab5c", "#5a1f12"], glow: "#ffd279" },
  { id: "weapon-bloom-spread", kind: "sprite", shape: "petal-bolt", size: 34, palette: ["#f1ffd9", "#7ed957", "#1e3a1b"], glow: "#baff95" },
  { id: "weapon-rail-splinter", kind: "sprite", shape: "rail-bolt", size: 36, palette: ["#e6fbff", "#85e8ff", "#234e67"], glow: "#baf2ff" },
  { id: "weapon-sun-orbiters", kind: "sprite", shape: "orbit-disc", size: 36, palette: ["#fff8d9", "#ffdd6c", "#8c5911"], glow: "#ffe18c" },
  { id: "weapon-quake-ring", kind: "effect", shape: "shock-ring", size: 96, palette: ["#fff6d8", "#ff926b", "#38161f"], glow: "#ffba8b" },
  { id: "weapon-tether-beam", kind: "effect", shape: "beam", size: 80, palette: ["#f6ffff", "#7af3ff", "#265c78"], glow: "#9ff4ff" },
  { id: "weapon-ember-mines", kind: "sprite", shape: "mine", size: 34, palette: ["#ffe8bf", "#ff8f59", "#451e19"], glow: "#ffb07e" },
  { id: "weapon-drone-sentinels", kind: "sprite", shape: "drone", size: 34, palette: ["#f7fff7", "#95ffd1", "#1a4f4b"], glow: "#a8ffe3" },
  { id: "weapon-storm-chain", kind: "effect", shape: "chain", size: 64, palette: ["#ffffff", "#b4f1ff", "#458dff"], glow: "#d5f8ff" },
  { id: "weapon-thorn-aura", kind: "effect", shape: "aura", size: 80, palette: ["#f3ffe2", "#8bff9b", "#24451d"], glow: "#bbffb6" },
  { id: "pickup-xp-small", kind: "icon", shape: "xp-small", size: 28, palette: ["#dffcff", "#78e3ff", "#226f92"], glow: "#abf1ff" },
  { id: "pickup-xp-medium", kind: "icon", shape: "xp-medium", size: 30, palette: ["#e7ffe6", "#8dff97", "#1f7c3b"], glow: "#b4ffbf" },
  { id: "pickup-xp-large", kind: "icon", shape: "xp-large", size: 32, palette: ["#fff3d7", "#ffd166", "#9e6d18"], glow: "#ffe58e" },
  { id: "pickup-heal-orb", kind: "icon", shape: "heal", size: 30, palette: ["#fff0f2", "#ff8aa1", "#9b3857"], glow: "#ffb8c4" },
  { id: "pickup-magnet-star", kind: "icon", shape: "magnet", size: 32, palette: ["#fffbe1", "#fff07a", "#9f8c2b"], glow: "#fff3a2" },
  { id: "effect-hit", kind: "effect", shape: "hit-burst", size: 48, palette: ["#ffffff", "#ffbd80", "#ff6c5c"], glow: "#ffd2a1" },
  { id: "effect-explosion", kind: "effect", shape: "explosion", size: 96, palette: ["#fff4ce", "#ff985e", "#ff5858"], glow: "#ffd28d" }
];
