import type { EnemyDefinition } from "./types";

export const enemyIndex: EnemyDefinition[] = [
  {
    id: "rootling",
    name: "Rootling",
    description: "Basic swarm enemy that relentlessly closes in.",
    behavior: "swarm",
    faction: "wildroot",
    spriteId: "enemy-rootling",
    iconId: "icon-rootling",
    unlockDay: 1,
    radius: 16,
    maxHp: 34,
    speed: 78,
    damage: 10,
    xp: 4,
    touchCooldown: 0.9,
    knockbackResistance: 0.95,
  },
  {
    id: "racer-mite",
    name: "Racer Mite",
    description: "Fast but fragile enemy that pressures positioning.",
    behavior: "fast",
    faction: "wildroot",
    spriteId: "enemy-racer-mite",
    iconId: "icon-racer-mite",
    unlockDay: 3,
    radius: 12,
    maxHp: 22,
    speed: 124,
    damage: 8,
    xp: 4,
    touchCooldown: 0.8,
    knockbackResistance: 0.85,
  },
  {
    id: "mire-brute",
    name: "Mire Brute",
    description: "Slow armored body that soaks damage for the pack.",
    behavior: "tank",
    faction: "wildroot",
    spriteId: "enemy-mire-brute",
    iconId: "icon-mire-brute",
    unlockDay: 5,
    radius: 22,
    maxHp: 84,
    speed: 58,
    damage: 18,
    xp: 9,
    touchCooldown: 1.1,
    knockbackResistance: 1.35,
  },
  {
    id: "spore-thrower",
    name: "Spore Thrower",
    description: "Keeps distance and hurls toxic globes.",
    behavior: "ranged",
    faction: "ruinborn",
    spriteId: "enemy-spore-thrower",
    iconId: "icon-spore-thrower",
    unlockDay: 8,
    radius: 17,
    maxHp: 44,
    speed: 70,
    damage: 12,
    xp: 7,
    touchCooldown: 1,
    knockbackResistance: 1,
    ranged: { cooldown: 2.2, speed: 220, damage: 14, range: 360 },
  },
  {
    id: "glass-lancer",
    name: "Glass Lancer",
    description: "Telegraphs and charges in straight violent bursts.",
    behavior: "charger",
    faction: "embercourt",
    spriteId: "enemy-glass-lancer",
    iconId: "icon-glass-lancer",
    unlockDay: 10,
    radius: 15,
    maxHp: 54,
    speed: 82,
    damage: 17,
    xp: 8,
    touchCooldown: 0.75,
    knockbackResistance: 1.05,
    charge: { cooldown: 3.1, speed: 320, duration: 0.45 },
  },
  {
    id: "gloom-wisp",
    name: "Gloom Wisp",
    description: "A drifting spirit that snakes through crowds.",
    behavior: "wisp",
    faction: "frostkin",
    spriteId: "enemy-gloom-wisp",
    iconId: "icon-gloom-wisp",
    unlockDay: 14,
    radius: 14,
    maxHp: 48,
    speed: 102,
    damage: 16,
    xp: 8,
    touchCooldown: 0.95,
    knockbackResistance: 0.9,
    ranged: { cooldown: 2.8, speed: 260, damage: 15, range: 300 },
  },
  {
    id: "seed-pod",
    name: "Seed Pod",
    description: "Splits into smaller threats when destroyed.",
    behavior: "splitter",
    faction: "wildroot",
    spriteId: "enemy-seed-pod",
    iconId: "icon-seed-pod",
    unlockDay: 18,
    radius: 20,
    maxHp: 66,
    speed: 68,
    damage: 18,
    xp: 10,
    touchCooldown: 1,
    knockbackResistance: 1.1,
    splitInto: "racer-mite",
    splitCount: 2,
  },
  {
    id: "rootling-elite",
    name: "Rootling Champion",
    description: "A hardened rootling leading the front line.",
    behavior: "swarm",
    faction: "wildroot",
    spriteId: "enemy-rootling-elite",
    iconId: "icon-rootling-elite",
    unlockDay: 10,
    radius: 20,
    maxHp: 160,
    speed: 94,
    damage: 24,
    xp: 22,
    touchCooldown: 0.85,
    knockbackResistance: 1.35,
    isElite: true,
  },
  {
    id: "mire-brute-elite",
    name: "Mire Juggernaut",
    description: "Elite brute with huge life and body pressure.",
    behavior: "tank",
    faction: "wildroot",
    spriteId: "enemy-mire-brute-elite",
    iconId: "icon-mire-brute-elite",
    unlockDay: 15,
    radius: 26,
    maxHp: 280,
    speed: 68,
    damage: 30,
    xp: 28,
    touchCooldown: 1,
    knockbackResistance: 1.6,
    isElite: true,
  },
  {
    id: "spore-thrower-elite",
    name: "Blight Artillerist",
    description: "Elite ranged threat that paints the arena with pressure.",
    behavior: "ranged",
    faction: "ruinborn",
    spriteId: "enemy-spore-thrower-elite",
    iconId: "icon-spore-thrower-elite",
    unlockDay: 20,
    radius: 21,
    maxHp: 210,
    speed: 78,
    damage: 24,
    xp: 30,
    touchCooldown: 0.9,
    knockbackResistance: 1.2,
    ranged: { cooldown: 1.5, speed: 290, damage: 20, range: 420 },
    isElite: true,
  },
  {
    id: "mire-titan",
    name: "Mire Titan",
    description: "Day 25 boss that slams and summons brute cover.",
    behavior: "boss",
    faction: "wildroot",
    spriteId: "boss-mire-titan",
    iconId: "icon-mire-titan",
    unlockDay: 25,
    radius: 42,
    maxHp: 2600,
    speed: 68,
    damage: 32,
    xp: 150,
    touchCooldown: 0.8,
    knockbackResistance: 3,
    summonIds: ["rootling", "mire-brute"],
    isBoss: true,
    bossMusic: "danger-bloom",
  },
  {
    id: "ash-monarch",
    name: "Ash Monarch",
    description: "Day 50 boss that fills the arena with burning volleys.",
    behavior: "boss",
    faction: "embercourt",
    spriteId: "boss-ash-monarch",
    iconId: "icon-ash-monarch",
    unlockDay: 50,
    radius: 36,
    maxHp: 4600,
    speed: 90,
    damage: 38,
    xp: 240,
    touchCooldown: 0.75,
    knockbackResistance: 3.2,
    ranged: { cooldown: 1.35, speed: 320, damage: 24, range: 480 },
    summonIds: ["glass-lancer", "gloom-wisp"],
    isBoss: true,
    bossMusic: "danger-bloom",
  },
  {
    id: "glacier-revenant",
    name: "Glacier Revenant",
    description: "Day 75 boss that alternates charge runs with cold volleys.",
    behavior: "boss",
    faction: "frostkin",
    spriteId: "boss-glacier-revenant",
    iconId: "icon-glacier-revenant",
    unlockDay: 75,
    radius: 38,
    maxHp: 6200,
    speed: 96,
    damage: 44,
    xp: 300,
    touchCooldown: 0.7,
    knockbackResistance: 3.4,
    ranged: { cooldown: 1.8, speed: 340, damage: 28, range: 500 },
    charge: { cooldown: 4.2, speed: 420, duration: 0.55 },
    summonIds: ["gloom-wisp", "spore-thrower-elite"],
    isBoss: true,
    bossMusic: "danger-bloom",
  },
  {
    id: "night-seraph",
    name: "Night Seraph",
    description: "Late boss that drifts and overwhelms with wisp support.",
    behavior: "boss",
    faction: "riftspawn",
    spriteId: "boss-night-seraph",
    iconId: "icon-night-seraph",
    unlockDay: 90,
    radius: 34,
    maxHp: 7200,
    speed: 110,
    damage: 46,
    xp: 360,
    touchCooldown: 0.65,
    knockbackResistance: 3.6,
    ranged: { cooldown: 1.2, speed: 360, damage: 28, range: 540 },
    summonIds: ["gloom-wisp", "rootling-elite"],
    isBoss: true,
    bossMusic: "danger-bloom",
  },
  {
    id: "hundredth-dawn",
    name: "The Hundredth Dawn",
    description: "Final boss and last test of every build decision.",
    behavior: "boss",
    faction: "riftspawn",
    spriteId: "boss-hundredth-dawn",
    iconId: "icon-hundredth-dawn",
    unlockDay: 100,
    radius: 46,
    maxHp: 9800,
    speed: 118,
    damage: 52,
    xp: 1000,
    touchCooldown: 0.6,
    knockbackResistance: 4,
    ranged: { cooldown: 1.05, speed: 390, damage: 32, range: 600 },
    charge: { cooldown: 3.6, speed: 460, duration: 0.68 },
    summonIds: ["glass-lancer", "spore-thrower-elite", "mire-brute-elite"],
    isBoss: true,
    bossMusic: "danger-bloom",
  },
];
