import type { PassiveDefinition } from "./types";

export const passiveIndex: PassiveDefinition[] = [
  {
    id: "heartforge",
    name: "Heartforge Plating",
    description: "Increase max health and top off a little life immediately.",
    iconId: "icon-heartforge",
    rarity: "common",
    weight: 9,
    unlockDay: 1,
    maxLevel: 5,
    perLevel: { maxHp: 18 },
    healOnPick: 14,
  },
  {
    id: "stride-engine",
    name: "Stride Engine",
    description: "Boost movement speed for safer kiting and sharper dodges.",
    iconId: "icon-stride-engine",
    rarity: "common",
    weight: 8,
    unlockDay: 1,
    maxLevel: 5,
    perLevel: { moveSpeed: 18 },
  },
  {
    id: "magnet-array",
    name: "Magnet Array",
    description: "Increase pickup radius and draw drops in harder.",
    iconId: "icon-magnet-array",
    rarity: "common",
    weight: 8,
    unlockDay: 1,
    maxLevel: 5,
    perLevel: { pickupRadius: 18, magnetStrength: 40 },
  },
  {
    id: "plate-shell",
    name: "Plate Shell",
    description: "Reduce incoming damage with layered armor.",
    iconId: "icon-plate-shell",
    rarity: "rare",
    weight: 6,
    unlockDay: 5,
    maxLevel: 5,
    perLevel: { armor: 0.7 },
  },
  {
    id: "chrono-lattice",
    name: "Chrono Lattice",
    description: "Tighten every weapon cooldown.",
    iconId: "icon-chrono-lattice",
    rarity: "rare",
    weight: 6,
    unlockDay: 6,
    maxLevel: 5,
    perLevel: { cooldownMultiplier: -0.08 },
  },
  {
    id: "crit-lens",
    name: "Crit Lens",
    description: "Raise critical hit chance and critical impact.",
    iconId: "icon-crit-lens",
    rarity: "rare",
    weight: 5,
    unlockDay: 8,
    maxLevel: 5,
    perLevel: { critChance: 0.04, critMultiplier: 0.1 },
  },
  {
    id: "salvage-sense",
    name: "Salvage Sense",
    description: "Gain more experience from every gem collected.",
    iconId: "icon-salvage-sense",
    rarity: "rare",
    weight: 5,
    unlockDay: 9,
    maxLevel: 5,
    perLevel: { xpMultiplier: 0.09 },
  },
  {
    id: "renewal-moss",
    name: "Renewal Moss",
    description: "Increase passive regeneration each second.",
    iconId: "icon-renewal-moss",
    rarity: "rare",
    weight: 5,
    unlockDay: 10,
    maxLevel: 5,
    perLevel: { regen: 0.35 },
  },
  {
    id: "bulwark-thread",
    name: "Bulwark Thread",
    description: "Add health and armor together for sturdier late-day pushes.",
    iconId: "icon-plate-shell",
    rarity: "rare",
    weight: 6,
    unlockDay: 7,
    maxLevel: 5,
    perLevel: { maxHp: 10, armor: 0.35 },
  },
  {
    id: "gravitic-band",
    name: "Gravitic Band",
    description: "Stretch pickup reach while also widening area-based attacks.",
    iconId: "icon-magnet-array",
    rarity: "rare",
    weight: 5,
    unlockDay: 9,
    maxLevel: 5,
    perLevel: { pickupRadius: 12, areaMultiplier: 0.04 },
  },
  {
    id: "overcharge-core",
    name: "Overcharge Core",
    description: "Boost all outgoing damage.",
    iconId: "icon-overcharge-core",
    rarity: "epic",
    weight: 4,
    unlockDay: 12,
    maxLevel: 5,
    perLevel: { damageMultiplier: 0.08 },
  },
  {
    id: "kinetic-bloom",
    name: "Kinetic Bloom",
    description: "Raise projectile speed and add a little raw damage.",
    iconId: "icon-overcharge-core",
    rarity: "epic",
    weight: 4,
    unlockDay: 11,
    maxLevel: 5,
    perLevel: { projectileSpeed: 0.1, damageMultiplier: 0.04 },
  },
  {
    id: "wildbloom",
    name: "Wildbloom Halo",
    description: "Increase area and lingering weapon duration.",
    iconId: "icon-wildbloom",
    rarity: "epic",
    weight: 4,
    unlockDay: 14,
    maxLevel: 5,
    perLevel: { areaMultiplier: 0.08, durationMultiplier: 0.06 },
  },
  {
    id: "phase-soles",
    name: "Phase Soles",
    description: "Lean harder into speed and a real chance to slip incoming hits.",
    iconId: "icon-stride-engine",
    rarity: "epic",
    weight: 4,
    unlockDay: 13,
    maxLevel: 5,
    perLevel: { moveSpeed: 14, dodgeChance: 0.025 },
  },
  {
    id: "longwatch-array",
    name: "Longwatch Array",
    description: "Increase weapon duration and sharpen projectile travel.",
    iconId: "icon-wildbloom",
    rarity: "epic",
    weight: 4,
    unlockDay: 15,
    maxLevel: 5,
    perLevel: { durationMultiplier: 0.08, projectileSpeed: 0.06 },
  },
  {
    id: "fortune-thread",
    name: "Fortune Thread",
    description: "Raise luck for better healing and special drop odds.",
    iconId: "icon-fortune-thread",
    rarity: "epic",
    weight: 4,
    unlockDay: 16,
    maxLevel: 5,
    perLevel: { luck: 0.05 },
  },
  {
    id: "prism-heart",
    name: "Prism Heart",
    description: "Blend crit growth with extra experience gain for snowball runs.",
    iconId: "icon-crit-lens",
    rarity: "epic",
    weight: 4,
    unlockDay: 17,
    maxLevel: 5,
    perLevel: { critChance: 0.025, xpMultiplier: 0.05 },
  },
  {
    id: "relay-spark",
    name: "Relay Spark",
    description: "Push cooldowns lower while boosting projectile velocity.",
    iconId: "icon-chrono-lattice",
    rarity: "epic",
    weight: 4,
    unlockDay: 18,
    maxLevel: 5,
    perLevel: { cooldownMultiplier: -0.05, projectileSpeed: 0.08 },
  },
  {
    id: "sun-cell",
    name: "Sun Cell",
    description: "Gain regeneration and a steady damage lift at the same time.",
    iconId: "icon-renewal-moss",
    rarity: "epic",
    weight: 4,
    unlockDay: 19,
    maxLevel: 5,
    perLevel: { regen: 0.2, damageMultiplier: 0.04 },
  },
  {
    id: "hunter-sigil",
    name: "Hunter Sigil",
    description: "Crit harder and convert sharp play into bigger finishers.",
    iconId: "icon-crit-lens",
    rarity: "legendary",
    weight: 3,
    unlockDay: 21,
    maxLevel: 5,
    perLevel: { critMultiplier: 0.16, damageMultiplier: 0.05 },
  },
  {
    id: "second-wind",
    name: "Second Wind",
    description: "Gain a one-time revive charge for a desperate comeback.",
    iconId: "icon-second-wind",
    rarity: "legendary",
    weight: 2,
    unlockDay: 20,
    maxLevel: 1,
    perLevel: { reviveCharges: 1 },
  },
];
