import type { WeaponDefinition, WeaponLevelStats } from "./types";

const createStats = (stats: Partial<WeaponLevelStats>): WeaponLevelStats => ({
  damage: 0,
  cooldown: 1,
  count: 0,
  speed: 0,
  size: 0,
  range: 0,
  duration: 0,
  pierce: 0,
  knockback: 0,
  radius: 0,
  chain: 0,
  orbitals: 0,
  drones: 0,
  spread: 0,
  orbitRadius: 0,
  fuse: 0,
  beamWidth: 0,
  ...stats,
});

export const weaponIndex: WeaponDefinition[] = [
  {
    id: "ember-darts",
    name: "Ember Darts",
    description: "Auto-fires fast tracking darts at the nearest threat.",
    archetype: "projectile",
    iconId: "icon-ember-darts",
    spriteId: "weapon-ember-darts",
    rarity: "common",
    weight: 9,
    unlockDay: 1,
    maxLevel: 5,
    baseStats: createStats({ damage: 18, cooldown: 0.62, count: 1, speed: 580, size: 11, range: 610, knockback: 90 }),
    perLevel: { damage: 5, cooldown: -0.05, count: 0.5, speed: 25, pierce: 0.2 },
  },
  {
    id: "bloom-spread",
    name: "Bloom Spread",
    description: "Fan-shaped burst that covers flanks and punishes packed swarms.",
    archetype: "spread",
    iconId: "icon-bloom-spread",
    spriteId: "weapon-bloom-spread",
    rarity: "common",
    weight: 8,
    unlockDay: 2,
    maxLevel: 5,
    baseStats: createStats({ damage: 15, cooldown: 1.2, count: 3, speed: 510, size: 10, range: 540, spread: 0.55, knockback: 70 }),
    perLevel: { damage: 4, cooldown: -0.08, count: 1, spread: 0.05, size: 1 },
  },
  {
    id: "rail-splinter",
    name: "Rail Splinter",
    description: "A piercing bolt that tears through lines of enemies.",
    archetype: "pierce",
    iconId: "icon-rail-splinter",
    spriteId: "weapon-rail-splinter",
    rarity: "rare",
    weight: 6,
    unlockDay: 5,
    maxLevel: 5,
    baseStats: createStats({ damage: 28, cooldown: 1.45, count: 1, speed: 820, size: 13, range: 760, pierce: 2, knockback: 150 }),
    perLevel: { damage: 7, cooldown: -0.1, pierce: 1, size: 1 },
  },
  {
    id: "sun-orbiters",
    name: "Sun Orbiters",
    description: "Forged rings orbit the player and carve open close-range space.",
    archetype: "orbit",
    iconId: "icon-sun-orbiters",
    spriteId: "weapon-sun-orbiters",
    rarity: "rare",
    weight: 5,
    unlockDay: 7,
    maxLevel: 5,
    baseStats: createStats({ damage: 16, cooldown: 0.16, orbitals: 1, size: 16, radius: 18, orbitRadius: 86, knockback: 65 }),
    perLevel: { damage: 4, orbitals: 0.75, orbitRadius: 8, size: 2 },
  },
  {
    id: "quake-ring",
    name: "Quake Ring",
    description: "Sends out repeated shock rings that blast nearby enemies.",
    archetype: "blast",
    iconId: "icon-quake-ring",
    spriteId: "weapon-quake-ring",
    rarity: "rare",
    weight: 5,
    unlockDay: 10,
    maxLevel: 5,
    baseStats: createStats({ damage: 32, cooldown: 2.9, radius: 132, size: 18, knockback: 200 }),
    perLevel: { damage: 8, cooldown: -0.2, radius: 14, size: 2 },
  },
  {
    id: "tether-beam",
    name: "Tether Beam",
    description: "Locks onto a priority target with a short burning beam.",
    archetype: "beam",
    iconId: "icon-tether-beam",
    spriteId: "weapon-tether-beam",
    rarity: "epic",
    weight: 4,
    unlockDay: 15,
    maxLevel: 5,
    baseStats: createStats({ damage: 34, cooldown: 2.45, range: 420, duration: 1.1, beamWidth: 12 }),
    perLevel: { damage: 7, cooldown: -0.18, range: 20, duration: 0.18, beamWidth: 1.4 },
  },
  {
    id: "ember-mines",
    name: "Ember Mines",
    description: "Drops timed charges that erupt when the horde closes in.",
    archetype: "mine",
    iconId: "icon-ember-mines",
    spriteId: "weapon-ember-mines",
    rarity: "epic",
    weight: 4,
    unlockDay: 18,
    maxLevel: 5,
    baseStats: createStats({ damage: 52, cooldown: 3.1, count: 1, radius: 96, fuse: 1.35, size: 16 }),
    perLevel: { damage: 10, cooldown: -0.22, count: 0.5, radius: 16, fuse: -0.08 },
  },
  {
    id: "drone-sentinels",
    name: "Drone Sentinels",
    description: "Summons orbiting helpers that fire on nearby threats.",
    archetype: "summon",
    iconId: "icon-drone-sentinels",
    spriteId: "weapon-drone-sentinels",
    rarity: "epic",
    weight: 4,
    unlockDay: 22,
    maxLevel: 5,
    baseStats: createStats({ damage: 18, cooldown: 1.05, drones: 1, range: 460, orbitRadius: 118, size: 13 }),
    perLevel: { damage: 4, cooldown: -0.08, drones: 0.5, range: 18 },
  },
  {
    id: "storm-chain",
    name: "Storm Chain",
    description: "Forks lightning across nearby enemies for screen-clearing bursts.",
    archetype: "chain",
    iconId: "icon-storm-chain",
    spriteId: "weapon-storm-chain",
    rarity: "legendary",
    weight: 3,
    unlockDay: 28,
    maxLevel: 5,
    baseStats: createStats({ damage: 26, cooldown: 1.8, chain: 3, range: 320, size: 10 }),
    perLevel: { damage: 6, cooldown: -0.14, chain: 1, range: 25 },
  },
  {
    id: "thorn-aura",
    name: "Thorn Aura",
    description: "A living aura damages and slows enemies within its bloom.",
    archetype: "aura",
    iconId: "icon-thorn-aura",
    spriteId: "weapon-thorn-aura",
    rarity: "legendary",
    weight: 3,
    unlockDay: 32,
    maxLevel: 5,
    baseStats: createStats({ damage: 14, cooldown: 0.34, radius: 114, size: 18, duration: 0.2 }),
    perLevel: { damage: 4, cooldown: -0.03, radius: 12, size: 1 },
  },
];
