export const projects = [
  {
    title: "Visual Search Lens",
    tag: "AI Vision / Image Search",
    description: "Upload an image and receive detailed visual search analysis with searchable descriptions, keywords, Google image queries, style classification, color palettes, tags, objects, and similar-image discovery guidance.",
    href: "../visual-search-lens/",
  },
  {
    title: "Space Explorer",
    tag: "NASA-style / 3D Solar System",
    description: "Cinematic 3D space explorer with textured planets, major moons, asteroid and Kuiper belts, famous stars, orbit paths, real measurements, and NASA/JPL integration hooks.",
    href: "../space-explorer/",
  },
  {
    title: "Private Residence Scroll Journey",
    tag: "Luxury Real Estate / R3F Scroll Tour",
    description: "Cinematic luxury villa walkthrough where scroll drives the camera from gated arrival through driveway, exterior reveal, interiors, feature rooms, and private viewing CTA.",
    href: "../luxury-house-scroll-journey/",
  },
  {
    title: "Global Intelligence World",
    tag: "RPG / AI Intelligence Dashboard",
    description: "Interactive 3D control hub where buildings open live intelligence, market analytics, infrastructure telemetry, and project dashboards.",
    href: "../global-intelligence-rpg/",
  },
  {
    title: "Global Intelligence Dashboard",
    tag: "Live Intel / Situational Awareness",
    description: "Full-screen world monitoring platform with live news, seismic and hazard feeds, market signals, AI risk insights, filters, and a real-time map.",
    href: "../global-intelligence-dashboard/",
  },
  {
    title: "Global Route Intelligence Map",
    tag: "Geospatial / Route Intelligence",
    description: "Real-world MapLibre and Deck.gl dashboard showing flight arcs, shipping lanes, the Silk Road, trade routes, aviation corridors, and strategic chokepoints.",
    href: "../global-route-intelligence-map/",
  },
  {
    title: "Object Scanner",
    tag: "Camera / 3D Reconstruction",
    description: "Realtime radar-style webcam scanner with object capture and room mapping, preserving camera colors in interactive Three.js point-cloud previews.",
    href: "../object-scanner/",
  },
  {
    title: "Privacy Face Recognition",
    tag: "Camera / Local AI",
    description: "Consent-based face login demo with local webcam detection, face descriptor registration, one-click recognition, and browser-only privacy controls.",
    href: "../privacy-face-recognition/",
  },
  {
    title: "Gemini AI Chat",
    tag: "AI / Server Route",
    description: "Secure Next.js chat assistant where the browser sends messages to a backend API route and Gemini replies without exposing the API key.",
    href: "../gemini-ai-chat/",
  },
  {
    title: "Particle Shape System",
    tag: "Canvas / Particle Simulation",
    description: "Realtime dust-pixel field where thousands of particles form uploaded images or typed text, repel from the cursor, and transition smoothly between modes.",
    href: "../particle-shape-system/",
  },
  {
    title: "Wheel of Fortune",
    tag: "Decision Tool / Canvas",
    description: "Polished spinning wheel with editable options, fair random selection, physics-style slowdown, pointer landing, sounds, and preset lists.",
    href: "../wheel-of-fortune/",
  },
  {
    title: "Sorting Algorithm Visualizer",
    tag: "Education / Algorithms",
    description: "Step-by-step sorting lab with animated bars, pseudocode highlighting, complexity notes, playback controls, and side-by-side algorithm comparison.",
    href: "../games/sorting-algorithm-visualizer/",
  },
  {
    title: "Galaxy Simulator",
    tag: "Physics / Cosmic Sandbox",
    description: "Interactive 3D gravity lab with celestial body creation, Newtonian orbits, collisions, black holes, supernova events, and predictive future paths.",
    href: "../games/galaxy-simulator/",
  },
  {
    title: "Market Pulse Trader",
    tag: "Trading / Simulation",
    description: "Browser stock-trading simulator with market events, holdings, cash balance, watchlist movement, and persistent portfolio state.",
    href: "../games/stock-trading-sim/",
  },
  {
    title: "Sky Atlas Flight",
    tag: "Flight / Simulation",
    description: "Lightweight browser flight simulator with a focused cockpit-style launch path from the games collection.",
    href: "../games/flight-simulator/",
  },
  {
    title: "Boardgame Vault",
    tag: "Game / Board System",
    description: "Playable boardgame experiment from the arcade with a dedicated browser interface.",
    href: "../games/boardgame/",
  },
  {
    title: "Lantern Oath",
    tag: "Game / Narrative RPG",
    description: "Atmospheric narrative game about guarding the last hearth through a stylized browser interface.",
    href: "../games/lantern-oath/",
  },
  {
    title: "Hundred Days of Ashfall",
    tag: "Game / Survival Strategy",
    description: "A compact survival strategy game built around lasting one hundred days through a changing crisis.",
    href: "../games/100days/",
  },
  {
    title: "Puzzle Escape Lab",
    tag: "Game / Puzzle",
    description: "Cyber-styled puzzle room experiment with level flow, escape logic, and arcade presentation.",
    href: "../games/puzzle/",
  },
  {
    title: "Hollowmere Classic",
    tag: "Game / RPG",
    description: "Classic Hollowmere RPG prototype for Veil of the Hollow Star.",
    href: "../games/rpg/",
  },
  {
    title: "Hollowmere Overworld",
    tag: "Game / RPG Overworld",
    description: "Overworld version of the Hollowmere RPG prototype with a broader map-first structure.",
    href: "../games/rpg-overworld/",
  },
  {
    title: "Hollowmere Overworld Snapshot",
    tag: "Game / RPG Snapshot",
    description: "Snapshot build of the Hollowmere overworld kept as a separate playable launch path.",
    href: "../games/rpg-overworld-snapshot/",
  },
  {
    title: "Reels Pull",
    tag: "Game / Collection",
    description: "Collection-pull game with roll history, achievements, signal lab controls, and account stats.",
    href: "../games/reelspull/",
  },
  {
    title: "Goal Kinetic Soccer Idle",
    tag: "Game / Idle Sports",
    description: "Soccer clicker and idle club builder with upgrades, players, prestige, and standings.",
    href: "../games/soccer-idle/",
  },
  {
    title: "Midnight Pawn",
    tag: "Game / Relic Shop",
    description: "Mythic relic broker game with wares, inventory, talents, codex entries, and nightly progress.",
    href: "../games/midnight-pawn/",
  },
  {
    title: "Hand Draw Studio",
    tag: "Camera / Drawing Tool",
    description: "Webcam hand-tracking canvas where the cursor follows your index fingertip and an index-plus-thumb pinch draws smooth lines.",
    href: "../hand-draw-studio/",
  },
  {
    title: "Market Intel AI",
    tag: "Finance / AI Analysis",
    description: "Real-time stock analysis terminal with live OHLC data, moving-average intelligence, RSI, sector signals, financial news, and account tracking.",
    href: "../market-intel-ai/",
  },
  {
    title: "Loop DAW",
    tag: "Music / Composition Tool",
    description: "Beginner-friendly browser DAW with a draggable piano roll, loop playback, Web Audio instruments, mixer controls, presets, and save/export.",
    href: "../loop-daw/",
  },
  {
    title: "RPG Homepage Hub",
    tag: "Homepage / 3D RPG Navigation",
    description: "Playable homepage world where buildings act as cinematic portals to portfolio, AI, trading, music, galaxy, and contact destinations.",
    href: "../test5.html",
  },
  {
    title: "Standalone Interface Test",
    tag: "HTML / Interface Study",
    description: "Root-level test.html standalone interface experiment kept available from the main archive.",
    href: "../test.html",
  },
  {
    title: "POLAR//SEED",
    tag: "HTML / Speculative Interface",
    description: "Standalone POLAR//SEED interface page with a stark experimental presentation.",
    href: "../test2.html",
  },
  {
    title: "Project Hub Prototype",
    tag: "Portfolio / Prototype",
    description: "Earlier Never Wet project hub prototype kept as a separate launch path.",
    href: "../test3.html",
  },
  {
    title: "3D Preview",
    tag: "WebGL / Preview",
    description: "Standalone 3D preview shell for generated models, image assets, and quick visual checks.",
    href: "../test4.html",
  },
  {
    title: "Meridian Fullstack Export",
    tag: "Standalone / Fullstack Export",
    description: "Standalone Emergent export for a Meridian operations-style landing interface.",
    href: "../Emergent _ Fullstack App.html",
  },
  {
    title: "AeroLab Car Showcase Export",
    tag: "Automotive / Standalone Export",
    description: "Standalone Emergent export for the Aerodynamica car showcase experience.",
    href: "../carEmergent _ Fullstack App.html",
  },
  {
    title: "Aerodynamica Car Showcase Variant",
    tag: "Automotive / Standalone Export",
    description: "Second standalone Aerodynamica export kept as an alternate launch path.",
    href: "../car2Emergent _ Fullstack App.html",
  },
  {
    title: "Code Workspace",
    tag: "Developer Tool / Monaco",
    description: "Browser-based VS Code-inspired workspace with Monaco editing, files, tabs, command palette, terminal, themes, and simulated extensions.",
    href: "../code-workspace/",
  },
  {
    title: "Entity Diagnostic System",
    tag: "Identity / R3F State Machine",
    description: "Controlled diagnostic interface where scroll advances system states, identity selection updates ranked entity data, and a reactive 3D core performs the analysis.",
    href: "../entity-diagnostic-system/",
  },
  {
    title: "Physics Engine Playground",
    tag: "Physics / Simulator",
    description: "Interactive physics laboratory with real Matter.js 2D experiments, Three.js/cannon-es 3D rigid bodies, debug vectors, trails, and draggable objects.",
    href: "../physics-engine-playground/physics-engine-playground.html",
  },
  {
    title: "Terrain Generator",
    tag: "Procedural / WebGL Tool",
    description: "Realtime terrain creation tool with procedural noise, erosion, brush editing, chunked Three.js rendering, and heightmap or mesh export.",
    href: "../terrain-generator/",
  },
  {
    title: "Igloo Experience",
    tag: "Homepage / Immersive",
    description: "Scene-only version of the Never Wet homepage with interactive brick disassembly and snowfall.",
    href: "../igloo-home/",
  },
  {
    title: "Apex Hypercar Showcase",
    tag: "Automotive / 3D Showcase",
    description: "Precision hypercar presentation with a focused 3D stage and cinematic product interface.",
    href: "../apex-hypercar-showcase/",
  },
  {
    title: "Aeroform Car Showcase",
    tag: "Automotive / Three.js",
    description: "Premium scroll-driven car showcase with GLTF vehicles, airflow visualization, and 360 inspection.",
    href: "../car/",
  },
  {
    title: "AeroRank Vehicle System",
    tag: "Automotive / R3F System",
    description: "Futuristic vehicle ranking interface with 3D cars, boot scans, aerodynamic airflow, pressure data, and cinematic system states.",
    href: "../aero-rank-system/",
  },
  {
    title: "Car Engine Lab",
    tag: "Education / 2D + 3D Engines",
    description: "Interactive engine learning lab with animated 2D diagrams, procedural 3D models, component isolation, cutaway and x-ray modes, torque graphs, and side-by-side comparison for combustion, hybrid, electric, turbo, and supercharged engines.",
    href: "../car-engine-lab/",
  },
  {
    title: "ARCTIS / SIGNAL",
    tag: "Immersive / WebGL",
    description: "Realtime brand world with cinematic scroll-driven 3D choreography.",
    href: "../arctis-signal/",
  },
  {
    title: "Noema Vault",
    tag: "Storyworld / Archive",
    description: "Atmospheric scrollytelling prototype built around memory as architecture.",
    href: "../noema-vault/",
  },
  {
    title: "UIUXPRO",
    tag: "Design / Interface",
    description: "Friendly pet grooming landing page with polished responsive UI and booking-focused flows.",
    href: "../uiuxpro/",
  },
  {
    title: "Loreline",
    tag: "Writing / Worldbuilding",
    description: "Premium drafting, character, and lore workspace for long-form fiction.",
    href: "../loreline/",
  },
  {
    title: "AI Lab",
    tag: "Research / Sandbox",
    description: "Browser neural-network lab with a floating 3D graph workspace.",
    href: "../ai-lab/",
  },
  {
    title: "AI Lab Edge DOM",
    tag: "AI / HTML Variant",
    description: "Standalone Edge DOM variant from the AI Lab experiments.",
    href: "../ai-lab/edge-dom.html",
  },
  {
    title: "AI Lab Edge DOM 2",
    tag: "AI / HTML Variant",
    description: "Second standalone Edge DOM variant from the AI Lab experiments.",
    href: "../ai-lab/edge-dom-2.html",
  },
  {
    title: "AI Lab Edge DOM 3",
    tag: "AI / HTML Variant",
    description: "Third standalone Edge DOM variant from the AI Lab experiments.",
    href: "../ai-lab/edge-dom-3.html",
  },
  {
    title: "AI Lab Edge DOM 4",
    tag: "AI / HTML Variant",
    description: "Fourth standalone Edge DOM variant from the AI Lab experiments.",
    href: "../ai-lab/edge-dom-4.html",
  },
  {
    title: "AI Lab Edge DOM Custom",
    tag: "AI / HTML Variant",
    description: "Custom standalone Edge DOM variant from the AI Lab experiments.",
    href: "../ai-lab/edge-dom-custom.html",
  },
  {
    title: "AI Lab Edge DOM Custom 2",
    tag: "AI / HTML Variant",
    description: "Second custom standalone Edge DOM variant from the AI Lab experiments.",
    href: "../ai-lab/edge-dom-custom-2.html",
  },
  {
    title: "Electric Circuit Lab",
    tag: "Education / Simulation",
    description: "Lessons, circuit building, simulation, and electronics practice in one app.",
    href: "../electric-circuit-lab/",
  },
  {
    title: "Freeform",
    tag: "Workspace / Canvas",
    description: "Project boards and canvas launching in a clean browser workspace.",
    href: "../freeform/",
  },
  {
    title: "Infinite Canvas",
    tag: "Workspace / Canvas",
    description: "Direct launch into the standalone Freeform infinite canvas workspace.",
    href: "../freeform/canvas.html",
  },
  {
    title: "Infinite Canvas Live",
    tag: "Workspace / Canvas",
    description: "Live standalone Freeform canvas build kept as its own HTML launch path.",
    href: "../freeform/live.html",
  },
  {
    title: "Freeform Backup",
    tag: "Archive / Canvas",
    description: "Earlier infinite-canvas workspace snapshot kept available as a backup launch path.",
    href: "../freeform-backup/",
  },
  {
    title: "Games",
    tag: "Arcade / Experiments",
    description: "Browser mini-games and interaction experiments collected in one hub.",
    href: "../games/",
  },
  {
    title: "Handtracking Lab",
    tag: "Camera / Gesture",
    description: "MediaPipe hand-tracking experiment with gesture readouts and layered canvas effects.",
    href: "../handtracking/",
  },
  {
    title: "House Builder",
    tag: "3D / Modular",
    description: "Modular building playground for assembling houses in the browser.",
    href: "../house-builder/",
  },
  {
    title: "Three.js",
    tag: "Cinematic / Scene Lab",
    description: "Local Three.js experiments and realtime visual prototypes.",
    href: "../threejs/",
  },
  {
    title: "Infinite Void To Shrine",
    tag: "Three.js / Scene Study",
    description: "Standalone Three.js scene that moves from an infinite void into a shrine-like environment.",
    href: "../threejs/other-project.html",
  },
  {
    title: "Project Atlas",
    tag: "Portfolio / Immersive",
    description: "Cinematic portfolio experience with premium motion and 3D presentation.",
    href: "../cinematic-portfolio/",
  },
  {
    title: "Bible",
    tag: "External / Reference",
    description: "Redirect launch path for the Bible project hosted on the external GitHub Pages site.",
    href: "../bible/",
  },
  {
    title: "TNHX",
    tag: "SVG / Drawing",
    description: "Small SVG drawing study with layered geometric forms.",
    href: "../tnhx/",
  },
  {
    title: "Random Triangles",
    tag: "SVG / Drawing Test",
    description: "Direct launch for the TNHX random triangle drawing test page.",
    href: "../tnhx/test.html",
  },
  {
    title: "Translator",
    tag: "Tool / Interface",
    description: "Analog-inspired Morse translator with tactile controls.",
    href: "../translator/",
  },
  {
    title: "Junha2010.github.io",
    tag: "External / Personal Site",
    description: "External site link for the broader web presence.",
    href: "https://junha2010.github.io/",
    external: true,
  },
];
