export const projects = [
  {
    title: "Loop DAW",
    tag: "Music / Composition Tool",
    description: "Beginner-friendly browser DAW with a draggable piano roll, loop playback, Web Audio instruments, mixer controls, presets, and save/export.",
    href: "../loop-daw/",
  },
  {
    title: "Code Workspace",
    tag: "Developer Tool / Monaco",
    description: "Browser-based VS Code-inspired workspace with Monaco editing, files, tabs, command palette, terminal, themes, and simulated extensions.",
    href: "../code-workspace/",
  },
  {
    title: "Entity Diagnostic System",
    tag: "Identity / R3F State Machine",
    description: "Controlled diagnostic interface where scroll advances system states, identity selection updates ranked entity data, and a reactive 3D core performs the analysis.",
    href: "../entity-diagnostic-system/",
  },
  {
    title: "Physics Engine Playground",
    tag: "Physics / Simulator",
    description: "Interactive physics laboratory with real Matter.js 2D experiments, Three.js/cannon-es 3D rigid bodies, debug vectors, trails, and draggable objects.",
    href: "../physics-engine-playground/physics-engine-playground.html",
  },
  {
    title: "Terrain Generator",
    tag: "Procedural / WebGL Tool",
    description: "Realtime terrain creation tool with procedural noise, erosion, brush editing, chunked Three.js rendering, and heightmap or mesh export.",
    href: "../terrain-generator/",
  },
  {
    title: "Igloo Experience",
    tag: "Homepage / Immersive",
    description: "Scene-only version of the Never Wet homepage with interactive brick disassembly and snowfall.",
    href: "../igloo-home/",
  },
  {
    title: "Aeroform Car Showcase",
    tag: "Automotive / Three.js",
    description: "Premium scroll-driven car showcase with GLTF vehicles, airflow visualization, and 360 inspection.",
    href: "../car/",
  },
  {
    title: "AeroRank Vehicle System",
    tag: "Automotive / R3F System",
    description: "Futuristic vehicle ranking interface with 3D cars, boot scans, aerodynamic airflow, pressure data, and cinematic system states.",
    href: "../aero-rank-system/",
  },
  {
    title: "ARCTIS / SIGNAL",
    tag: "Immersive / WebGL",
    description: "Realtime brand world with cinematic scroll-driven 3D choreography.",
    href: "../arctis-signal/",
  },
  {
    title: "Noema Vault",
    tag: "Storyworld / Archive",
    description: "Atmospheric scrollytelling prototype built around memory as architecture.",
    href: "../noema-vault/",
  },
  {
    title: "UIUXPRO",
    tag: "Design / Interface",
    description: "Friendly pet grooming landing page with polished responsive UI and booking-focused flows.",
    href: "../uiuxpro/",
  },
  {
    title: "Loreline",
    tag: "Writing / Worldbuilding",
    description: "Premium drafting, character, and lore workspace for long-form fiction.",
    href: "../loreline/",
  },
  {
    title: "AI Lab",
    tag: "Research / Sandbox",
    description: "Browser neural-network lab with a floating 3D graph workspace.",
    href: "../ai-lab/",
  },
  {
    title: "Electric Circuit Lab",
    tag: "Education / Simulation",
    description: "Lessons, circuit building, simulation, and electronics practice in one app.",
    href: "../electric-circuit-lab/",
  },
  {
    title: "Freeform",
    tag: "Workspace / Canvas",
    description: "Project boards and canvas launching in a clean browser workspace.",
    href: "../freeform/",
  },
  {
    title: "Freeform Backup",
    tag: "Archive / Canvas",
    description: "Earlier infinite-canvas workspace snapshot kept available as a backup launch path.",
    href: "../freeform-backup/",
  },
  {
    title: "Games",
    tag: "Arcade / Experiments",
    description: "Browser mini-games and interaction experiments collected in one hub.",
    href: "../games/",
  },
  {
    title: "Handtracking Lab",
    tag: "Camera / Gesture",
    description: "MediaPipe hand-tracking experiment with gesture readouts and layered canvas effects.",
    href: "../handtracking/",
  },
  {
    title: "House Builder",
    tag: "3D / Modular",
    description: "Modular building playground for assembling houses in the browser.",
    href: "../house-builder/",
  },
  {
    title: "Three.js",
    tag: "Cinematic / Scene Lab",
    description: "Local Three.js experiments and realtime visual prototypes.",
    href: "../threejs/",
  },
  {
    title: "Project Atlas",
    tag: "Portfolio / Immersive",
    description: "Cinematic portfolio experience with premium motion and 3D presentation.",
    href: "../cinematic-portfolio/",
  },
  {
    title: "Bible",
    tag: "External / Reference",
    description: "Redirect launch path for the Bible project hosted on the external GitHub Pages site.",
    href: "../bible/",
  },
  {
    title: "TNHX",
    tag: "SVG / Drawing",
    description: "Small SVG drawing study with layered geometric forms.",
    href: "../tnhx/",
  },
  {
    title: "Translator",
    tag: "Tool / Interface",
    description: "Analog-inspired Morse translator with tactile controls.",
    href: "../translator/",
  },
  {
    title: "Junha2010.github.io",
    tag: "External / Personal Site",
    description: "External site link for the broader web presence.",
    href: "https://junha2010.github.io/",
    external: true,
  },
];
