import type { ComponentDefinition, ParameterSchema, TerminalDefinition } from './types'

const twoTerminal = (
  leftId: string,
  rightId: string,
  leftRole: TerminalDefinition['role'] = 'bidirectional',
  rightRole: TerminalDefinition['role'] = 'bidirectional',
): TerminalDefinition[] => [
  { id: leftId, label: leftId, role: leftRole, x: -56, y: 0 },
  { id: rightId, label: rightId, role: rightRole, x: 56, y: 0 },
]

const numberParameter = (
  id: string,
  label: string,
  defaultValue: number,
  extras: Partial<ParameterSchema> = {},
): ParameterSchema => ({
  id,
  label,
  type: 'number',
  defaultValue,
  ...extras,
})

const booleanParameter = (
  id: string,
  label: string,
  defaultValue: boolean,
  extras: Partial<ParameterSchema> = {},
): ParameterSchema => ({
  id,
  label,
  type: 'boolean',
  defaultValue,
  ...extras,
})

const selectParameter = (
  id: string,
  label: string,
  defaultValue: string,
  options: ParameterSchema['options'],
  extras: Partial<ParameterSchema> = {},
): ParameterSchema => ({
  id,
  label,
  type: 'select',
  defaultValue,
  options,
  ...extras,
})

export const componentIndex: ComponentDefinition[] = [
  {
    id: 'battery',
    name: 'Battery',
    shortName: 'BAT',
    category: 'sources',
    symbol: 'Battery',
    description: 'A DC voltage source that energizes the circuit.',
    educationalSummary: 'Use batteries to create a voltage difference that can drive current around a closed loop.',
    terminals: twoTerminal('negative', 'positive', 'ground', 'power'),
    parameters: [
      numberParameter('voltage', 'Voltage', 9, { min: 1, max: 24, step: 0.5, unit: 'V' }),
      numberParameter('internalResistance', 'Internal R', 0.3, { min: 0, max: 10, step: 0.1, unit: 'ohm' }),
    ],
    examples: ['LED with resistor', 'Series resistor demo', 'Switch-controlled lamp'],
    validationRules: ['Connect both positive and negative into the circuit.', 'Avoid wiring positive directly to negative.'],
    formula: 'I = V / R_total',
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 60 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Multiple source support can expand into source prioritization and AC behavior later.',
    },
  },
  {
    id: 'ground',
    name: 'Ground',
    shortName: 'GND',
    category: 'sources',
    symbol: 'Ground',
    description: 'A reference node that helps learners understand the return side of a circuit.',
    educationalSummary: 'Ground does not power a circuit by itself, but it marks a useful reference node for measurements and returns.',
    terminals: [{ id: 'pin', label: 'pin', role: 'ground', x: 0, y: -20 }],
    parameters: [],
    examples: ['Return node marker', 'Logic reference', 'Grounded measurement point'],
    validationRules: ['Ground should tie to a meaningful node, often the negative side of the source.'],
    simulationSupport: 'supported',
    defaultSize: { width: 70, height: 70 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can evolve into named nets and reference rails.',
    },
  },
  {
    id: 'voltage-source',
    name: 'Variable Voltage Source',
    shortName: 'V-SRC',
    category: 'sources',
    symbol: 'Source',
    description: 'A configurable voltage supply for experiments beyond a basic battery.',
    educationalSummary: 'Use a variable source when you want to study how voltage changes the behavior of a circuit.',
    terminals: twoTerminal('negative', 'positive', 'ground', 'power'),
    parameters: [numberParameter('voltage', 'Voltage', 5, { min: 1, max: 18, step: 0.1, unit: 'V' })],
    examples: ['Sensor thresholds', 'LED current comparison', 'Logic supply demo'],
    validationRules: ['Tie negative into the return path.', 'Change voltage carefully when low-resistance paths exist.'],
    formula: 'Power = V x I',
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 60 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future updates can add regulated rails and waveform sources.',
    },
  },
  {
    id: 'resistor',
    name: 'Resistor',
    shortName: 'R',
    category: 'passive',
    symbol: 'Resistor',
    description: 'Limits current and drops voltage based on its resistance.',
    educationalSummary: 'Resistors control current, set voltage drops, and protect LEDs or other sensitive loads.',
    terminals: twoTerminal('a', 'b'),
    parameters: [numberParameter('resistance', 'Resistance', 220, { min: 1, max: 100000, step: 1, unit: 'ohm' })],
    examples: ['LED current limiting', 'Voltage drop experiments', 'Series networks'],
    validationRules: ['Use a resistor with LEDs to avoid excessive current.', 'Keep resistance positive.'],
    formula: 'V = I x R',
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 56 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future versions can support resistor color bands and measurement modes.',
    },
  },
  {
    id: 'led',
    name: 'LED',
    shortName: 'LED',
    category: 'outputs',
    symbol: 'LED',
    description: 'A diode that emits light when current flows from anode to cathode.',
    educationalSummary: 'LEDs need the correct direction and usually a series resistor to light safely.',
    terminals: twoTerminal('cathode', 'anode', 'cathode', 'anode'),
    parameters: [
      numberParameter('forwardVoltage', 'Forward V', 2, { min: 1.5, max: 3.5, step: 0.1, unit: 'V' }),
      numberParameter('resistance', 'Recommended R', 180, { min: 20, max: 2000, step: 5, unit: 'ohm' }),
      selectParameter(
        'color',
        'Color',
        'emerald',
        [
          { value: 'emerald', label: 'Emerald' },
          { value: 'amber', label: 'Amber' },
          { value: 'crimson', label: 'Crimson' },
          { value: 'ice', label: 'Ice' },
        ],
      ),
    ],
    examples: ['Simple indicator circuit', 'Switch plus LED', 'Logic output light'],
    validationRules: ['Connect anode toward the positive side of the loop.', 'Use a resistor for safe current.'],
    formula: 'I ~= (Vsource - Vf) / R',
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 56 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future simulation can include brightness curves and diode equations.',
    },
  },
  {
    id: 'lamp',
    name: 'Lamp',
    shortName: 'LAMP',
    category: 'outputs',
    symbol: 'Lamp',
    description: 'A simple bulb-like load that glows when current flows.',
    educationalSummary: 'Lamps are a beginner-friendly way to study complete loops and the effect of resistance.',
    terminals: twoTerminal('a', 'b'),
    parameters: [numberParameter('resistance', 'Resistance', 60, { min: 10, max: 1000, step: 5, unit: 'ohm' })],
    examples: ['Closed loop demo', 'Parallel branch comparison', 'Switch challenge'],
    validationRules: ['A lamp needs a full loop to turn on.'],
    formula: 'P = I^2 x R',
    simulationSupport: 'supported',
    defaultSize: { width: 112, height: 60 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can later support filament warm-up and non-linear behavior.',
    },
  },
  {
    id: 'output-indicator',
    name: 'Output Indicator',
    shortName: 'OUT',
    category: 'outputs',
    symbol: 'Output',
    description: 'A learner-friendly indicator that shows high, low, and powered states.',
    educationalSummary: 'Use output indicators to inspect logic outputs and quick state changes.',
    terminals: twoTerminal('input', 'return', 'input', 'ground'),
    parameters: [numberParameter('threshold', 'On threshold', 2.5, { min: 0.5, max: 5, step: 0.1, unit: 'V' })],
    examples: ['Gate output checker', 'Signal path demo', 'Troubleshooting target'],
    validationRules: ['Connect the return side to the reference node for clear output behavior.'],
    simulationSupport: 'supported',
    defaultSize: { width: 128, height: 60 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Later versions can include meters and oscilloscopes.',
    },
  },
  {
    id: 'switch',
    name: 'Switch',
    shortName: 'SW',
    category: 'controls',
    symbol: 'Switch',
    description: 'Toggles a circuit path open or closed.',
    educationalSummary: 'Switches teach the difference between an open circuit and a complete loop.',
    terminals: twoTerminal('a', 'b'),
    parameters: [booleanParameter('closed', 'Closed', false)],
    examples: ['LED toggle', 'Lamp circuit', 'Gate input control'],
    validationRules: ['An open switch breaks the loop.', 'A closed switch behaves like a near-zero resistance path.'],
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 56 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can later expand into SPDT and momentary switches.',
    },
  },
  {
    id: 'push-button',
    name: 'Push Button',
    shortName: 'BTN',
    category: 'controls',
    symbol: 'Button',
    description: 'A momentary control that conducts only while pressed.',
    educationalSummary: 'Push buttons are useful for practice circuits where the learner wants temporary input changes.',
    terminals: twoTerminal('a', 'b'),
    parameters: [booleanParameter('pressed', 'Pressed', false)],
    examples: ['Momentary LED', 'Input trigger', 'Practice quiz circuit'],
    validationRules: ['Pressed behaves like a closed path.', 'Released leaves the circuit open.'],
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 56 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can later support debounce timing.',
    },
  },
  {
    id: 'capacitor',
    name: 'Capacitor',
    shortName: 'C',
    category: 'passive',
    symbol: 'Capacitor',
    description: 'Stores charge and resists sudden voltage changes.',
    educationalSummary: 'Capacitors are central to timing, filtering, and energy storage, even though their full behavior is a later simulation phase here.',
    terminals: twoTerminal('a', 'b'),
    parameters: [numberParameter('capacitance', 'Capacitance', 100, { min: 1, max: 10000, step: 1, unit: 'uF' })],
    examples: ['Timing circuits', 'Smoothing experiments', 'Future transient lessons'],
    validationRules: ['In the current DC solver, a charged capacitor behaves like a nearly open path.'],
    formula: 'Q = C x V',
    simulationSupport: 'supported',
    defaultSize: { width: 112, height: 56 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'The current engine supports a steady-state DC approximation. Transient charging and discharging are planned next.',
    },
  },
  {
    id: 'inductor',
    name: 'Inductor',
    shortName: 'L',
    category: 'passive',
    symbol: 'Inductor',
    description: 'Stores energy in a magnetic field and resists sudden current changes.',
    educationalSummary: 'Inductors matter in filters and power electronics, and the architecture is prepared for their future simulation.',
    terminals: twoTerminal('a', 'b'),
    parameters: [numberParameter('inductance', 'Inductance', 10, { min: 1, max: 1000, step: 1, unit: 'mH' })],
    examples: ['Filter concepts', 'Power conversion previews', 'Magnetic storage lesson'],
    validationRules: ['In the current DC solver, an inductor behaves like a low-resistance path after startup.'],
    formula: 'V = L x (dI / dt)',
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 56 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'The current engine supports a steady-state DC approximation. Dynamic current and back-EMF handling are reserved for a future pass.',
    },
  },
  {
    id: 'diode',
    name: 'Diode',
    shortName: 'D',
    category: 'advanced',
    symbol: 'Diode',
    description: 'Allows current primarily in one direction.',
    educationalSummary: 'Diodes teach direction-sensitive conduction and are the basis for LEDs and rectifiers.',
    terminals: twoTerminal('cathode', 'anode', 'cathode', 'anode'),
    parameters: [numberParameter('forwardVoltage', 'Forward V', 0.7, { min: 0.2, max: 1.2, step: 0.1, unit: 'V' })],
    examples: ['Direction checks', 'Rectifier preview', 'One-way current lesson'],
    validationRules: ['Anode to cathode is the expected forward direction.'],
    formula: 'I rises sharply after the forward threshold',
    simulationSupport: 'supported',
    defaultSize: { width: 120, height: 56 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future work can refine the conduction curve.',
    },
  },
  {
    id: 'transistor',
    name: 'Transistor',
    shortName: 'Q',
    category: 'advanced',
    symbol: 'Transistor',
    description: 'Acts like an electronically controlled switch or amplifier.',
    educationalSummary: 'Transistors unlock switching and amplification. The current lab supports a simplified transistor-as-switch model so advanced lessons can run in the browser.',
    terminals: [
      { id: 'collector', label: 'collector', role: 'collector', x: 0, y: -42 },
      { id: 'base', label: 'base', role: 'base', x: -54, y: 14 },
      { id: 'emitter', label: 'emitter', role: 'emitter', x: 38, y: 36 },
    ],
    parameters: [
      numberParameter('gain', 'Gain', 100, { min: 20, max: 300, step: 5 }),
      numberParameter('baseThreshold', 'Base threshold', 0.7, { min: 0.4, max: 2, step: 0.05, unit: 'V' }),
    ],
    examples: ['Electronic switching', 'Amplifier preview', 'Future transistor lesson'],
    validationRules: ['Drive the base relative to the emitter to switch collector-emitter conduction.', 'Use the current model as an educational switching approximation rather than a full analog transistor solve.'],
    simulationSupport: 'supported',
    defaultSize: { width: 116, height: 96 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'The current engine supports a simplified switching model. Biasing and active-region behavior are planned for the next simulation layer.',
    },
  },
  {
    id: 'and-gate',
    name: 'AND Gate',
    shortName: 'AND',
    category: 'logic',
    symbol: 'AND',
    description: 'Outputs high only when both inputs are high.',
    educationalSummary: 'AND gates help learners bridge electric circuits and logic circuits.',
    terminals: [
      { id: 'a', label: 'A', role: 'input', x: -60, y: -18 },
      { id: 'b', label: 'B', role: 'input', x: -60, y: 18 },
      { id: 'out', label: 'OUT', role: 'output', x: 60, y: 0 },
    ],
    parameters: [],
    examples: ['Two-switch logic', 'Permission circuit', 'Logic truth table demos'],
    validationRules: ['Feed both inputs with defined high or low references.'],
    simulationSupport: 'supported',
    defaultSize: { width: 132, height: 88 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can later add propagation timing and dedicated rails.',
    },
  },
  {
    id: 'or-gate',
    name: 'OR Gate',
    shortName: 'OR',
    category: 'logic',
    symbol: 'OR',
    description: 'Outputs high when either input is high.',
    educationalSummary: 'OR gates show how multiple conditions can activate a circuit output.',
    terminals: [
      { id: 'a', label: 'A', role: 'input', x: -60, y: -18 },
      { id: 'b', label: 'B', role: 'input', x: -60, y: 18 },
      { id: 'out', label: 'OUT', role: 'output', x: 60, y: 0 },
    ],
    parameters: [],
    examples: ['Alternate path logic', 'Alarm logic', 'Signal combining'],
    validationRules: ['Give both inputs a defined state for clearer logic behavior.'],
    simulationSupport: 'supported',
    defaultSize: { width: 132, height: 88 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future upgrades can support chained logic timing.',
    },
  },
  {
    id: 'not-gate',
    name: 'NOT Gate',
    shortName: 'NOT',
    category: 'logic',
    symbol: 'NOT',
    description: 'Outputs the opposite of its input.',
    educationalSummary: 'NOT gates introduce inversion and help learners reason about low versus high signals.',
    terminals: [
      { id: 'in', label: 'IN', role: 'input', x: -60, y: 0 },
      { id: 'out', label: 'OUT', role: 'output', x: 60, y: 0 },
    ],
    parameters: [],
    examples: ['Inverse LED logic', 'Basic control circuits', 'Signal inversion practice'],
    validationRules: ['Provide a meaningful input reference for clear output.'],
    simulationSupport: 'supported',
    defaultSize: { width: 128, height: 80 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future passes can add timing and pull-up or pull-down patterns.',
    },
  },
  {
    id: 'nand-gate',
    name: 'NAND Gate',
    shortName: 'NAND',
    category: 'logic',
    symbol: 'NAND',
    description: 'Outputs low only when both inputs are high.',
    educationalSummary: 'NAND gates are foundational because complex digital systems can be built from them.',
    terminals: [
      { id: 'a', label: 'A', role: 'input', x: -60, y: -18 },
      { id: 'b', label: 'B', role: 'input', x: -60, y: 18 },
      { id: 'out', label: 'OUT', role: 'output', x: 60, y: 0 },
    ],
    parameters: [],
    examples: ['Universal gate lesson', 'Logic design practice', 'Challenge circuits'],
    validationRules: ['Keep inputs defined for a predictable result.'],
    simulationSupport: 'supported',
    defaultSize: { width: 138, height: 88 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can later extend into timing and multi-gate propagation.',
    },
  },
  {
    id: 'nor-gate',
    name: 'NOR Gate',
    shortName: 'NOR',
    category: 'logic',
    symbol: 'NOR',
    description: 'Outputs high only when both inputs are low.',
    educationalSummary: 'NOR gates reinforce the idea of logic inversion across combined inputs.',
    terminals: [
      { id: 'a', label: 'A', role: 'input', x: -60, y: -18 },
      { id: 'b', label: 'B', role: 'input', x: -60, y: 18 },
      { id: 'out', label: 'OUT', role: 'output', x: 60, y: 0 },
    ],
    parameters: [],
    examples: ['Reset logic', 'Alarm logic', 'Truth table practice'],
    validationRules: ['Tie unused inputs to known states for stable logic.'],
    simulationSupport: 'supported',
    defaultSize: { width: 138, height: 88 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can later support propagation timing and feedback experiments.',
    },
  },
  {
    id: 'xor-gate',
    name: 'XOR Gate',
    shortName: 'XOR',
    category: 'logic',
    symbol: 'XOR',
    description: 'Outputs high when the inputs are different.',
    educationalSummary: 'XOR gates are great for practicing comparison logic and truth tables.',
    terminals: [
      { id: 'a', label: 'A', role: 'input', x: -60, y: -18 },
      { id: 'b', label: 'B', role: 'input', x: -60, y: 18 },
      { id: 'out', label: 'OUT', role: 'output', x: 60, y: 0 },
    ],
    parameters: [],
    examples: ['Comparator logic', 'Switch difference detector', 'Challenge practice'],
    validationRules: ['XOR behavior is clearest when both inputs are intentionally controlled.'],
    simulationSupport: 'supported',
    defaultSize: { width: 138, height: 88 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future work can add compound gate compositions and propagation delays.',
    },
  },
  {
    id: 'light-sensor',
    name: 'Light Sensor',
    shortName: 'LDR',
    category: 'sensors',
    symbol: 'Light',
    description: 'Outputs a digital high when ambient light crosses its threshold.',
    educationalSummary: 'Sensors make the sandbox feel like a real lab by letting you test responsive circuits.',
    terminals: twoTerminal('signal', 'reference', 'output', 'ground'),
    parameters: [
      numberParameter('ambient', 'Ambient', 70, { min: 0, max: 100, step: 1, unit: '%' }),
      numberParameter('threshold', 'Threshold', 60, { min: 0, max: 100, step: 1, unit: '%' }),
      booleanParameter('invert', 'Invert', false),
    ],
    examples: ['Automatic light', 'Sensor gate input', 'Threshold lesson'],
    validationRules: ['Signal is compared against threshold in phase 1.'],
    simulationSupport: 'supported',
    defaultSize: { width: 132, height: 64 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Can later support analog sensor curves.',
    },
  },
  {
    id: 'temperature-sensor',
    name: 'Temperature Sensor',
    shortName: 'TEMP',
    category: 'sensors',
    symbol: 'Temp',
    description: 'Outputs a digital high when the temperature passes the chosen threshold.',
    educationalSummary: 'Threshold-driven sensors are useful for learning control logic and environmental triggers.',
    terminals: twoTerminal('signal', 'reference', 'output', 'ground'),
    parameters: [
      numberParameter('temperature', 'Temperature', 24, { min: -10, max: 120, step: 1, unit: 'C' }),
      numberParameter('threshold', 'Threshold', 30, { min: -10, max: 120, step: 1, unit: 'C' }),
      booleanParameter('invert', 'Invert', false),
    ],
    examples: ['Cooling fan logic', 'Alarm threshold', 'Sensor challenge'],
    validationRules: ['The sensor compares temperature to threshold in the current engine.'],
    simulationSupport: 'supported',
    defaultSize: { width: 146, height: 64 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Analog transfer functions can arrive later.',
    },
  },
  {
    id: 'proximity-sensor',
    name: 'Proximity Sensor',
    shortName: 'PROX',
    category: 'sensors',
    symbol: 'Prox',
    description: 'Outputs a digital high when a target is within range.',
    educationalSummary: 'Proximity sensors make experimentation feel more like a physical prototype lab.',
    terminals: twoTerminal('signal', 'reference', 'output', 'ground'),
    parameters: [
      numberParameter('distance', 'Distance', 10, { min: 0, max: 100, step: 1, unit: 'cm' }),
      numberParameter('threshold', 'Threshold', 15, { min: 1, max: 100, step: 1, unit: 'cm' }),
      booleanParameter('invert', 'Invert', false),
    ],
    examples: ['Presence detection', 'Logic trigger', 'Sensor sandbox experiments'],
    validationRules: ['The sensor uses a threshold comparison in phase 1.'],
    simulationSupport: 'supported',
    defaultSize: { width: 146, height: 64 },
    phaseSupport: {
      phase1: true,
      phase2Notes: 'Future work can add analog range intensity and noise.',
    },
  },
]
