import { appManifest } from './appManifest'
import { componentIndex } from './componentIndex'
import { lessonIndex } from './lessonIndex'
import { performanceConfig } from './performanceConfig'
import { quizIndex } from './quizIndex'
import { simulationManifest } from './simulationManifest'
import { uiManifest } from './uiManifest'
import type { SampleCircuitDefinition } from './types'

const createdAt = '2026-04-19T00:00:00.000Z'

export const sampleCircuitIndex: SampleCircuitDefinition[] = [
  {
    id: 'starter-led',
    title: 'Starter LED Loop',
    summary: 'A beginner-safe LED loop with a switch, resistor, battery, and grounded return.',
    learningFocus: ['closed loop', 'resistor current limiting', 'switch behavior'],
    circuit: {
      id: 'sample-starter-led',
      name: 'Starter LED Loop',
      description: 'A clean beginner circuit that shows the difference between open and closed loops.',
      mode: 'guided',
      createdAt,
      updatedAt: createdAt,
      linkedLessonId: 'current-voltage-basics',
      tags: ['starter', 'led', 'guided'],
      board: {
        placementMode: 'grid',
        zoom: performanceConfig.defaultBoardZoom,
        pan: performanceConfig.defaultBoardPan,
        showGrid: true,
      },
      components: [
        {
          id: 'bat-1',
          typeId: 'battery',
          position: { x: -250, y: 10 },
          rotation: 0,
          flipX: false,
          params: { voltage: 9, internalResistance: 0.3 },
        },
        {
          id: 'sw-1',
          typeId: 'switch',
          position: { x: -70, y: 10 },
          rotation: 0,
          flipX: false,
          params: { closed: true },
        },
        {
          id: 'r-1',
          typeId: 'resistor',
          position: { x: 110, y: 10 },
          rotation: 0,
          flipX: false,
          params: { resistance: 220 },
        },
        {
          id: 'led-1',
          typeId: 'led',
          position: { x: 300, y: 10 },
          rotation: 0,
          flipX: false,
          params: { forwardVoltage: 2, resistance: 180, color: 'emerald' },
        },
        {
          id: 'gnd-1',
          typeId: 'ground',
          position: { x: 110, y: 130 },
          rotation: 0,
          flipX: false,
          params: {},
        },
      ],
      wires: [
        {
          id: 'wire-1',
          from: { componentId: 'bat-1', terminalId: 'positive' },
          to: { componentId: 'sw-1', terminalId: 'a' },
        },
        {
          id: 'wire-2',
          from: { componentId: 'sw-1', terminalId: 'b' },
          to: { componentId: 'r-1', terminalId: 'a' },
        },
        {
          id: 'wire-3',
          from: { componentId: 'r-1', terminalId: 'b' },
          to: { componentId: 'led-1', terminalId: 'anode' },
        },
        {
          id: 'wire-4',
          from: { componentId: 'led-1', terminalId: 'cathode' },
          to: { componentId: 'gnd-1', terminalId: 'pin' },
        },
        {
          id: 'wire-5',
          from: { componentId: 'bat-1', terminalId: 'negative' },
          to: { componentId: 'gnd-1', terminalId: 'pin' },
        },
      ],
    },
  },
  {
    id: 'parallel-lamps',
    title: 'Parallel Lamp Branches',
    summary: 'Two lamp branches in parallel to show how current can split across paths.',
    learningFocus: ['parallel branches', 'equivalent resistance', 'branch debugging'],
    circuit: {
      id: 'sample-parallel-lamps',
      name: 'Parallel Lamp Branches',
      description: 'A simple branch circuit used for parallel reasoning and troubleshooting.',
      mode: 'guided',
      createdAt,
      updatedAt: createdAt,
      linkedLessonId: 'series-parallel',
      tags: ['parallel', 'lamps', 'guided'],
      board: {
        placementMode: 'grid',
        zoom: performanceConfig.defaultBoardZoom,
        pan: { x: 420, y: 240 },
        showGrid: true,
      },
      components: [
        {
          id: 'bat-2',
          typeId: 'battery',
          position: { x: -260, y: 20 },
          rotation: 0,
          flipX: false,
          params: { voltage: 9, internalResistance: 0.3 },
        },
        {
          id: 'sw-2',
          typeId: 'switch',
          position: { x: -100, y: 20 },
          rotation: 0,
          flipX: false,
          params: { closed: true },
        },
        {
          id: 'lamp-1',
          typeId: 'lamp',
          position: { x: 120, y: -60 },
          rotation: 0,
          flipX: false,
          params: { resistance: 70 },
        },
        {
          id: 'lamp-2',
          typeId: 'lamp',
          position: { x: 120, y: 100 },
          rotation: 0,
          flipX: false,
          params: { resistance: 70 },
        },
        {
          id: 'gnd-2',
          typeId: 'ground',
          position: { x: -20, y: 180 },
          rotation: 0,
          flipX: false,
          params: {},
        },
      ],
      wires: [
        {
          id: 'wire-p1',
          from: { componentId: 'bat-2', terminalId: 'positive' },
          to: { componentId: 'sw-2', terminalId: 'a' },
        },
        {
          id: 'wire-p2',
          from: { componentId: 'sw-2', terminalId: 'b' },
          to: { componentId: 'lamp-1', terminalId: 'a' },
        },
        {
          id: 'wire-p3',
          from: { componentId: 'sw-2', terminalId: 'b' },
          to: { componentId: 'lamp-2', terminalId: 'a' },
        },
        {
          id: 'wire-p4',
          from: { componentId: 'lamp-1', terminalId: 'b' },
          to: { componentId: 'gnd-2', terminalId: 'pin' },
        },
        {
          id: 'wire-p5',
          from: { componentId: 'lamp-2', terminalId: 'b' },
          to: { componentId: 'gnd-2', terminalId: 'pin' },
        },
        {
          id: 'wire-p6',
          from: { componentId: 'bat-2', terminalId: 'negative' },
          to: { componentId: 'gnd-2', terminalId: 'pin' },
        },
      ],
    },
  },
  {
    id: 'logic-and-demo',
    title: 'Two-Switch AND Gate',
    summary: 'A digital logic practice circuit that lights the indicator only when both switches are on.',
    learningFocus: ['logic gates', 'high and low', 'input combinations'],
    circuit: {
      id: 'sample-logic-and',
      name: 'Two-Switch AND Gate',
      description: 'A logic demo linking two manual inputs to an AND gate and output indicator.',
      mode: 'guided',
      createdAt,
      updatedAt: createdAt,
      linkedLessonId: 'logic-intro',
      tags: ['logic', 'and', 'guided'],
      board: {
        placementMode: 'grid',
        zoom: performanceConfig.defaultBoardZoom,
        pan: { x: 410, y: 240 },
        showGrid: true,
      },
      components: [
        {
          id: 'src-logic',
          typeId: 'voltage-source',
          position: { x: -280, y: 10 },
          rotation: 0,
          flipX: false,
          params: { voltage: 5 },
        },
        {
          id: 'sw-a',
          typeId: 'switch',
          position: { x: -90, y: -70 },
          rotation: 0,
          flipX: false,
          params: { closed: true },
        },
        {
          id: 'sw-b',
          typeId: 'switch',
          position: { x: -90, y: 90 },
          rotation: 0,
          flipX: false,
          params: { closed: false },
        },
        {
          id: 'gate-and',
          typeId: 'and-gate',
          position: { x: 110, y: 10 },
          rotation: 0,
          flipX: false,
          params: {},
        },
        {
          id: 'indicator-1',
          typeId: 'output-indicator',
          position: { x: 330, y: 10 },
          rotation: 0,
          flipX: false,
          params: { threshold: 2.5 },
        },
        {
          id: 'gnd-logic',
          typeId: 'ground',
          position: { x: 60, y: 170 },
          rotation: 0,
          flipX: false,
          params: {},
        },
      ],
      wires: [
        {
          id: 'wire-l1',
          from: { componentId: 'src-logic', terminalId: 'positive' },
          to: { componentId: 'sw-a', terminalId: 'a' },
        },
        {
          id: 'wire-l2',
          from: { componentId: 'src-logic', terminalId: 'positive' },
          to: { componentId: 'sw-b', terminalId: 'a' },
        },
        {
          id: 'wire-l3',
          from: { componentId: 'sw-a', terminalId: 'b' },
          to: { componentId: 'gate-and', terminalId: 'a' },
        },
        {
          id: 'wire-l4',
          from: { componentId: 'sw-b', terminalId: 'b' },
          to: { componentId: 'gate-and', terminalId: 'b' },
        },
        {
          id: 'wire-l5',
          from: { componentId: 'gate-and', terminalId: 'out' },
          to: { componentId: 'indicator-1', terminalId: 'input' },
        },
        {
          id: 'wire-l6',
          from: { componentId: 'indicator-1', terminalId: 'return' },
          to: { componentId: 'gnd-logic', terminalId: 'pin' },
        },
        {
          id: 'wire-l7',
          from: { componentId: 'src-logic', terminalId: 'negative' },
          to: { componentId: 'gnd-logic', terminalId: 'pin' },
        },
      ],
    },
  },
  {
    id: 'capacitor-preview',
    title: 'Capacitor DC Preview',
    summary: 'A resistor-capacitor loop used to explain why the current DC model treats capacitors like a nearly open path after charging.',
    learningFocus: ['capacitor approximation', 'steady-state DC', 'reading simulator notes'],
    circuit: {
      id: 'sample-capacitor-preview',
      name: 'Capacitor DC Preview',
      description: 'A steady-state capacitor example for comparing the current phase-1 DC approximation with real transient behavior.',
      mode: 'guided',
      createdAt,
      updatedAt: createdAt,
      linkedLessonId: 'capacitor-inductor-dc',
      tags: ['capacitor', 'dc', 'guided'],
      board: {
        placementMode: 'grid',
        zoom: performanceConfig.defaultBoardZoom,
        pan: { x: 420, y: 240 },
        showGrid: true,
      },
      components: [
        {
          id: 'bat-cap',
          typeId: 'battery',
          position: { x: -250, y: 20 },
          rotation: 0,
          flipX: false,
          params: { voltage: 9, internalResistance: 0.3 },
        },
        {
          id: 'sw-cap',
          typeId: 'switch',
          position: { x: -90, y: 20 },
          rotation: 0,
          flipX: false,
          params: { closed: true },
        },
        {
          id: 'r-cap',
          typeId: 'resistor',
          position: { x: 90, y: 20 },
          rotation: 0,
          flipX: false,
          params: { resistance: 330 },
        },
        {
          id: 'cap-1',
          typeId: 'capacitor',
          position: { x: 280, y: 20 },
          rotation: 0,
          flipX: false,
          params: { capacitance: 220 },
        },
        {
          id: 'gnd-cap',
          typeId: 'ground',
          position: { x: 90, y: 170 },
          rotation: 0,
          flipX: false,
          params: {},
        },
      ],
      wires: [
        {
          id: 'wire-cap-1',
          from: { componentId: 'bat-cap', terminalId: 'positive' },
          to: { componentId: 'sw-cap', terminalId: 'a' },
        },
        {
          id: 'wire-cap-2',
          from: { componentId: 'sw-cap', terminalId: 'b' },
          to: { componentId: 'r-cap', terminalId: 'a' },
        },
        {
          id: 'wire-cap-3',
          from: { componentId: 'r-cap', terminalId: 'b' },
          to: { componentId: 'cap-1', terminalId: 'a' },
        },
        {
          id: 'wire-cap-4',
          from: { componentId: 'cap-1', terminalId: 'b' },
          to: { componentId: 'gnd-cap', terminalId: 'pin' },
        },
        {
          id: 'wire-cap-5',
          from: { componentId: 'bat-cap', terminalId: 'negative' },
          to: { componentId: 'gnd-cap', terminalId: 'pin' },
        },
      ],
    },
  },
  {
    id: 'transistor-switch',
    title: 'Transistor Switch Demo',
    summary: 'A simplified transistor-controlled LED load using a separate base-drive source.',
    learningFocus: ['transistor as switch', 'base threshold', 'separate control and load paths'],
    circuit: {
      id: 'sample-transistor-switch',
      name: 'Transistor Switch Demo',
      description: 'A browser-friendly transistor switching exercise that keeps the control path and load path visually separate.',
      mode: 'guided',
      createdAt,
      updatedAt: createdAt,
      linkedLessonId: 'transistor-switching',
      tags: ['transistor', 'switching', 'guided'],
      board: {
        placementMode: 'grid',
        zoom: performanceConfig.defaultBoardZoom,
        pan: { x: 430, y: 250 },
        showGrid: true,
      },
      components: [
        {
          id: 'bat-load',
          typeId: 'battery',
          position: { x: -280, y: 40 },
          rotation: 0,
          flipX: false,
          params: { voltage: 9, internalResistance: 0.3 },
        },
        {
          id: 'src-base',
          typeId: 'voltage-source',
          position: { x: -280, y: -120 },
          rotation: 0,
          flipX: false,
          params: { voltage: 5 },
        },
        {
          id: 'sw-base',
          typeId: 'switch',
          position: { x: -90, y: -120 },
          rotation: 0,
          flipX: false,
          params: { closed: true },
        },
        {
          id: 'r-load',
          typeId: 'resistor',
          position: { x: -80, y: 40 },
          rotation: 0,
          flipX: false,
          params: { resistance: 220 },
        },
        {
          id: 'led-load',
          typeId: 'led',
          position: { x: 110, y: 40 },
          rotation: 0,
          flipX: false,
          params: { forwardVoltage: 2, resistance: 180, color: 'amber' },
        },
        {
          id: 'q-1',
          typeId: 'transistor',
          position: { x: 310, y: 70 },
          rotation: 0,
          flipX: false,
          params: { gain: 120, baseThreshold: 0.7 },
        },
        {
          id: 'gnd-tr',
          typeId: 'ground',
          position: { x: 110, y: 210 },
          rotation: 0,
          flipX: false,
          params: {},
        },
      ],
      wires: [
        {
          id: 'wire-tr-1',
          from: { componentId: 'bat-load', terminalId: 'positive' },
          to: { componentId: 'r-load', terminalId: 'a' },
        },
        {
          id: 'wire-tr-2',
          from: { componentId: 'r-load', terminalId: 'b' },
          to: { componentId: 'led-load', terminalId: 'anode' },
        },
        {
          id: 'wire-tr-3',
          from: { componentId: 'led-load', terminalId: 'cathode' },
          to: { componentId: 'q-1', terminalId: 'collector' },
        },
        {
          id: 'wire-tr-4',
          from: { componentId: 'q-1', terminalId: 'emitter' },
          to: { componentId: 'gnd-tr', terminalId: 'pin' },
        },
        {
          id: 'wire-tr-5',
          from: { componentId: 'bat-load', terminalId: 'negative' },
          to: { componentId: 'gnd-tr', terminalId: 'pin' },
        },
        {
          id: 'wire-tr-6',
          from: { componentId: 'src-base', terminalId: 'positive' },
          to: { componentId: 'sw-base', terminalId: 'a' },
        },
        {
          id: 'wire-tr-7',
          from: { componentId: 'sw-base', terminalId: 'b' },
          to: { componentId: 'q-1', terminalId: 'base' },
        },
        {
          id: 'wire-tr-8',
          from: { componentId: 'src-base', terminalId: 'negative' },
          to: { componentId: 'gnd-tr', terminalId: 'pin' },
        },
      ],
    },
  },
  {
    id: 'sensor-alert',
    title: 'Sensor Alert Logic',
    summary: 'A light sensor driving an indicator so learners can test threshold-based digital behavior.',
    learningFocus: ['sensor threshold', 'digital high and low', 'indicator response'],
    circuit: {
      id: 'sample-sensor-alert',
      name: 'Sensor Alert Logic',
      description: 'A threshold-driven sensor example that turns an indicator on when ambient light crosses the chosen level.',
      mode: 'guided',
      createdAt,
      updatedAt: createdAt,
      tags: ['sensor', 'logic', 'guided'],
      board: {
        placementMode: 'grid',
        zoom: performanceConfig.defaultBoardZoom,
        pan: { x: 420, y: 230 },
        showGrid: true,
      },
      components: [
        {
          id: 'sensor-1',
          typeId: 'light-sensor',
          position: { x: -80, y: 20 },
          rotation: 0,
          flipX: false,
          params: { ambient: 75, threshold: 60, invert: false },
        },
        {
          id: 'indicator-sensor',
          typeId: 'output-indicator',
          position: { x: 160, y: 20 },
          rotation: 0,
          flipX: false,
          params: { threshold: 2.5 },
        },
        {
          id: 'gnd-sensor',
          typeId: 'ground',
          position: { x: 40, y: 150 },
          rotation: 0,
          flipX: false,
          params: {},
        },
      ],
      wires: [
        {
          id: 'wire-sensor-1',
          from: { componentId: 'sensor-1', terminalId: 'signal' },
          to: { componentId: 'indicator-sensor', terminalId: 'input' },
        },
        {
          id: 'wire-sensor-2',
          from: { componentId: 'sensor-1', terminalId: 'reference' },
          to: { componentId: 'gnd-sensor', terminalId: 'pin' },
        },
        {
          id: 'wire-sensor-3',
          from: { componentId: 'indicator-sensor', terminalId: 'return' },
          to: { componentId: 'gnd-sensor', terminalId: 'pin' },
        },
      ],
    },
  },
  {
    id: 'blank-sandbox',
    title: 'Blank Sandbox Board',
    summary: 'An empty board for free experimentation.',
    learningFocus: ['freeform experimentation', 'builder practice', 'playground'],
    circuit: {
      id: 'sample-blank-sandbox',
      name: 'Blank Sandbox Board',
      description: 'A ready-to-build blank workspace.',
      mode: 'sandbox',
      createdAt,
      updatedAt: createdAt,
      tags: ['sandbox'],
      board: {
        placementMode: 'grid',
        zoom: performanceConfig.defaultBoardZoom,
        pan: performanceConfig.defaultBoardPan,
        showGrid: true,
      },
      components: [],
      wires: [],
    },
  },
]

export const componentRegistry = Object.fromEntries(componentIndex.map((component) => [component.id, component]))
export const lessonRegistry = Object.fromEntries(lessonIndex.map((lesson) => [lesson.id, lesson]))
export const quizRegistry = Object.fromEntries(quizIndex.map((quiz) => [quiz.id, quiz]))
export const sampleCircuitRegistry = Object.fromEntries(
  sampleCircuitIndex.map((sample) => [sample.id, sample]),
)

export const contentRegistry = {
  appManifest,
  uiManifest,
  simulationManifest,
  performanceConfig,
  components: componentIndex,
  lessons: lessonIndex,
  quizzes: quizIndex,
  sampleCircuits: sampleCircuitIndex,
}
