import type { LessonDefinition } from './types'

export const lessonIndex: LessonDefinition[] = [
  {
    id: 'current-voltage-basics',
    title: 'Current and Voltage Basics',
    difficulty: 'beginner',
    duration: '8 min',
    summary: 'Learn what pushes charge and what actually flows in a closed circuit.',
    prerequisites: [],
    goals: [
      'Explain voltage as an electrical push.',
      'Explain current as moving charge in a loop.',
      'Identify why open circuits stop current.',
    ],
    concepts: ['voltage', 'current', 'source', 'closed loop'],
    steps: [
      'Start with the LED starter circuit and run the simulation.',
      'Open and close the switch to compare the powered path.',
      'Watch how the simulation log describes a complete versus broken loop.',
    ],
    checkpoints: [
      'You can point to the source, load, and return path.',
      'You can explain why a broken loop stops current.',
      'You can tell the difference between voltage and current in plain language.',
    ],
    commonMistakes: [
      'Thinking voltage itself moves through the wire like current.',
      'Assuming one wire from a battery is enough to power a part.',
      'Treating ground as a power source instead of a reference or return node.',
    ],
    challengePrompt: 'Can you explain why a battery alone does not light an LED without a return path?',
    relatedQuizId: 'predict-led',
    sampleCircuitId: 'starter-led',
    exampleComponentIds: ['battery', 'switch', 'resistor', 'led', 'ground'],
  },
  {
    id: 'ohms-law',
    title: "Ohm's Law in Practice",
    difficulty: 'beginner',
    duration: '10 min',
    summary: 'Use resistors to predict current and voltage drop in simple loops.',
    prerequisites: ['current-voltage-basics'],
    goals: [
      "Use Ohm's law to estimate current.",
      'Relate larger resistance to lower current.',
      'Understand why resistors protect LEDs.',
    ],
    concepts: ['resistance', 'ohms law', 'voltage drop', 'current limiting'],
    steps: [
      'Change the resistor value in the starter circuit.',
      'Run the simulation after each change.',
      'Compare the estimated current and LED brightness feedback.',
    ],
    checkpoints: [
      'You can predict whether current should rise or fall before pressing Run.',
      'You can explain why resistors create voltage drop.',
      'You can choose a safer resistor value for an LED loop.',
    ],
    commonMistakes: [
      'Increasing voltage and resistance together without tracking the ratio.',
      'Assuming LEDs can be wired directly across a battery safely.',
      'Ignoring the unit when reading resistance values.',
    ],
    challengePrompt: 'What resistor change would make the LED dimmer without breaking the loop?',
    relatedQuizId: 'series-current',
    sampleCircuitId: 'starter-led',
    exampleComponentIds: ['resistor', 'led', 'battery'],
  },
  {
    id: 'series-parallel',
    title: 'Series and Parallel Paths',
    difficulty: 'intermediate',
    duration: '12 min',
    summary: 'Explore how branches behave differently from a single series path.',
    prerequisites: ['ohms-law'],
    goals: [
      'Compare a series path with parallel branches.',
      'Explain why each parallel branch can still receive source voltage.',
      'Read branch current summaries in the simulator.',
    ],
    concepts: ['series circuit', 'parallel circuit', 'branch current', 'shared source'],
    steps: [
      'Load the parallel lamps sample.',
      'Observe how both lamps connect across the same source.',
      'Inspect the simulation notes and branch summaries.',
    ],
    checkpoints: [
      'You can identify where current splits and where it recombines.',
      'You can explain why parallel branches reduce equivalent resistance.',
      'You can compare branch current values instead of guessing by appearance.',
    ],
    commonMistakes: [
      'Thinking voltage gets divided the same way current divides in every circuit.',
      'Assuming removing one branch always kills the entire circuit.',
      'Confusing a branch node with a source terminal.',
    ],
    challengePrompt: 'Can you predict what happens if one branch is removed from a parallel lamp circuit?',
    relatedQuizId: 'parallel-troubleshoot',
    sampleCircuitId: 'parallel-lamps',
    exampleComponentIds: ['lamp', 'resistor', 'battery', 'switch'],
  },
  {
    id: 'switches-leds',
    title: 'Switches, Buttons, and LEDs',
    difficulty: 'beginner',
    duration: '9 min',
    summary: 'Practice control inputs and output indicators with simple wiring changes.',
    prerequisites: ['current-voltage-basics'],
    goals: [
      'Use a switch to control a loop.',
      'Use a push button as a momentary input.',
      'Inspect output state feedback in the right panel.',
    ],
    concepts: ['switch', 'push button', 'led', 'state feedback'],
    steps: [
      'Swap a toggle switch for a push button.',
      'Run the simulator with the button pressed and released.',
      'Watch the component state feedback update.',
    ],
    checkpoints: [
      'You can predict what an open versus closed control will do before simulating.',
      'You can wire a momentary path that only turns on while pressed.',
      'You can read the inspector to confirm the control state.',
    ],
    commonMistakes: [
      'Leaving the return path disconnected while blaming the switch.',
      'Treating a push button like a latching switch.',
      'Forgetting the LED polarity while testing the control.',
    ],
    challengePrompt: 'Can you wire one LED to turn on only while the button is pressed?',
    relatedQuizId: 'build-led-loop',
    sampleCircuitId: 'starter-led',
    exampleComponentIds: ['switch', 'push-button', 'led', 'output-indicator'],
  },
  {
    id: 'logic-intro',
    title: 'Logic Gates and Digital Thinking',
    difficulty: 'intermediate',
    duration: '14 min',
    summary: 'Move from electric current to decision-making circuits using logic gates.',
    prerequisites: ['switches-leds'],
    goals: [
      'Interpret high and low input states.',
      'Predict an AND gate output from two switches.',
      'Connect a logic output to an indicator.',
    ],
    concepts: ['logic gate', 'and', 'or', 'not', 'digital signal'],
    steps: [
      'Load the AND gate sample circuit.',
      'Toggle each switch and run the simulation.',
      'Compare the indicator output to the truth table in the inspector and scope.',
    ],
    checkpoints: [
      'You can explain what makes an input high or low.',
      'You can predict the AND output before running the simulator.',
      'You can trace a digital signal from input to indicator.',
    ],
    commonMistakes: [
      'Treating a floating logic input like a guaranteed low state.',
      'Mixing analog load reasoning with digital truth-table reasoning.',
      'Forgetting to connect the return node for the indicator.',
    ],
    challengePrompt: 'When does the indicator turn on in the AND gate circuit, and why?',
    relatedQuizId: 'logic-and-output',
    sampleCircuitId: 'logic-and-demo',
    exampleComponentIds: ['and-gate', 'switch', 'output-indicator', 'ground'],
  },
  {
    id: 'capacitor-inductor-dc',
    title: 'Capacitors and Inductors in DC',
    difficulty: 'intermediate',
    duration: '11 min',
    summary: 'Understand the steady-state DC approximation: capacitors tend toward open paths and inductors tend toward low resistance.',
    prerequisites: ['series-parallel'],
    goals: [
      'Explain what a capacitor does after charging in DC.',
      'Explain why an inductor behaves differently over time than at steady state.',
      'Use the simulator notes to separate approximation from real transient behavior.',
    ],
    concepts: ['capacitor', 'inductor', 'steady state', 'transient'],
    steps: [
      'Load the capacitor preview sample circuit.',
      'Run the simulation and inspect the component notes and warnings.',
      'Swap the capacitor for an inductor and compare the resulting loop behavior.',
    ],
    checkpoints: [
      'You can describe what the current engine means by a DC steady-state approximation.',
      'You can predict whether a capacitor or inductor will allow more DC current in the current model.',
      'You can explain why the app still labels transient behavior as future work.',
    ],
    commonMistakes: [
      'Expecting the static DC solve to show real-time charging curves.',
      'Assuming capacitor and inductor behavior is identical in DC.',
      'Ignoring simulator notes that call out educational approximations.',
    ],
    challengePrompt: 'Why does a capacitor look almost open in the DC model while an inductor looks almost shorted?',
    relatedQuizId: 'capacitor-dc-behavior',
    sampleCircuitId: 'capacitor-preview',
    exampleComponentIds: ['capacitor', 'inductor', 'battery', 'resistor'],
  },
  {
    id: 'transistor-switching',
    title: 'Transistor Switching',
    difficulty: 'advanced',
    duration: '13 min',
    summary: 'Use a transistor as a simplified electronically controlled switch between a load and ground.',
    prerequisites: ['logic-intro'],
    goals: [
      'Recognize the collector, base, and emitter roles.',
      'Explain why the base controls conduction in the current model.',
      'Use a control signal to switch a separate load path.',
    ],
    concepts: ['transistor', 'base drive', 'controlled switch', 'load path'],
    steps: [
      'Load the transistor switch sample.',
      'Toggle the base-drive switch and compare the transistor state note.',
      'Trace how the load branch turns on only when the base rises above threshold.',
    ],
    checkpoints: [
      'You can identify the control path and the load path separately.',
      'You can explain what base threshold means in the current model.',
      'You can tell why the LED stays off when base drive is removed.',
    ],
    commonMistakes: [
      'Treating the transistor like a two-terminal resistor.',
      'Assuming the base terminal directly powers the load branch.',
      'Ignoring the emitter reference when reasoning about base threshold.',
    ],
    challengePrompt: 'What changes on the board when the transistor turns on, and which path is actually carrying load current?',
    relatedQuizId: 'transistor-base-control',
    sampleCircuitId: 'transistor-switch',
    exampleComponentIds: ['transistor', 'battery', 'switch', 'led', 'resistor'],
  },
  {
    id: 'troubleshooting-patterns',
    title: 'Troubleshooting Opens, Shorts, and Miswires',
    difficulty: 'intermediate',
    duration: '12 min',
    summary: 'Practice diagnosing open branches, direct shorts, and wrong-path wiring using the board and inspector together.',
    prerequisites: ['series-parallel'],
    goals: [
      'Spot the difference between an open path and a short-circuit risk.',
      'Use warnings, branch summaries, and component notes together.',
      'Work backward from a dark output to the missing or incorrect connection.',
    ],
    concepts: ['open circuit', 'short circuit', 'branch diagnosis', 'debugging workflow'],
    steps: [
      'Load a sample circuit and intentionally break a branch.',
      'Run the simulator and compare the warning list with the branch summaries.',
      'Repair the path and confirm the output and current values change as expected.',
    ],
    checkpoints: [
      'You can name one likely cause for an open branch and one for a short-circuit risk.',
      'You can use the inspector instead of only guessing from the visual board.',
      'You can repair a broken loop and verify the fix in simulation.',
    ],
    commonMistakes: [
      'Blaming the source when only one branch is disconnected.',
      'Assuming a bright path always means a correct path.',
      'Changing multiple wires at once and losing track of the real fault.',
    ],
    challengePrompt: 'Can you describe a repeatable workflow for finding the one broken connection in a larger circuit?',
    relatedQuizId: 'short-circuit-risk',
    sampleCircuitId: 'parallel-lamps',
    exampleComponentIds: ['switch', 'lamp', 'battery', 'ground', 'resistor'],
  },
]
