import type { LessonDefinition } from './types'

export const lessonIndex: LessonDefinition[] = [
  {
    id: 'current-voltage-basics',
    title: 'Current and Voltage Basics',
    difficulty: 'beginner',
    duration: '8 min',
    summary: 'Learn what pushes charge and what actually flows in a closed circuit.',
    prerequisites: [],
    goals: [
      'Explain voltage as an electrical push.',
      'Explain current as moving charge in a loop.',
      'Identify why open circuits stop current.',
    ],
    concepts: ['voltage', 'current', 'source', 'closed loop'],
    steps: [
      'Start with the LED starter circuit and run the simulation.',
      'Open and close the switch to compare the powered path.',
      'Watch how the simulation log describes a complete versus broken loop.',
    ],
    challengePrompt: 'Can you explain why a battery alone does not light an LED without a return path?',
    sampleCircuitId: 'starter-led',
    exampleComponentIds: ['battery', 'switch', 'resistor', 'led', 'ground'],
  },
  {
    id: 'ohms-law',
    title: "Ohm's Law in Practice",
    difficulty: 'beginner',
    duration: '10 min',
    summary: 'Use resistors to predict current and voltage drop in simple loops.',
    prerequisites: ['current-voltage-basics'],
    goals: [
      "Use Ohm's law to estimate current.",
      'Relate larger resistance to lower current.',
      'Understand why resistors protect LEDs.',
    ],
    concepts: ['resistance', 'ohms law', 'voltage drop', 'current limiting'],
    steps: [
      'Change the resistor value in the starter circuit.',
      'Run the simulation after each change.',
      'Compare the estimated current and LED brightness feedback.',
    ],
    challengePrompt: 'What resistor change would make the LED dimmer without breaking the loop?',
    sampleCircuitId: 'starter-led',
    exampleComponentIds: ['resistor', 'led', 'battery'],
  },
  {
    id: 'series-parallel',
    title: 'Series and Parallel Paths',
    difficulty: 'intermediate',
    duration: '12 min',
    summary: 'Explore how branches behave differently from a single series path.',
    prerequisites: ['ohms-law'],
    goals: [
      'Compare a series path with parallel branches.',
      'Explain why each parallel branch can still receive source voltage.',
      'Read current distribution warnings in the simulator.',
    ],
    concepts: ['series circuit', 'parallel circuit', 'branch current', 'shared source'],
    steps: [
      'Load the parallel lamps sample.',
      'Observe how both lamps connect across the same source.',
      'Inspect the simulation notes about equivalent resistance.',
    ],
    challengePrompt: 'Can you predict what happens if one branch is removed from a parallel lamp circuit?',
    sampleCircuitId: 'parallel-lamps',
    exampleComponentIds: ['lamp', 'resistor', 'battery', 'switch'],
  },
  {
    id: 'switches-leds',
    title: 'Switches, Buttons, and LEDs',
    difficulty: 'beginner',
    duration: '9 min',
    summary: 'Practice control inputs and output indicators with simple wiring changes.',
    prerequisites: ['current-voltage-basics'],
    goals: [
      'Use a switch to control a loop.',
      'Use a push button as a momentary input.',
      'Inspect output state feedback in the right panel.',
    ],
    concepts: ['switch', 'push button', 'led', 'state feedback'],
    steps: [
      'Swap a toggle switch for a push button.',
      'Run the simulator with the button pressed and released.',
      'Watch the component state feedback update.',
    ],
    challengePrompt: 'Can you wire one LED to turn on only while the button is pressed?',
    sampleCircuitId: 'starter-led',
    exampleComponentIds: ['switch', 'push-button', 'led', 'output-indicator'],
  },
  {
    id: 'logic-intro',
    title: 'Logic Gates and Digital Thinking',
    difficulty: 'intermediate',
    duration: '14 min',
    summary: 'Move from electric current to decision-making circuits using logic gates.',
    prerequisites: ['switches-leds'],
    goals: [
      'Interpret high and low input states.',
      'Predict an AND gate output from two switches.',
      'Connect a logic output to an indicator.',
    ],
    concepts: ['logic gate', 'and', 'or', 'not', 'digital signal'],
    steps: [
      'Load the AND gate sample circuit.',
      'Toggle each switch and run the simulation.',
      'Compare the indicator output to the truth table in the formula dock.',
    ],
    challengePrompt: 'When does the indicator turn on in the AND gate circuit, and why?',
    sampleCircuitId: 'logic-and-demo',
    exampleComponentIds: ['and-gate', 'switch', 'output-indicator', 'ground'],
  },
]
