import type { QuizDefinition } from './types'

export const quizIndex: QuizDefinition[] = [
  {
    id: 'identify-resistor',
    title: 'Identify the Resistor',
    difficulty: 'beginner',
    kind: 'component-match',
    prompt: 'Which component is mainly used to limit current in a simple LED circuit?',
    hint: 'Look for the part whose main job is to oppose current flow.',
    explanation: 'A resistor limits current and creates a voltage drop, which helps protect LEDs.',
    tags: ['resistor', 'basics'],
    choices: [
      { id: 'battery', label: 'Battery' },
      { id: 'resistor', label: 'Resistor' },
      { id: 'ground', label: 'Ground' },
      { id: 'switch', label: 'Switch' },
    ],
    correctChoiceId: 'resistor',
  },
  {
    id: 'predict-led',
    title: 'Will the LED Turn On?',
    difficulty: 'beginner',
    kind: 'prediction',
    prompt: 'In the starter LED circuit, what happens if the switch stays open?',
    hint: 'Think about whether the loop is complete.',
    explanation: 'An open switch breaks the loop, so current cannot flow and the LED stays off.',
    sampleCircuitId: 'starter-led',
    tags: ['prediction', 'switch', 'led'],
    choices: [
      { id: 'on', label: 'The LED turns on brightly.' },
      { id: 'off', label: 'The LED stays off.' },
      { id: 'blink', label: 'The LED blinks slowly.' },
      { id: 'short', label: 'The battery shorts immediately.' },
    ],
    correctChoiceId: 'off',
  },
  {
    id: 'series-current',
    title: 'Series Current Reasoning',
    difficulty: 'beginner',
    kind: 'multiple-choice',
    prompt: 'If you increase the series resistor value in a battery-LED-resistor circuit, what usually happens to current?',
    hint: "Apply Ohm's law: current equals voltage divided by resistance.",
    explanation: 'Increasing resistance lowers current when the source voltage stays the same.',
    tags: ['ohms-law', 'series'],
    choices: [
      { id: 'rises', label: 'Current rises.' },
      { id: 'falls', label: 'Current falls.' },
      { id: 'same', label: 'Current stays exactly the same.' },
      { id: 'reverses', label: 'Current reverses direction.' },
    ],
    correctChoiceId: 'falls',
  },
  {
    id: 'parallel-troubleshoot',
    title: 'Troubleshoot the Parallel Lamps',
    difficulty: 'intermediate',
    kind: 'troubleshooting',
    prompt: 'A parallel lamp circuit only lights one lamp. What is the most likely issue with the dark branch?',
    hint: 'Each branch needs its own complete path back to the source.',
    explanation: 'If one branch is dark while the other works, the dark branch is likely open or disconnected.',
    sampleCircuitId: 'parallel-lamps',
    tags: ['parallel', 'troubleshooting'],
    choices: [
      { id: 'open-branch', label: 'That branch is open or disconnected.' },
      { id: 'battery-dead', label: 'The battery has no voltage at all.' },
      { id: 'too-many-grounds', label: 'There are too many ground symbols.' },
      { id: 'lamp-too-bright', label: 'The lamp is receiving too much logic input.' },
    ],
    correctChoiceId: 'open-branch',
  },
  {
    id: 'build-led-loop',
    title: 'Build a Safe LED Loop',
    difficulty: 'beginner',
    kind: 'build-check',
    prompt: 'Use the builder to create a closed loop that includes a battery, a resistor, an LED, and a return path.',
    hint: 'The LED should not connect directly across the battery without a resistor.',
    explanation:
      'A valid beginner LED loop usually needs a source, a resistor for current limiting, an LED, and a closed return path.',
    tags: ['builder', 'led', 'challenge'],
    expectedBuild: {
      requiredTypes: ['battery', 'resistor', 'led'],
      minimumWires: 4,
      mustBeClosedLoop: true,
      requiredPoweredTypes: ['led'],
      notes: [
        'Include a source and return path.',
        'Use at least one resistor in the active loop.',
        'The LED should be on when the loop is complete.',
      ],
    },
  },
  {
    id: 'logic-and-output',
    title: 'AND Gate Output',
    difficulty: 'intermediate',
    kind: 'prediction',
    prompt: 'In the AND gate demo, when is the output indicator high?',
    hint: 'AND requires every input to be high.',
    explanation: 'The AND output becomes high only when both input switches provide a high state.',
    sampleCircuitId: 'logic-and-demo',
    tags: ['logic', 'and-gate'],
    choices: [
      { id: 'both', label: 'Only when both switches are on.' },
      { id: 'either', label: 'When either switch is on.' },
      { id: 'neither', label: 'Only when both are off.' },
      { id: 'always', label: 'It stays high all the time.' },
    ],
    correctChoiceId: 'both',
  },
  {
    id: 'capacitor-dc-behavior',
    title: 'Capacitor in DC Steady State',
    difficulty: 'intermediate',
    kind: 'multiple-choice',
    prompt: 'In the current educational DC model, how does a capacitor behave after charging?',
    hint: 'The simulator is focusing on steady-state DC, not the instant you first connect power.',
    explanation: 'In the current DC approximation, the capacitor tends toward an open path after charging, so current falls toward zero.',
    sampleCircuitId: 'capacitor-preview',
    tags: ['capacitor', 'dc', 'steady-state'],
    choices: [
      { id: 'open', label: 'It behaves like a nearly open path.' },
      { id: 'short', label: 'It behaves like a short all the time.' },
      { id: 'source', label: 'It becomes a new voltage source.' },
      { id: 'gate', label: 'It turns into a logic gate.' },
    ],
    correctChoiceId: 'open',
  },
  {
    id: 'transistor-base-control',
    title: 'Transistor Base Control',
    difficulty: 'advanced',
    kind: 'prediction',
    prompt: 'In the transistor switch demo, what makes the LED load path turn on in the current model?',
    hint: 'Look at the relationship between base drive and emitter reference.',
    explanation: 'The simplified model turns the transistor on when the base rises enough above the emitter, allowing collector-emitter conduction.',
    sampleCircuitId: 'transistor-switch',
    tags: ['transistor', 'base', 'switching'],
    choices: [
      { id: 'base-high', label: 'The base goes high enough relative to the emitter.' },
      { id: 'collector-high', label: 'The collector is always high.' },
      { id: 'led-forward', label: 'The LED decides when the transistor turns on.' },
      { id: 'ground-floating', label: 'The ground symbol becomes a source.' },
    ],
    correctChoiceId: 'base-high',
  },
  {
    id: 'short-circuit-risk',
    title: 'Spot the Short-Circuit Risk',
    difficulty: 'intermediate',
    kind: 'troubleshooting',
    prompt: 'Which change is most likely to create a short-circuit risk in a simple source-and-load circuit?',
    hint: 'Think about the equivalent resistance the source would see.',
    explanation: 'Bypassing the intended load or resistor creates a very low-resistance path, which behaves like a short-circuit risk.',
    tags: ['short-circuit', 'troubleshooting', 'safety'],
    choices: [
      { id: 'bypass-load', label: 'Wiring source positive almost directly back to return around the load.' },
      { id: 'add-branch', label: 'Adding a well-wired second lamp branch.' },
      { id: 'use-ground', label: 'Adding a ground reference node.' },
      { id: 'rename-circuit', label: 'Saving the circuit under a different name.' },
    ],
    correctChoiceId: 'bypass-load',
  },
  {
    id: 'build-parallel-branches',
    title: 'Build Two Parallel Branches',
    difficulty: 'intermediate',
    kind: 'build-check',
    prompt: 'Build a working parallel circuit with one source, one switch, two lamps, and a grounded return.',
    hint: 'Both lamps should share the source but each needs its own complete branch.',
    explanation:
      'A correct parallel build uses one source and return, splits into at least two active branches, and powers both lamps.',
    tags: ['builder', 'parallel', 'branches'],
    expectedBuild: {
      requiredTypes: ['battery', 'switch', 'lamp', 'ground'],
      requiredTypeCounts: {
        lamp: 2,
      },
      minimumWires: 6,
      mustBeClosedLoop: true,
      minimumBranches: 2,
      requiredPoweredTypes: ['lamp'],
      notes: [
        'Use one source and one return path.',
        'Create at least two lamp branches.',
        'Both lamp branches should be part of the powered result.',
      ],
    },
  },
]
