import type { AssetDefinition } from "./types";

export const assetManifest: AssetDefinition[] = [
  {
    id: "logo-hollowmere",
    kind: "logo",
    label: "Game Logo",
    variant: "title-seal",
    palette: {
      primary: "#101727",
      secondary: "#294162",
      accent: "#e0b968",
      ink: "#f5f0da",
      light: "#7bd2ff",
    },
  },
  {
    id: "bg-home",
    kind: "background",
    label: "Landing Hero",
    variant: "storm-spire",
    palette: {
      primary: "#0f1020",
      secondary: "#1d2f40",
      accent: "#f2bb6b",
      ink: "#f7f3e8",
      light: "#7fc3ff",
    },
    caption: "Skyglass Spire under a split moon.",
  },
  {
    id: "bg-thornwake",
    kind: "background",
    label: "Thornwake",
    variant: "lantern-town",
    palette: {
      primary: "#11141f",
      secondary: "#3f2f2c",
      accent: "#e09a49",
      ink: "#f4ebd3",
      light: "#7cc0b6",
    },
  },
  {
    id: "bg-gloamwood",
    kind: "background",
    label: "Gloamwood Reach",
    variant: "forest-veil",
    palette: {
      primary: "#0a1915",
      secondary: "#18362c",
      accent: "#9ed486",
      ink: "#e7f2db",
      light: "#7bc7b3",
    },
  },
  {
    id: "bg-rainmire",
    kind: "background",
    label: "Rainmire Crossing",
    variant: "marsh-bridge",
    palette: {
      primary: "#101a20",
      secondary: "#31404b",
      accent: "#98c68a",
      ink: "#e8f3ef",
      light: "#85d6ff",
    },
  },
  {
    id: "bg-abbey",
    kind: "background",
    label: "Saint Veyra Abbey",
    variant: "abbey-ruin",
    palette: {
      primary: "#111218",
      secondary: "#2d3444",
      accent: "#cda868",
      ink: "#f3ecdf",
      light: "#8fb3ff",
    },
  },
  {
    id: "bg-spire",
    kind: "background",
    label: "Skyglass Spire",
    variant: "star-observatory",
    palette: {
      primary: "#090b18",
      secondary: "#25335c",
      accent: "#e16868",
      ink: "#f7f5ff",
      light: "#7ed6ff",
    },
  },
  {
    id: "portrait-rowan",
    kind: "portrait",
    label: "Rowan Vale",
    variant: "wanderer",
    palette: {
      primary: "#293347",
      secondary: "#6e4a47",
      accent: "#e3be72",
      ink: "#f8e9dc",
      light: "#90d0ff",
    },
  },
  {
    id: "portrait-mira",
    kind: "portrait",
    label: "Mira Quill",
    variant: "scribe-mage",
    palette: {
      primary: "#2a2442",
      secondary: "#5d4979",
      accent: "#8ee6de",
      ink: "#f8e5f2",
      light: "#9fd2ff",
    },
  },
  {
    id: "portrait-nessa",
    kind: "portrait",
    label: "Nessa Reed",
    variant: "ranger",
    palette: {
      primary: "#1d2d28",
      secondary: "#4f6f48",
      accent: "#d8b86f",
      ink: "#eff1de",
      light: "#8fd0b0",
    },
  },
  {
    id: "portrait-caldus",
    kind: "portrait",
    label: "Brother Caldus",
    variant: "pilgrim",
    palette: {
      primary: "#2f3047",
      secondary: "#6a5d4a",
      accent: "#e3d59e",
      ink: "#f4f0ea",
      light: "#9eb8ff",
    },
  },
  {
    id: "portrait-elric",
    kind: "portrait",
    label: "Captain Elric Thorn",
    variant: "knight",
    palette: {
      primary: "#2b2533",
      secondary: "#5c3d3c",
      accent: "#d9a462",
      ink: "#f5e8dc",
      light: "#bcc7ff",
    },
  },
  {
    id: "portrait-sera",
    kind: "portrait",
    label: "Sera Vale",
    variant: "innkeeper",
    palette: {
      primary: "#352321",
      secondary: "#724137",
      accent: "#e4b16c",
      ink: "#fff1e4",
      light: "#ffd6a1",
    },
  },
  {
    id: "portrait-ivo",
    kind: "portrait",
    label: "Ivo Pell",
    variant: "apothecary",
    palette: {
      primary: "#17302d",
      secondary: "#2f635a",
      accent: "#9fd089",
      ink: "#ecfff4",
      light: "#9bf2d0",
    },
  },
  {
    id: "portrait-fen",
    kind: "portrait",
    label: "Fen Hollow",
    variant: "smuggler",
    palette: {
      primary: "#23222f",
      secondary: "#504766",
      accent: "#9ec8b1",
      ink: "#f7eefc",
      light: "#8fd9d0",
    },
  },
  {
    id: "portrait-isolde",
    kind: "portrait",
    label: "Isolde Vey",
    variant: "archivist",
    palette: {
      primary: "#23293a",
      secondary: "#55627f",
      accent: "#d4c08f",
      ink: "#fdf7ea",
      light: "#abd1ff",
    },
  },
  {
    id: "portrait-edda",
    kind: "portrait",
    label: "Edda Thorn",
    variant: "child",
    palette: {
      primary: "#2b2c48",
      secondary: "#655c91",
      accent: "#f2c694",
      ink: "#fff0f4",
      light: "#d2e7ff",
    },
  },
  {
    id: "portrait-maelin",
    kind: "portrait",
    label: "Sister Maelin",
    variant: "abbess",
    palette: {
      primary: "#1a2130",
      secondary: "#4a6179",
      accent: "#d8d8f2",
      ink: "#f1f8ff",
      light: "#a9cfff",
    },
  },
  {
    id: "portrait-vael",
    kind: "portrait",
    label: "Regent Vael",
    variant: "regent",
    palette: {
      primary: "#1a1731",
      secondary: "#4a355e",
      accent: "#ee6c7d",
      ink: "#f8edf8",
      light: "#8fc8ff",
    },
  },
  {
    id: "portrait-lyessa",
    kind: "portrait",
    label: "Lyessa Vale",
    variant: "star-keeper",
    palette: {
      primary: "#201f3e",
      secondary: "#48588d",
      accent: "#f2d39c",
      ink: "#fbf7ff",
      light: "#9bd8ff",
    },
  },
  {
    id: "portrait-briar-wolf",
    kind: "portrait",
    label: "Briar Wolf",
    variant: "wolf",
    palette: {
      primary: "#1d2117",
      secondary: "#44562d",
      accent: "#9fd372",
      ink: "#eef7df",
      light: "#b6ffd5",
    },
  },
  {
    id: "portrait-hollow-moth",
    kind: "portrait",
    label: "Hollow Moth",
    variant: "moth",
    palette: {
      primary: "#27253c",
      secondary: "#60567a",
      accent: "#e8d8b4",
      ink: "#fff9ef",
      light: "#c8d0ff",
    },
  },
  {
    id: "portrait-mireling",
    kind: "portrait",
    label: "Mireling",
    variant: "mireling",
    palette: {
      primary: "#152622",
      secondary: "#315249",
      accent: "#8fb89a",
      ink: "#e8fff5",
      light: "#9ce0c3",
    },
  },
  {
    id: "portrait-glass-cantor",
    kind: "portrait",
    label: "Glass Cantor",
    variant: "cantor",
    palette: {
      primary: "#251a34",
      secondary: "#5f4c82",
      accent: "#ff98af",
      ink: "#fff1f7",
      light: "#a8c8ff",
    },
  },
  {
    id: "portrait-ruin-sentinel",
    kind: "portrait",
    label: "Ruin Sentinel",
    variant: "sentinel",
    palette: {
      primary: "#1c1f25",
      secondary: "#576271",
      accent: "#cfc2a3",
      ink: "#f8f7f2",
      light: "#d2e8ff",
    },
  },
  {
    id: "portrait-lantern-leech",
    kind: "portrait",
    label: "Lantern Leech",
    variant: "leech",
    palette: {
      primary: "#132432",
      secondary: "#2a5d79",
      accent: "#90f2ff",
      ink: "#effcff",
      light: "#b8ffff",
    },
  },
  {
    id: "portrait-shade-archer",
    kind: "portrait",
    label: "Shade Archer",
    variant: "archer",
    palette: {
      primary: "#25212f",
      secondary: "#514d62",
      accent: "#c8b892",
      ink: "#fff6eb",
      light: "#b8cfff",
    },
  },
  {
    id: "portrait-mossback-troll",
    kind: "portrait",
    label: "Mossback Troll",
    variant: "troll",
    palette: {
      primary: "#1a211b",
      secondary: "#4e6144",
      accent: "#9aba6f",
      ink: "#f5ffe5",
      light: "#cbffbc",
    },
  },
  {
    id: "portrait-mirror-warden",
    kind: "portrait",
    label: "Mirror Warden",
    variant: "boss-mask",
    palette: {
      primary: "#10131d",
      secondary: "#3c4964",
      accent: "#9bdfff",
      ink: "#f1f9ff",
      light: "#ffffff",
    },
  },
  { id: "icon-lantern", kind: "icon", label: "Lantern", variant: "lantern", palette: { primary: "#1a2230", secondary: "#31445b", accent: "#efbe6e", ink: "#fff5de", light: "#8fd0ff" } },
  { id: "icon-sigil", kind: "icon", label: "Sigil", variant: "sigil", palette: { primary: "#221b2f", secondary: "#4d3b5b", accent: "#e0c585", ink: "#fff8e8", light: "#a7dcff" } },
  { id: "icon-pack", kind: "icon", label: "Pack", variant: "pack", palette: { primary: "#29231d", secondary: "#564635", accent: "#d8b16a", ink: "#fff4e0", light: "#acd6ff" } },
  { id: "icon-scroll", kind: "icon", label: "Scroll", variant: "scroll", palette: { primary: "#272028", secondary: "#4f4052", accent: "#d8b783", ink: "#fff5ea", light: "#a0d7ff" } },
  { id: "icon-map", kind: "icon", label: "Map", variant: "map", palette: { primary: "#18302d", secondary: "#355953", accent: "#8fd2b0", ink: "#ecfff3", light: "#8bd4ff" } },
  { id: "icon-book", kind: "icon", label: "Book", variant: "book", palette: { primary: "#252530", secondary: "#3f4a67", accent: "#e0c46d", ink: "#fffbe9", light: "#98c7ff" } },
  { id: "icon-gear", kind: "icon", label: "Gear", variant: "gear", palette: { primary: "#202530", secondary: "#44586f", accent: "#b7c7d6", ink: "#f6fbff", light: "#9de0ff" } },
  { id: "icon-star", kind: "icon", label: "Star", variant: "star", palette: { primary: "#241d2f", secondary: "#574170", accent: "#f2c46d", ink: "#fff5df", light: "#9dd2ff" } },
  { id: "icon-archive", kind: "icon", label: "Archive", variant: "archive", palette: { primary: "#262332", secondary: "#59506e", accent: "#88c6d8", ink: "#edf7ff", light: "#bbf0ff" } },
  { id: "icon-potion", kind: "icon", label: "Potion", variant: "potion", palette: { primary: "#182535", secondary: "#2f5874", accent: "#85f0ff", ink: "#effdff", light: "#bafff7" } },
  { id: "icon-blade", kind: "icon", label: "Blade", variant: "blade", palette: { primary: "#2a2230", secondary: "#4d5268", accent: "#d4a666", ink: "#fff6eb", light: "#d4eeff" } },
];
