import type { LayerKey, RouteMarker, RouteRecord } from "@/types";

export const routeColors: Record<LayerKey, [number, number, number, number]> = {
  flight: [84, 205, 255, 220],
  shipping: [38, 239, 163, 220],
  historical: [243, 181, 92, 220],
  chokepoints: [255, 83, 122, 230]
};

export const routes: RouteRecord[] = [
  {
    id: "jfk-lhr",
    name: "JFK - LHR North Atlantic Flight Path",
    type: "flight",
    layer: "flight",
    from: "JFK",
    to: "LHR",
    coordinates: [[-73.7781, 40.6413], [-0.4543, 51.47]],
    countries: ["United States", "United Kingdom", "Canada", "Ireland"],
    description: "High-density passenger and cargo connection between New York and London.",
    strategicImportance: "Core North Atlantic business corridor linking financial, diplomatic, and data-center markets.",
    strategicLevel: 5,
    status: "Heavy scheduled traffic",
    volumeLabel: "Transatlantic hub pair"
  },
  {
    id: "lax-hnd",
    name: "LAX - HND Trans-Pacific Flight Path",
    type: "flight",
    layer: "flight",
    from: "LAX",
    to: "HND",
    coordinates: [[-118.4085, 33.9416], [139.7798, 35.5494]],
    countries: ["United States", "Japan"],
    description: "Long-haul passenger, cargo, and technology corridor across the North Pacific.",
    strategicImportance: "Connects West Coast logistics and aerospace markets with Tokyo's financial and industrial networks.",
    strategicLevel: 5,
    status: "Long-haul active",
    volumeLabel: "Pacific bridge"
  },
  {
    id: "dxb-sin",
    name: "DXB - SIN Gulf-Asia Air Corridor",
    type: "flight",
    layer: "flight",
    from: "DXB",
    to: "SIN",
    coordinates: [[55.3657, 25.2532], [103.9915, 1.3644]],
    countries: ["United Arab Emirates", "India", "Sri Lanka", "Malaysia", "Singapore"],
    description: "High-frequency aviation corridor between Gulf transfer hubs and Southeast Asia.",
    strategicImportance: "Links oil, finance, tourism, and cargo flows through two global hub airports.",
    strategicLevel: 4,
    status: "Hub-to-hub flow",
    volumeLabel: "Asia-Gulf transfer"
  },
  {
    id: "cdg-dxb",
    name: "CDG - DXB Europe-Gulf Flight Path",
    type: "flight",
    layer: "flight",
    from: "CDG",
    to: "DXB",
    coordinates: [[2.55, 49.0097], [55.3657, 25.2532]],
    countries: ["France", "Italy", "Greece", "Turkey", "United Arab Emirates"],
    description: "Passenger and cargo link from continental Europe to the Gulf transfer network.",
    strategicImportance: "Moves travelers, high-value freight, and diplomatic traffic between Europe and the Middle East.",
    strategicLevel: 4,
    status: "Scheduled international",
    volumeLabel: "Europe-Gulf link"
  },
  {
    id: "fra-sin",
    name: "FRA - SIN Europe-Asia Aviation Corridor",
    type: "aviation",
    layer: "flight",
    from: "FRA",
    to: "SIN",
    coordinates: [[8.5622, 50.0379], [103.9915, 1.3644]],
    countries: ["Germany", "Turkey", "India", "Malaysia", "Singapore"],
    description: "Major commercial aviation corridor connecting European industry with Southeast Asian trade.",
    strategicImportance: "Supports air cargo, executive travel, and global supply chain coordination.",
    strategicLevel: 4,
    status: "Aviation corridor",
    volumeLabel: "Intercontinental air lane"
  },
  {
    id: "icn-lax",
    name: "ICN - LAX Pacific Gateway",
    type: "flight",
    layer: "flight",
    from: "ICN",
    to: "LAX",
    coordinates: [[126.4505, 37.4602], [-118.4085, 33.9416]],
    countries: ["South Korea", "United States"],
    description: "Korea-US passenger and freight corridor over the northern Pacific.",
    strategicImportance: "Carries electronics, e-commerce freight, and alliance travel between Seoul and California.",
    strategicLevel: 4,
    status: "Pacific gateway",
    volumeLabel: "High-value air cargo"
  },
  {
    id: "silk-road",
    name: "Silk Road",
    type: "historical",
    layer: "historical",
    coordinates: [[108.94, 34.34], [94.66, 40.14], [75.99, 39.47], [66.97, 39.65], [51.39, 35.69], [44.36, 33.31], [36.16, 36.2], [28.98, 41.01], [12.315, 45.44]],
    countries: ["China", "Kyrgyzstan", "Uzbekistan", "Iran", "Iraq", "Turkey", "Italy"],
    description: "Ancient trade route connecting East Asia and Europe.",
    strategicImportance: "Historical foundation for transcontinental commerce, cultural exchange, and modern Eurasian infrastructure thinking.",
    strategicLevel: 5,
    status: "Historical land route",
    volumeLabel: "Ancient trade network"
  },
  {
    id: "eurasian-rail-bridge",
    name: "Eurasian Land Bridge",
    type: "trade",
    layer: "historical",
    coordinates: [[121.47, 31.23], [106.55, 29.56], [87.62, 43.82], [76.89, 43.24], [71.43, 51.16], [37.62, 55.75], [21.01, 52.23], [13.4, 52.52], [4.9, 52.37]],
    countries: ["China", "Kazakhstan", "Russia", "Poland", "Germany", "Netherlands"],
    description: "Modern overland container rail connection between East Asia and European logistics centers.",
    strategicImportance: "Offers an inland complement to maritime shipping and reflects renewed interest in Eurasian trade corridors.",
    strategicLevel: 4,
    status: "Intermodal rail corridor",
    volumeLabel: "Container rail"
  },
  {
    id: "trans-saharan-route",
    name: "Trans-Saharan Trade Route",
    type: "historical",
    layer: "historical",
    coordinates: [[-3.0, 16.77], [7.99, 16.97], [13.19, 32.89]],
    countries: ["Mali", "Niger", "Libya"],
    description: "Historic caravan route moving gold, salt, scholarship, and culture across the Sahara.",
    strategicImportance: "Shows how desert crossings shaped cities, finance, and regional power before modern maritime networks.",
    strategicLevel: 3,
    status: "Historical caravan route",
    volumeLabel: "Gold-salt corridor"
  },
  {
    id: "indian-ocean-monsoon",
    name: "Indian Ocean Monsoon Trade",
    type: "historical",
    layer: "historical",
    coordinates: [[75.78, 11.26], [57.5, 15.0], [45.04, 12.78], [39.67, -4.04], [39.2, -6.16]],
    countries: ["India", "Oman", "Yemen", "Kenya", "Tanzania"],
    description: "Seasonal maritime trade route shaped by monsoon winds across the Indian Ocean.",
    strategicImportance: "Linked East Africa, Arabia, and South Asia through commerce, migration, and maritime knowledge.",
    strategicLevel: 4,
    status: "Historical sea route",
    volumeLabel: "Monsoon trade"
  },
  {
    id: "asia-europe-suez",
    name: "Asia-Europe Container Route via Suez",
    type: "shipping",
    layer: "shipping",
    coordinates: [[121.5, 31.2], [103.8, 1.25], [80.2, 6.0], [43.32, 12.62], [32.55, 30.0], [18.0, 36.5], [4.48, 51.92]],
    countries: ["China", "Singapore", "Sri Lanka", "Egypt", "Netherlands"],
    description: "Primary maritime container lane connecting East Asian manufacturing with European ports.",
    strategicImportance: "Depends on the Strait of Malacca, Bab el-Mandeb, and Suez Canal; disruption can reroute global container flows.",
    strategicLevel: 5,
    status: "Critical maritime lane",
    volumeLabel: "Asia-Europe containers"
  },
  {
    id: "gulf-energy-malacca",
    name: "Gulf Energy Route to East Asia",
    type: "shipping",
    layer: "shipping",
    coordinates: [[50.2, 26.6], [56.25, 26.57], [67.0, 24.0], [78.0, 8.0], [101.0, 2.2], [121.0, 24.0], [139.7, 35.5]],
    countries: ["Saudi Arabia", "United Arab Emirates", "Oman", "India", "Singapore", "Japan"],
    description: "Energy shipping lane moving crude oil and refined products from the Gulf toward Asian markets.",
    strategicImportance: "The route is exposed to both the Strait of Hormuz and Strait of Malacca, two major energy chokepoints.",
    strategicLevel: 5,
    status: "Energy corridor",
    volumeLabel: "Oil and LNG flow"
  },
  {
    id: "trans-pacific-container",
    name: "Trans-Pacific Container Lane",
    type: "shipping",
    layer: "shipping",
    coordinates: [[121.5, 31.2], [139.0, 35.0], [170.0, 38.0], [-150.0, 39.5], [-118.25, 33.74]],
    countries: ["China", "Japan", "United States"],
    description: "Major container route connecting East Asian export ports with the US West Coast.",
    strategicImportance: "Backbone lane for consumer goods, electronics, industrial inputs, and port-side rail distribution.",
    strategicLevel: 5,
    status: "High-capacity container lane",
    volumeLabel: "Pacific containers"
  },
  {
    id: "panama-atlantic-pacific",
    name: "Panama Canal Pacific-Atlantic Connector",
    type: "shipping",
    layer: "shipping",
    coordinates: [[-118.25, 33.74], [-104.0, 19.0], [-79.6, 9.08], [-75.0, 20.0], [-74.04, 40.68]],
    countries: ["United States", "Mexico", "Panama"],
    description: "Canal-enabled maritime path between Pacific and Atlantic trade networks.",
    strategicImportance: "Shortens vessel routes between oceans and anchors trade between the US coasts, Asia, and the Atlantic basin.",
    strategicLevel: 4,
    status: "Canal connector",
    volumeLabel: "Inter-ocean transit"
  },
  {
    id: "north-atlantic-shipping",
    name: "North Atlantic Shipping Route",
    type: "shipping",
    layer: "shipping",
    coordinates: [[-74.04, 40.68], [-45.0, 48.0], [-15.0, 51.0], [4.48, 51.92]],
    countries: ["United States", "United Kingdom", "Netherlands", "Germany"],
    description: "Dense Atlantic maritime connection between North American and European ports.",
    strategicImportance: "Carries containerized freight, energy products, vehicles, and transatlantic supply chain flows.",
    strategicLevel: 4,
    status: "Atlantic trade lane",
    volumeLabel: "US-Europe shipping"
  },
  {
    id: "asia-europe-cape-route",
    name: "Asia-Europe Cape of Good Hope Route",
    type: "shipping",
    layer: "shipping",
    coordinates: [[121.5, 31.2], [103.8, 1.25], [80.2, -6.0], [39.2, -6.16], [18.42, -34.36], [-5.6, 35.96], [4.48, 51.92]],
    countries: ["China", "Singapore", "Tanzania", "South Africa", "Spain", "Netherlands"],
    description: "Long-distance maritime alternative around southern Africa when Suez or Red Sea routes are constrained.",
    strategicImportance: "Shows the global fallback path for Asia-Europe shipping when canal or Red Sea chokepoints are disrupted.",
    strategicLevel: 5,
    status: "Strategic reroute",
    volumeLabel: "Cape diversion"
  },
  {
    id: "taiwan-strait-electronics",
    name: "Taiwan Strait Electronics Corridor",
    type: "shipping",
    layer: "shipping",
    coordinates: [[121.5, 31.2], [120.2, 23.7], [114.1, 22.3], [103.8, 1.25]],
    countries: ["China", "Taiwan", "Hong Kong", "Singapore"],
    description: "Dense near-shore shipping corridor through the Taiwan Strait and South China Sea.",
    strategicImportance: "Links semiconductor, electronics, container, and naval risk in one of the most closely watched maritime regions.",
    strategicLevel: 5,
    status: "High-sensitivity sea lane",
    volumeLabel: "Electronics and containers"
  },
  {
    id: "sunda-lombok-energy-route",
    name: "Sunda-Lombok Energy Route",
    type: "shipping",
    layer: "shipping",
    coordinates: [[103.8, 1.25], [105.9, -5.95], [115.85, -8.72], [130.0, -12.0], [151.2, -33.86]],
    countries: ["Singapore", "Indonesia", "Australia"],
    description: "Southern Indonesian strait route used by energy, bulk, and container traffic toward Australia and the Pacific.",
    strategicImportance: "Provides alternative passage options when Malacca is congested or constrained.",
    strategicLevel: 4,
    status: "Alternative strait route",
    volumeLabel: "Energy and bulk flow"
  },
  {
    id: "mediterranean-gibraltar-atlantic",
    name: "Mediterranean-Gibraltar-Atlantic Route",
    type: "shipping",
    layer: "shipping",
    coordinates: [[32.55, 30.0], [14.5, 35.9], [-5.6, 35.96], [-9.14, 38.72], [-45.0, 45.0], [-74.04, 40.68]],
    countries: ["Egypt", "Malta", "Spain", "Portugal", "United States"],
    description: "Maritime route connecting the Suez system, Mediterranean basin, Strait of Gibraltar, and North Atlantic.",
    strategicImportance: "Connects canal traffic to Atlantic markets and concentrates vessels through Gibraltar.",
    strategicLevel: 4,
    status: "Mediterranean gateway",
    volumeLabel: "Canal-to-Atlantic flow"
  },
  {
    id: "baltic-north-sea-route",
    name: "Baltic-North Sea Route",
    type: "shipping",
    layer: "shipping",
    coordinates: [[24.94, 60.17], [18.06, 59.33], [12.67, 55.7], [4.48, 51.92], [-0.1, 51.5]],
    countries: ["Finland", "Sweden", "Denmark", "Netherlands", "United Kingdom"],
    description: "Northern European sea route connecting Baltic ports to the North Sea and Atlantic logistics system.",
    strategicImportance: "Highlights the Danish Straits as the Baltic's maritime gate to wider European trade.",
    strategicLevel: 3,
    status: "Regional maritime corridor",
    volumeLabel: "Baltic containers and energy"
  },
  {
    id: "northern-sea-route",
    name: "Arctic Northern Sea Route",
    type: "shipping",
    layer: "shipping",
    coordinates: [[30.3, 69.0], [60.0, 70.0], [100.0, 73.0], [145.0, 70.0], [179.0, 66.0], [-168.8, 65.8], [-149.9, 61.2]],
    countries: ["Norway", "Russia", "United States"],
    description: "Arctic maritime route skirting northern Eurasia toward the Bering Strait and North Pacific.",
    strategicImportance: "Represents a climate-sensitive, infrastructure-heavy polar route with naval and energy implications.",
    strategicLevel: 4,
    status: "Seasonal Arctic corridor",
    volumeLabel: "Polar shipping"
  },
  {
    id: "incense-route",
    name: "Incense Route",
    type: "historical",
    layer: "historical",
    coordinates: [[45.04, 12.78], [44.2, 15.35], [39.82, 21.42], [35.21, 31.77], [34.78, 32.08]],
    countries: ["Yemen", "Saudi Arabia", "Jordan", "Israel"],
    description: "Ancient Arabian trade path carrying frankincense, myrrh, spices, and luxury goods northward.",
    strategicImportance: "Adds the Red Sea and Arabian overland trade context around Bab el-Mandeb and Suez approaches.",
    strategicLevel: 3,
    status: "Historical trade route",
    volumeLabel: "Incense and spice trade"
  },
  {
    id: "tea-horse-road",
    name: "Tea Horse Road",
    type: "historical",
    layer: "historical",
    coordinates: [[102.72, 25.04], [100.23, 26.86], [91.13, 29.65], [88.36, 27.72], [85.32, 27.71]],
    countries: ["China", "Nepal", "India"],
    description: "Historic mountain trade route linking southwest China with Tibet and South Asia.",
    strategicImportance: "Shows inland highland exchange paths beyond the better-known Silk Road corridor.",
    strategicLevel: 3,
    status: "Historical mountain route",
    volumeLabel: "Tea and horse trade"
  }
];

export const markers: RouteMarker[] = [
  {
    id: "jfk",
    name: "John F. Kennedy International Airport",
    type: "airport",
    code: "JFK",
    coordinates: [-73.7781, 40.6413],
    countries: ["United States"],
    description: "Major New York international airport and transatlantic gateway.",
    strategicImportance: "Connects North American finance, diplomacy, and cargo flows to Europe and the Middle East.",
    connectedRoutes: ["jfk-lhr"]
  },
  {
    id: "lhr",
    name: "London Heathrow Airport",
    type: "airport",
    code: "LHR",
    coordinates: [-0.4543, 51.47],
    countries: ["United Kingdom"],
    description: "Major European hub airport serving long-haul passenger and cargo movement.",
    strategicImportance: "Key bridge between Europe, North America, the Gulf, and Asia.",
    connectedRoutes: ["jfk-lhr"]
  },
  {
    id: "dxb",
    name: "Dubai International Airport",
    type: "airport",
    code: "DXB",
    coordinates: [55.3657, 25.2532],
    countries: ["United Arab Emirates"],
    description: "Global Gulf transfer hub for passenger and air cargo traffic.",
    strategicImportance: "Anchors a long-haul hub network between Europe, Africa, South Asia, and East Asia.",
    connectedRoutes: ["dxb-sin", "cdg-dxb"]
  },
  {
    id: "hnd",
    name: "Tokyo Haneda Airport",
    type: "airport",
    code: "HND",
    coordinates: [139.7798, 35.5494],
    countries: ["Japan"],
    description: "Central Tokyo airport with dense domestic and international connectivity.",
    strategicImportance: "Connects Japanese industrial, financial, and diplomatic networks to the Pacific system.",
    connectedRoutes: ["lax-hnd"]
  },
  {
    id: "sin",
    name: "Singapore Changi Airport",
    type: "airport",
    code: "SIN",
    coordinates: [103.9915, 1.3644],
    countries: ["Singapore"],
    description: "Southeast Asian aviation hub near the Strait of Malacca.",
    strategicImportance: "Pairs major aviation capacity with one of the world's most important maritime chokepoint regions.",
    connectedRoutes: ["dxb-sin", "fra-sin"]
  },
  {
    id: "icn",
    name: "Incheon International Airport",
    type: "airport",
    code: "ICN",
    coordinates: [126.4505, 37.4602],
    countries: ["South Korea"],
    description: "Korean aviation gateway with heavy passenger and logistics movement.",
    strategicImportance: "Supports electronics, e-commerce, and alliance travel across the Pacific.",
    connectedRoutes: ["icn-lax"]
  },
  {
    id: "lax",
    name: "Los Angeles International Airport",
    type: "airport",
    code: "LAX",
    coordinates: [-118.4085, 33.9416],
    countries: ["United States"],
    description: "US West Coast gateway airport for Pacific travel and freight.",
    strategicImportance: "Connects media, technology, defense, and Pacific Rim commerce.",
    connectedRoutes: ["lax-hnd", "icn-lax"]
  },
  {
    id: "cdg",
    name: "Paris Charles de Gaulle Airport",
    type: "airport",
    code: "CDG",
    coordinates: [2.55, 49.0097],
    countries: ["France"],
    description: "Major continental European hub with long-haul passenger and cargo services.",
    strategicImportance: "Supports Europe-Gulf-Asia flows and global diplomatic travel through Paris.",
    connectedRoutes: ["cdg-dxb"]
  },
  {
    id: "fra",
    name: "Frankfurt Airport",
    type: "airport",
    code: "FRA",
    coordinates: [8.5622, 50.0379],
    countries: ["Germany"],
    description: "Large European hub airport with significant air cargo and passenger capacity.",
    strategicImportance: "Links European industry and finance to Asian markets.",
    connectedRoutes: ["fra-sin"]
  },
  {
    id: "rotterdam",
    name: "Port of Rotterdam",
    type: "port",
    coordinates: [4.48, 51.92],
    countries: ["Netherlands"],
    description: "Large European seaport and inland distribution gateway.",
    strategicImportance: "Receives container, energy, and bulk cargo from Atlantic and Suez-linked routes.",
    connectedRoutes: ["asia-europe-suez", "north-atlantic-shipping"]
  },
  {
    id: "singapore-port",
    name: "Port of Singapore",
    type: "port",
    coordinates: [103.8, 1.25],
    countries: ["Singapore"],
    description: "Major transshipment port near the Strait of Malacca.",
    strategicImportance: "Concentrates container, bunker, and naval-adjacent traffic in a critical Southeast Asian maritime node.",
    connectedRoutes: ["asia-europe-suez", "gulf-energy-malacca"]
  },
  {
    id: "shanghai-port",
    name: "Port of Shanghai",
    type: "port",
    coordinates: [121.5, 31.2],
    countries: ["China"],
    description: "High-volume Chinese container port on the Yangtze River Delta.",
    strategicImportance: "A core origin point for Asia-Europe and trans-Pacific manufactured goods flows.",
    connectedRoutes: ["asia-europe-suez", "trans-pacific-container"]
  },
  {
    id: "los-angeles-port",
    name: "Port of Los Angeles / Long Beach",
    type: "port",
    coordinates: [-118.25, 33.74],
    countries: ["United States"],
    description: "Largest US West Coast container gateway complex.",
    strategicImportance: "Converts Pacific maritime traffic into rail and road flows across North America.",
    connectedRoutes: ["trans-pacific-container", "panama-atlantic-pacific"]
  },
  {
    id: "strait-of-hormuz",
    name: "Strait of Hormuz",
    type: "chokepoint",
    coordinates: [56.25, 26.57],
    countries: ["Iran", "Oman", "United Arab Emirates"],
    description: "Narrow maritime passage between the Persian Gulf and Gulf of Oman.",
    strategicImportance: "One of the world's most sensitive energy chokepoints for oil and LNG flows.",
    connectedRoutes: ["gulf-energy-malacca"]
  },
  {
    id: "suez-canal",
    name: "Suez Canal",
    type: "chokepoint",
    coordinates: [32.55, 30.0],
    countries: ["Egypt"],
    description: "Artificial waterway connecting the Red Sea and Mediterranean Sea.",
    strategicImportance: "Shortens Asia-Europe shipping and concentrates a large share of container and energy traffic.",
    connectedRoutes: ["asia-europe-suez"]
  },
  {
    id: "panama-canal",
    name: "Panama Canal",
    type: "chokepoint",
    coordinates: [-79.6, 9.08],
    countries: ["Panama"],
    description: "Artificial waterway connecting the Pacific and Atlantic oceans.",
    strategicImportance: "Critical inter-ocean shortcut for container, grain, energy, and naval movement.",
    connectedRoutes: ["panama-atlantic-pacific"]
  },
  {
    id: "strait-of-malacca",
    name: "Strait of Malacca",
    type: "chokepoint",
    coordinates: [101.0, 2.2],
    countries: ["Malaysia", "Indonesia", "Singapore"],
    description: "Narrow sea lane between the Malay Peninsula and Sumatra.",
    strategicImportance: "Major channel for East Asian energy imports and Asia-Europe container trade.",
    connectedRoutes: ["asia-europe-suez", "gulf-energy-malacca"]
  },
  {
    id: "bosporus-strait",
    name: "Bosporus Strait",
    type: "chokepoint",
    coordinates: [29.04, 41.12],
    countries: ["Turkey"],
    description: "Waterway through Istanbul connecting the Black Sea with the Sea of Marmara.",
    strategicImportance: "Controls access between Black Sea states and Mediterranean trade routes.",
    connectedRoutes: ["silk-road"]
  },
  {
    id: "bab-el-mandeb",
    name: "Bab el-Mandeb",
    type: "chokepoint",
    coordinates: [43.32, 12.62],
    countries: ["Yemen", "Djibouti", "Eritrea"],
    description: "Narrow passage linking the Red Sea and Gulf of Aden.",
    strategicImportance: "A vulnerable gateway for Suez-bound container traffic and Gulf energy shipments.",
    connectedRoutes: ["asia-europe-suez"]
  },
  {
    id: "strait-of-gibraltar",
    name: "Strait of Gibraltar",
    type: "chokepoint",
    coordinates: [-5.6, 35.96],
    countries: ["Spain", "Morocco", "United Kingdom"],
    description: "Narrow passage connecting the Mediterranean Sea and Atlantic Ocean.",
    strategicImportance: "Controls access between Mediterranean shipping, Atlantic markets, and naval movement.",
    connectedRoutes: ["asia-europe-cape-route", "mediterranean-gibraltar-atlantic"]
  },
  {
    id: "dover-strait",
    name: "Dover Strait",
    type: "chokepoint",
    coordinates: [1.6, 51.0],
    countries: ["United Kingdom", "France"],
    description: "Narrowest part of the English Channel between Dover and Calais.",
    strategicImportance: "One of Europe's busiest short-sea and ferry corridors, close to major North Sea ports.",
    connectedRoutes: ["north-atlantic-shipping", "baltic-north-sea-route"]
  },
  {
    id: "taiwan-strait",
    name: "Taiwan Strait",
    type: "chokepoint",
    coordinates: [120.2, 23.7],
    countries: ["China", "Taiwan"],
    description: "Waterway separating Taiwan from mainland China.",
    strategicImportance: "Critical commercial and military flashpoint near global semiconductor and container flows.",
    connectedRoutes: ["taiwan-strait-electronics", "trans-pacific-container"]
  },
  {
    id: "lombok-strait",
    name: "Lombok Strait",
    type: "chokepoint",
    coordinates: [115.85, -8.72],
    countries: ["Indonesia"],
    description: "Deep-water passage between Bali and Lombok.",
    strategicImportance: "Alternative route for larger vessels moving between the Indian Ocean and Pacific approaches.",
    connectedRoutes: ["sunda-lombok-energy-route"]
  },
  {
    id: "sunda-strait",
    name: "Sunda Strait",
    type: "chokepoint",
    coordinates: [105.9, -5.95],
    countries: ["Indonesia"],
    description: "Passage between Java and Sumatra linking the Java Sea and Indian Ocean.",
    strategicImportance: "Regional alternative to Malacca with volcanic, congestion, and navigational constraints.",
    connectedRoutes: ["sunda-lombok-energy-route"]
  },
  {
    id: "danish-straits",
    name: "Danish Straits",
    type: "chokepoint",
    coordinates: [12.67, 55.7],
    countries: ["Denmark", "Sweden", "Germany"],
    description: "System of passages connecting the Baltic Sea with the North Sea.",
    strategicImportance: "Controls Baltic maritime access for trade, energy, and naval movement.",
    connectedRoutes: ["baltic-north-sea-route"]
  },
  {
    id: "dardanelles-strait",
    name: "Dardanelles Strait",
    type: "chokepoint",
    coordinates: [26.4, 40.18],
    countries: ["Turkey"],
    description: "Waterway linking the Aegean Sea to the Sea of Marmara.",
    strategicImportance: "Works with the Bosporus as part of the Turkish Straits system controlling Black Sea access.",
    connectedRoutes: ["silk-road"]
  },
  {
    id: "bering-strait",
    name: "Bering Strait",
    type: "chokepoint",
    coordinates: [-168.8, 65.8],
    countries: ["United States", "Russia"],
    description: "Arctic passage between Alaska and Russia connecting the Pacific and Arctic oceans.",
    strategicImportance: "A polar gateway for Arctic shipping, surveillance, and strategic mobility.",
    connectedRoutes: ["northern-sea-route"]
  },
  {
    id: "korea-strait",
    name: "Korea Strait",
    type: "chokepoint",
    coordinates: [129.3, 34.6],
    countries: ["South Korea", "Japan"],
    description: "Sea passage between Korea and Japan connecting the East China Sea and Sea of Japan.",
    strategicImportance: "Important for Northeast Asian shipping, energy, naval movement, and air-sea logistics.",
    connectedRoutes: ["trans-pacific-container", "icn-lax"]
  },
  {
    id: "mozambique-channel",
    name: "Mozambique Channel",
    type: "chokepoint",
    coordinates: [40.0, -18.0],
    countries: ["Mozambique", "Madagascar"],
    description: "Major western Indian Ocean passage between Mozambique and Madagascar.",
    strategicImportance: "Supports Indian Ocean reroutes, energy movement, and southern Africa maritime access.",
    connectedRoutes: ["asia-europe-cape-route"]
  },
  {
    id: "cape-of-good-hope",
    name: "Cape of Good Hope",
    type: "chokepoint",
    coordinates: [18.42, -34.36],
    countries: ["South Africa"],
    description: "Southern African maritime turning point between the Atlantic and Indian oceans.",
    strategicImportance: "Critical global fallback corridor when Suez, Red Sea, or Middle East routes are disrupted.",
    connectedRoutes: ["asia-europe-cape-route"]
  }
];

export const layerLabels: Record<LayerKey, string> = {
  flight: "Flight Paths",
  shipping: "Shipping Routes",
  historical: "Historical Routes",
  chokepoints: "Chokepoints"
};
