import { SAVE_SCHEMA_VERSION } from './saveSchema'
import type {
  BuilderFlowState,
  DatasetRecord,
  ExperimentRecord,
  GraphLinkRecord,
  GraphNodeRecord,
  ModelRecord,
  NoteRecord,
  ResultRecord,
  WorkspaceStateData,
} from './types'

const nowIso = () => new Date().toISOString()

const datasets: DatasetRecord[] = [
  {
    id: 'dataset-xor',
    title: 'XOR Table',
    description: 'Binary logic dataset with two features and a non-linear target.',
    tags: ['binary', 'logic', 'intro'],
    schema: ['x1', 'x2', 'target'],
    targetField: 'target',
    presetId: 'xor-lab',
    sampleRows: [
      { x1: 0, x2: 0, target: 0 },
      { x1: 0, x2: 1, target: 1 },
      { x1: 1, x2: 0, target: 1 },
      { x1: 1, x2: 1, target: 0 },
    ],
  },
  {
    id: 'dataset-spiral',
    title: 'Two Spiral',
    description: 'Harder non-linear classification data for richer hidden representations.',
    tags: ['classification', 'manifold', 'advanced'],
    schema: ['x', 'y', 'class'],
    targetField: 'class',
    presetId: 'spiral-lab',
    sampleRows: [
      { x: 0.13, y: 0.01, class: 0 },
      { x: 0.19, y: 0.16, class: 0 },
      { x: -0.18, y: -0.05, class: 1 },
      { x: -0.32, y: 0.12, class: 1 },
    ],
  },
  {
    id: 'dataset-sine',
    title: 'Sine Curve',
    description: 'One-dimensional regression samples along a smooth sinusoid.',
    tags: ['regression', 'curve-fit'],
    schema: ['x', 'y'],
    targetField: 'y',
    presetId: 'sine-lab',
    sampleRows: [
      { x: 0, y: 0 },
      { x: 0.5, y: 0.479 },
      { x: 1, y: 0.842 },
      { x: 1.5, y: 0.997 },
    ],
  },
]

const notes: NoteRecord[] = [
  {
    id: 'note-lab-charter',
    title: 'Lab Charter',
    markdown:
      '# Cortex Lab\n\nThis workspace links neural architectures, datasets, results, and research notes into one local-first graph.\n\n- Use the builder to change the architecture.\n- Train in the browser.\n- Capture takeaways as linked notes.\n',
    tags: ['overview', 'workflow'],
    linkedNodeIds: ['node-exp-core', 'node-arch-main'],
    linkedNoteIds: ['note-spiral-observation'],
    updatedAt: nowIso(),
  },
  {
    id: 'note-spiral-observation',
    title: 'Spiral Observation',
    markdown:
      'The spiral preset benefits from a second hidden layer and sometimes a small dropout block. Keep the hidden units modest so browser training stays snappy.',
    tags: ['spiral', 'regularization'],
    linkedNodeIds: ['node-dataset-spiral', 'node-task-compare'],
    linkedNoteIds: ['note-lab-charter'],
    updatedAt: nowIso(),
  },
]

const experiments: ExperimentRecord[] = [
  {
    id: 'experiment-core',
    title: 'Core Browser Lab',
    description:
      'Primary experiment wiring together the active builder flow, the selected dataset preset, and training outputs.',
    datasetId: 'dataset-xor',
    architectureNodeId: 'node-arch-main',
    noteIds: ['note-lab-charter', 'note-spiral-observation'],
    modelIds: ['model-baseline-a'],
    latestResultId: 'result-baseline',
    presetId: 'xor-lab',
    status: 'draft',
  },
]

const models: ModelRecord[] = [
  {
    id: 'model-baseline-a',
    title: 'Baseline XOR v1',
    description: 'A starter model record representing the first saved browser run.',
    experimentId: 'experiment-core',
    version: 1,
    parameterEstimate: 37,
    metrics: {
      loss: 0.18,
      accuracy: 0.94,
      valLoss: 0.21,
      valAccuracy: 0.91,
    },
    updatedAt: nowIso(),
  },
]

const results: ResultRecord[] = [
  {
    id: 'result-baseline',
    title: 'Baseline Readout',
    experimentId: 'experiment-core',
    observations: [
      'The hidden stack is compact enough to retrain instantly in the browser.',
      'The note graph already connects the dataset, model, and next task.',
    ],
    metrics: {
      loss: 0.18,
      accuracy: 0.94,
    },
    createdAt: nowIso(),
  },
]

const nodes: GraphNodeRecord[] = [
  {
    id: 'node-note-charter',
    title: 'Lab Charter',
    category: 'note',
    summary: 'The central note describing how the AI lab is meant to be used.',
    cluster: 'knowledge-hub',
    group: 'knowledge',
    tags: ['overview', 'workflow'],
    entityKind: 'note',
    entityId: 'note-lab-charter',
    emphasis: 0.9,
    x: -86,
    y: 12,
    z: 24,
  },
  {
    id: 'node-note-spiral',
    title: 'Spiral Observation',
    category: 'note',
    summary: 'A note about regularization and depth on the spiral preset.',
    cluster: 'knowledge-hub',
    group: 'knowledge',
    tags: ['spiral', 'regularization'],
    entityKind: 'note',
    entityId: 'note-spiral-observation',
    emphasis: 0.68,
    x: -126,
    y: -26,
    z: 42,
  },
  {
    id: 'node-dataset-xor',
    title: 'XOR Table',
    category: 'dataset',
    summary: 'Starter binary dataset for learning hidden-layer separability.',
    cluster: 'dataset-dock',
    group: 'data',
    tags: ['binary', 'logic'],
    entityKind: 'dataset',
    entityId: 'dataset-xor',
    emphasis: 0.78,
    x: 96,
    y: -24,
    z: 18,
  },
  {
    id: 'node-dataset-spiral',
    title: 'Two Spiral',
    category: 'dataset',
    summary: 'Harder classification benchmark for advanced builder experiments.',
    cluster: 'dataset-dock',
    group: 'data',
    tags: ['advanced', 'classification'],
    entityKind: 'dataset',
    entityId: 'dataset-spiral',
    emphasis: 0.74,
    x: 134,
    y: -42,
    z: -12,
  },
  {
    id: 'node-exp-core',
    title: 'Core Browser Lab',
    category: 'experiment',
    summary: 'The active experiment tying notes, model versions, and datasets together.',
    cluster: 'experiment-bay',
    group: 'workflow',
    tags: ['active', 'browser'],
    entityKind: 'experiment',
    entityId: 'experiment-core',
    emphasis: 0.98,
    x: -2,
    y: 56,
    z: -72,
  },
  {
    id: 'node-arch-main',
    title: 'Architecture Flow',
    category: 'layerGroup',
    summary: 'A grouped representation of the current neural network builder.',
    cluster: 'experiment-bay',
    group: 'architecture',
    tags: ['builder', 'layers'],
    entityKind: 'builder',
    emphasis: 0.92,
    x: 18,
    y: 84,
    z: -96,
  },
  {
    id: 'node-model-a',
    title: 'Baseline XOR v1',
    category: 'model',
    summary: 'A locally saveable browser model record with starter metrics.',
    cluster: 'model-orbit',
    group: 'architecture',
    tags: ['saved', 'baseline'],
    entityKind: 'model',
    entityId: 'model-baseline-a',
    emphasis: 0.82,
    x: -24,
    y: -76,
    z: -64,
  },
  {
    id: 'node-result-baseline',
    title: 'Baseline Readout',
    category: 'result',
    summary: 'A metrics and insight snapshot from the current workspace.',
    cluster: 'results-shell',
    group: 'results',
    tags: ['metrics', 'output'],
    entityKind: 'result',
    entityId: 'result-baseline',
    emphasis: 0.76,
    x: 76,
    y: 48,
    z: 88,
  },
  {
    id: 'node-idea-latent',
    title: 'Latent atlas idea',
    category: 'idea',
    summary: 'Explore comparing learned hidden states as linked idea nodes.',
    cluster: 'knowledge-hub',
    group: 'knowledge',
    tags: ['future', 'analysis'],
    entityKind: 'idea',
    emphasis: 0.52,
    x: -56,
    y: 48,
    z: 72,
  },
  {
    id: 'node-task-compare',
    title: 'Compare presets',
    category: 'task',
    summary: 'Train XOR and spiral back-to-back, then attach a note about generalization.',
    cluster: 'results-shell',
    group: 'workflow',
    tags: ['next-step'],
    entityKind: 'task',
    emphasis: 0.6,
    x: 124,
    y: 74,
    z: 52,
  },
]

const links: GraphLinkRecord[] = [
  {
    id: 'link-note-exp',
    source: 'node-note-charter',
    target: 'node-exp-core',
    relation: 'documents',
    strength: 1,
  },
  {
    id: 'link-exp-dataset',
    source: 'node-exp-core',
    target: 'node-dataset-xor',
    relation: 'trains',
    strength: 1,
  },
  {
    id: 'link-exp-arch',
    source: 'node-exp-core',
    target: 'node-arch-main',
    relation: 'depends on',
    strength: 1,
  },
  {
    id: 'link-exp-model',
    source: 'node-exp-core',
    target: 'node-model-a',
    relation: 'versions',
    strength: 0.94,
  },
  {
    id: 'link-model-result',
    source: 'node-model-a',
    target: 'node-result-baseline',
    relation: 'evaluates',
    strength: 0.88,
  },
  {
    id: 'link-note-task',
    source: 'node-note-spiral',
    target: 'node-task-compare',
    relation: 'tracks',
    strength: 0.72,
  },
  {
    id: 'link-idea-note',
    source: 'node-idea-latent',
    target: 'node-note-charter',
    relation: 'inspires',
    strength: 0.62,
  },
  {
    id: 'link-spiral-dataset',
    source: 'node-note-spiral',
    target: 'node-dataset-spiral',
    relation: 'documents',
    strength: 0.76,
  },
]

const builder: BuilderFlowState = {
  id: 'flow-primary',
  title: 'Primary XOR Flow',
  nodes: [
    {
      id: 'builder-input',
      kind: 'input',
      label: 'Input',
      description: 'Two logical features feed the model.',
      position: { x: 40, y: 160 },
      config: {
        inputUnits: 2,
      },
    },
    {
      id: 'builder-dense-1',
      kind: 'dense',
      label: 'Hidden Dense A',
      description: 'A compact hidden layer for the XOR decision boundary.',
      position: { x: 260, y: 120 },
      config: {
        units: 8,
        activation: 'relu',
      },
    },
    {
      id: 'builder-dense-2',
      kind: 'dense',
      label: 'Hidden Dense B',
      description: 'A second layer gives the browser model room to separate classes.',
      position: { x: 500, y: 160 },
      config: {
        units: 3,
        activation: 'tanh',
      },
    },
    {
      id: 'builder-output',
      kind: 'output',
      label: 'Output',
      description: 'Binary classification head.',
      position: { x: 740, y: 160 },
      config: {
        units: 1,
        activation: 'sigmoid',
      },
    },
    {
      id: 'builder-dataset',
      kind: 'dataset',
      label: 'Dataset',
      description: 'Linked metadata node for the current preset.',
      position: { x: 40, y: 20 },
      config: {},
    },
    {
      id: 'builder-config',
      kind: 'trainingConfig',
      label: 'Training Config',
      description: 'Controls epochs and learning rate.',
      position: { x: 260, y: 20 },
      config: {
        epochs: 120,
        learningRate: 0.08,
      },
    },
    {
      id: 'builder-eval',
      kind: 'evaluation',
      label: 'Evaluation',
      description: 'Routes metrics and prediction previews into the workspace.',
      position: { x: 520, y: 20 },
      config: {},
    },
  ],
  edges: [
    { id: 'edge-input-dense-1', source: 'builder-input', target: 'builder-dense-1' },
    { id: 'edge-dense-1-dense-2', source: 'builder-dense-1', target: 'builder-dense-2' },
    { id: 'edge-dense-2-output', source: 'builder-dense-2', target: 'builder-output' },
    { id: 'edge-dataset-config', source: 'builder-dataset', target: 'builder-config' },
    { id: 'edge-config-eval', source: 'builder-config', target: 'builder-eval' },
  ],
}

export const createDefaultWorkspaceState = (): WorkspaceStateData => ({
  mode: 'beginner',
  nodes,
  links,
  notes,
  datasets,
  experiments,
  models,
  results,
  builder,
  training: {
    presetId: 'xor-lab',
    status: 'idle',
    config: {
      epochs: 120,
      batchSize: 4,
      learningRate: 0.08,
      validationSplit: 0.25,
      optimizer: 'adam',
      loss: 'binaryCrossentropy',
      metricKeys: ['accuracy'],
    },
    metrics: [],
    predictions: [],
    currentEpoch: 0,
    message: 'Ready to train the active browser model.',
    parameterEstimate: 0,
  },
  ui: {
    activeBottomTab: 'training',
    activeInspectorTab: 'overview',
    selectedNodeId: 'node-exp-core',
    focusedNodeId: 'node-exp-core',
    searchQuery: '',
    categoryFilters: {
      neural: true,
      note: true,
      dataset: true,
      experiment: true,
      model: true,
      idea: true,
      task: true,
      layerGroup: true,
      result: true,
    },
    showLabels: true,
    showOnlyConnected: false,
    leftPanelCollapsed: false,
    rightPanelCollapsed: false,
  },
  lastSavedAt: nowIso(),
  saveVersion: SAVE_SCHEMA_VERSION,
})
