import type {
  GraphBehaviorManifest,
  GraphCategoryVisual,
  GraphClusterDefinition,
  NodeCategory,
} from './types'

export const graphClusters: Record<string, GraphClusterDefinition> = {
  'knowledge-hub': {
    id: 'knowledge-hub',
    label: 'Knowledge Hub',
    hint: 'Notes, ideas, and linked research concepts gravitate here.',
    color: '#7cc7ff',
    origin: { x: -84, y: 8, z: 36 },
  },
  'dataset-dock': {
    id: 'dataset-dock',
    label: 'Dataset Dock',
    hint: 'Sample data, feature previews, and dataset metadata stay anchored here.',
    color: '#7cf6cb',
    origin: { x: 104, y: -28, z: 12 },
  },
  'experiment-bay': {
    id: 'experiment-bay',
    label: 'Experiment Bay',
    hint: 'Training runs, architecture nodes, and active configurations settle together.',
    color: '#ffb66d',
    origin: { x: 8, y: 72, z: -82 },
  },
  'model-orbit': {
    id: 'model-orbit',
    label: 'Model Orbit',
    hint: 'Saved model versions and reusable architectures orbit the experiment cluster.',
    color: '#c89aff',
    origin: { x: -8, y: -86, z: -56 },
  },
  'results-shell': {
    id: 'results-shell',
    label: 'Results Shell',
    hint: 'Metrics, evaluations, and action items remain near the outer shell.',
    color: '#ffd76c',
    origin: { x: 74, y: 52, z: 88 },
  },
}

export const nodeCategoryVisuals: Record<NodeCategory, GraphCategoryVisual> = {
  neural: {
    label: 'Neural Block',
    description: 'Model structure and builder-connected layer groups.',
    group: 'architecture',
    cluster: 'experiment-bay',
    color: '#64b8ff',
    accent: '#c6f0ff',
    size: 7.2,
    glow: 0.52,
  },
  note: {
    label: 'Research Note',
    description: 'Markdown notes, reflections, and experiment annotations.',
    group: 'knowledge',
    cluster: 'knowledge-hub',
    color: '#7fe3ff',
    accent: '#eafcff',
    size: 6.4,
    glow: 0.42,
  },
  dataset: {
    label: 'Dataset',
    description: 'Feature previews and metadata for in-browser experiments.',
    group: 'data',
    cluster: 'dataset-dock',
    color: '#66f0c2',
    accent: '#dbfff2',
    size: 7,
    glow: 0.5,
  },
  experiment: {
    label: 'Experiment',
    description: 'Trainable workflows linking datasets, architectures, and notes.',
    group: 'workflow',
    cluster: 'experiment-bay',
    color: '#ffa56c',
    accent: '#fff1e1',
    size: 7.6,
    glow: 0.58,
  },
  model: {
    label: 'Model Version',
    description: 'Saved browser models with versioned metrics and lineage.',
    group: 'architecture',
    cluster: 'model-orbit',
    color: '#b88cff',
    accent: '#f3eaff',
    size: 7.8,
    glow: 0.62,
  },
  idea: {
    label: 'Idea',
    description: 'Loose concepts and future directions for the lab.',
    group: 'knowledge',
    cluster: 'knowledge-hub',
    color: '#9ea8ff',
    accent: '#f1f3ff',
    size: 5.8,
    glow: 0.36,
  },
  task: {
    label: 'Task',
    description: 'Follow-ups, prompts, and checklist items tied to the workspace.',
    group: 'workflow',
    cluster: 'results-shell',
    color: '#ffd36e',
    accent: '#fff8dc',
    size: 5.8,
    glow: 0.36,
  },
  layerGroup: {
    label: 'Layer Group',
    description: 'Architectural summaries for the active neural network builder flow.',
    group: 'architecture',
    cluster: 'experiment-bay',
    color: '#4dd0ff',
    accent: '#d9f8ff',
    size: 8,
    glow: 0.64,
  },
  result: {
    label: 'Result',
    description: 'Metrics snapshots, evaluations, and takeaways from runs.',
    group: 'results',
    cluster: 'results-shell',
    color: '#ffd76c',
    accent: '#fff9de',
    size: 6.8,
    glow: 0.58,
  },
}

export const graphBehaviorManifest: GraphBehaviorManifest = {
  defaultCameraDistance: 220,
  focusCameraDistance: 88,
  linkOpacity: 0.34,
  settleTicks: 90,
  chargeStrength: -250,
  collisionRadius: 13,
  linkDistance: 54,
}

export const graphRelations = [
  'documents',
  'trains',
  'depends on',
  'versions',
  'evaluates',
  'inspires',
  'tracks',
] as const
