import type { BuilderBlockKind, ModelBlockDefinition } from './types'

const any = 'any' as const

export const modelBlockIndex: Record<BuilderBlockKind, ModelBlockDefinition> = {
  input: {
    kind: 'input',
    label: 'Input',
    family: 'data',
    description: 'Defines the feature width entering the network.',
    beginner: true,
    advanced: true,
    color: '#63d9b7',
    configFields: [
      {
        id: 'inputUnits',
        label: 'Features',
        input: 'number',
        helper: 'The number of numeric features expected by the first trainable layer.',
        min: 1,
        max: 32,
        step: 1,
      },
    ],
    acceptsFrom: [],
    emitsTo: any,
  },
  dense: {
    kind: 'dense',
    label: 'Dense',
    family: 'model',
    description: 'Fully connected layer for hidden representations.',
    beginner: true,
    advanced: true,
    color: '#5eb1ff',
    configFields: [
      {
        id: 'units',
        label: 'Units',
        input: 'number',
        helper: 'How many neurons should live in this dense layer.',
        min: 1,
        max: 128,
        step: 1,
      },
      {
        id: 'activation',
        label: 'Activation',
        input: 'select',
        helper: 'The non-linearity applied inside the dense layer.',
        options: [
          { label: 'ReLU', value: 'relu' },
          { label: 'Tanh', value: 'tanh' },
          { label: 'Sigmoid', value: 'sigmoid' },
          { label: 'Linear', value: 'linear' },
        ],
      },
    ],
    acceptsFrom: any,
    emitsTo: any,
  },
  activation: {
    kind: 'activation',
    label: 'Activation',
    family: 'model',
    description: 'Standalone activation for advanced sequencing.',
    beginner: false,
    advanced: true,
    color: '#85c9ff',
    configFields: [
      {
        id: 'activation',
        label: 'Activation',
        input: 'select',
        helper: 'Applies an activation after the previous trainable layer.',
        options: [
          { label: 'ReLU', value: 'relu' },
          { label: 'Tanh', value: 'tanh' },
          { label: 'Sigmoid', value: 'sigmoid' },
          { label: 'Softmax', value: 'softmax' },
          { label: 'Linear', value: 'linear' },
        ],
      },
    ],
    acceptsFrom: any,
    emitsTo: any,
  },
  dropout: {
    kind: 'dropout',
    label: 'Dropout',
    family: 'model',
    description: 'Regularization block for hiding a fraction of neurons during training.',
    beginner: false,
    advanced: true,
    color: '#72b4dd',
    configFields: [
      {
        id: 'rate',
        label: 'Dropout rate',
        input: 'range',
        helper: '0 disables dropout, 0.5 drops half the units on each training step.',
        min: 0,
        max: 0.8,
        step: 0.05,
      },
    ],
    acceptsFrom: any,
    emitsTo: any,
  },
  normalization: {
    kind: 'normalization',
    label: 'Batch Norm',
    family: 'model',
    description: 'Stabilizes activations between trainable layers.',
    beginner: false,
    advanced: true,
    color: '#75d9ff',
    configFields: [],
    acceptsFrom: any,
    emitsTo: any,
  },
  reshape: {
    kind: 'reshape',
    label: 'Reshape',
    family: 'model',
    description: 'Lightweight shape transform for advanced demos.',
    beginner: false,
    advanced: true,
    color: '#5fa0d9',
    configFields: [
      {
        id: 'targetUnits',
        label: 'Target width',
        input: 'number',
        helper: 'The flattened output width after reshaping.',
        min: 1,
        max: 64,
        step: 1,
      },
    ],
    acceptsFrom: any,
    emitsTo: any,
  },
  output: {
    kind: 'output',
    label: 'Output',
    family: 'control',
    description: 'Defines the model output layer and task-specific activation.',
    beginner: true,
    advanced: true,
    color: '#ffd36d',
    configFields: [
      {
        id: 'units',
        label: 'Outputs',
        input: 'number',
        helper: 'How many values should be predicted per sample.',
        min: 1,
        max: 16,
        step: 1,
      },
      {
        id: 'activation',
        label: 'Activation',
        input: 'select',
        helper: 'The output activation should match the selected training preset.',
        options: [
          { label: 'Sigmoid', value: 'sigmoid' },
          { label: 'Softmax', value: 'softmax' },
          { label: 'Linear', value: 'linear' },
        ],
      },
    ],
    acceptsFrom: any,
    emitsTo: [],
  },
  dataset: {
    kind: 'dataset',
    label: 'Dataset',
    family: 'data',
    description: 'Reference node for the currently selected training preset dataset.',
    beginner: true,
    advanced: true,
    color: '#5ee3b0',
    configFields: [],
    acceptsFrom: [],
    emitsTo: ['trainingConfig', 'evaluation', 'note'],
  },
  trainingConfig: {
    kind: 'trainingConfig',
    label: 'Training Config',
    family: 'control',
    description: 'Meta block describing epochs, learning rate, and batch size.',
    beginner: true,
    advanced: true,
    color: '#ffb26b',
    configFields: [
      {
        id: 'epochs',
        label: 'Epochs',
        input: 'number',
        helper: 'How many times the model should sweep through the dataset.',
        min: 1,
        max: 300,
        step: 1,
      },
      {
        id: 'learningRate',
        label: 'Learning rate',
        input: 'number',
        helper: 'Higher values train faster but can destabilize the run.',
        min: 0.0001,
        max: 0.5,
        step: 0.0005,
      },
    ],
    acceptsFrom: ['dataset'],
    emitsTo: ['evaluation', 'note'],
  },
  evaluation: {
    kind: 'evaluation',
    label: 'Evaluation',
    family: 'control',
    description: 'Captures outputs, preview predictions, and confusion summaries.',
    beginner: true,
    advanced: true,
    color: '#ffc767',
    configFields: [],
    acceptsFrom: any,
    emitsTo: ['note'],
  },
  note: {
    kind: 'note',
    label: 'Comment',
    family: 'annotation',
    description: 'Lightweight annotation block that mirrors into the notes graph.',
    beginner: true,
    advanced: true,
    color: '#7fe3ff',
    configFields: [
      {
        id: 'annotation',
        label: 'Comment',
        input: 'textarea',
        helper: 'Use this to explain why a block or experiment exists.',
      },
    ],
    acceptsFrom: any,
    emitsTo: any,
  },
}
