import type { NodeCategory, NodeTypeManifest } from './types'

export const nodeTypeIndex: Record<NodeCategory, NodeTypeManifest> = {
  neural: {
    category: 'neural',
    detailTitle: 'Neural component',
    description: 'Builder-linked architecture elements that explain how the model is assembled.',
    defaultBottomTab: 'builder',
    quickActionLabel: 'Open builder',
    relationHint: 'Use neural nodes to jump into architecture editing and layer inspection.',
  },
  note: {
    category: 'note',
    detailTitle: 'Research note',
    description: 'Markdown notes with backlinks into experiments, datasets, and models.',
    defaultBottomTab: 'notes',
    quickActionLabel: 'Edit note',
    relationHint: 'Note nodes are the main knowledge-management anchors in the graph.',
  },
  dataset: {
    category: 'dataset',
    detailTitle: 'Dataset',
    description: 'Small, browser-friendly datasets used for demos and local experimentation.',
    defaultBottomTab: 'training',
    quickActionLabel: 'Preview dataset',
    relationHint: 'Datasets connect into training presets, experiment nodes, and notes.',
  },
  experiment: {
    category: 'experiment',
    detailTitle: 'Experiment',
    description: 'Trainable workflows that bind datasets, architectures, and outputs together.',
    defaultBottomTab: 'training',
    quickActionLabel: 'Inspect run',
    relationHint: 'Experiment nodes are the bridge between the builder and the training console.',
  },
  model: {
    category: 'model',
    detailTitle: 'Model version',
    description: 'Locally saved TensorFlow.js models with metrics, versions, and lineage.',
    defaultBottomTab: 'training',
    quickActionLabel: 'Review metrics',
    relationHint: 'Model nodes capture browser-side training results and stored weights.',
  },
  idea: {
    category: 'idea',
    detailTitle: 'Idea',
    description: 'Open-ended concept cards for future research, product direction, or model tweaks.',
    defaultBottomTab: 'notes',
    quickActionLabel: 'Expand idea',
    relationHint: 'Idea nodes keep loose thinking connected to formal notes and tasks.',
  },
  task: {
    category: 'task',
    detailTitle: 'Task',
    description: 'Action-oriented follow-ups that keep the lab moving from thought to execution.',
    defaultBottomTab: 'workspace',
    quickActionLabel: 'Track task',
    relationHint: 'Task nodes help you operationalize results and experiment findings.',
  },
  layerGroup: {
    category: 'layerGroup',
    detailTitle: 'Layer group',
    description: 'A clustered representation of the active neural architecture in the 3D graph.',
    defaultBottomTab: 'builder',
    quickActionLabel: 'Review layers',
    relationHint: 'Layer groups summarize the builder flow without duplicating every edge in 3D.',
  },
  result: {
    category: 'result',
    detailTitle: 'Result snapshot',
    description: 'Output-oriented records such as metrics, evaluations, and confusion summaries.',
    defaultBottomTab: 'training',
    quickActionLabel: 'Open results',
    relationHint: 'Result nodes are ideal targets for post-training notes and action items.',
  },
}
