export const assetManifest = {
  sprites: [
    "player_riven",
    "npc_mara",
    "npc_sable",
    "npc_brann",
    "npc_nessa",
    "npc_hale",
    "npc_lyra",
    "npc_toma",
    "npc_pell",
    "npc_orsa",
    "npc_guard",
    "npc_townsfolk",
    "enemy_mossling",
    "enemy_bandit",
    "enemy_moth",
    "enemy_beetle",
    "enemy_raider",
    "enemy_wisp",
    "boss_hollow_stag",
  ],
  icons: [
    "icon_sword",
    "icon_spear",
    "icon_bow",
    "icon_tome",
    "icon_tonic",
    "icon_herb",
    "icon_fish",
    "icon_ore",
    "icon_timber",
    "icon_key",
    "icon_charm",
  ],
  ui: ["ui_frame", "ui_cursor", "ui_marker", "ui_logo_emblem"],
  notes:
    "Art is generated from palette-driven pixel patterns in code so the project can stay fully original, editable, and self-contained.",
};
