export const audioManifest = {
  music: [
    "title_theme",
    "emberwharf_theme",
    "sunglade_theme",
    "wilds_theme",
    "coast_theme",
    "ruin_theme",
    "battle_theme",
    "boss_theme",
    "menu_theme",
  ],
  sfx: [
    "menu_move",
    "menu_accept",
    "dialogue",
    "swing",
    "hit",
    "dodge",
    "projectile",
    "pickup",
    "coin",
    "quest",
    "heal",
    "enemy_down",
    "save",
  ],
  fallback: "All audio is synthesized at runtime with Web Audio oscillators and noise bursts; no external sound files are required.",
};
