export const mapIndex = [
  { id: "emberwharf", regionId: "emberward", theme: "town", linksTo: ["old_road", "lantern_inn", "forgehouse", "guildhall", "apothecary"] },
  { id: "lantern_inn", regionId: "emberward", theme: "interior", linksTo: ["emberwharf"] },
  { id: "forgehouse", regionId: "emberward", theme: "interior", linksTo: ["emberwharf"] },
  { id: "guildhall", regionId: "emberward", theme: "interior", linksTo: ["emberwharf"] },
  { id: "apothecary", regionId: "emberward", theme: "interior", linksTo: ["emberwharf"] },
  { id: "old_road", regionId: "greenway", theme: "village", linksTo: ["emberwharf", "southfields", "whisperwood", "sunglade_city"] },
  { id: "southfields", regionId: "southfields", theme: "village", linksTo: ["old_road", "farmhouse", "brasscoast"] },
  { id: "farmhouse", regionId: "southfields", theme: "interior", linksTo: ["southfields"] },
  { id: "brasscoast", regionId: "southfields", theme: "coast", linksTo: ["southfields"] },
  { id: "whisperwood", regionId: "greenway", theme: "forest", linksTo: ["old_road", "ridgewatch_mine", "glassroot_ruins", "moonwell_glen"] },
  { id: "ridgewatch_mine", regionId: "ridgewatch", theme: "mine", linksTo: ["whisperwood"] },
  { id: "sunglade_city", regionId: "sunglade", theme: "city", linksTo: ["old_road", "city_tavern", "archive_hall"] },
  { id: "city_tavern", regionId: "sunglade", theme: "interior", linksTo: ["sunglade_city"] },
  { id: "archive_hall", regionId: "sunglade", theme: "interior", linksTo: ["sunglade_city"] },
  { id: "glassroot_ruins", regionId: "glassroot", theme: "ruin", linksTo: ["whisperwood", "glassroot_depths"] },
  { id: "glassroot_depths", regionId: "glassroot", theme: "dungeon", linksTo: ["glassroot_ruins"] },
  { id: "moonwell_glen", regionId: "glassroot", theme: "forest", linksTo: ["whisperwood"] },
] as const;
