export const worldIndex = [
  {
    id: "emberward",
    name: "Emberward",
    biome: "Town and meadow frontier",
    summary: "A lantern town of couriers, workshops, and market lanes built around the oldest lit brazier in the Reach.",
    mapIds: ["emberwharf", "lantern_inn", "forgehouse", "guildhall", "apothecary"],
    connections: ["greenway", "southfields"],
  },
  {
    id: "greenway",
    name: "Greenway Road",
    biome: "Fields and roadside wilds",
    summary: "Wind-bent grass, ruined mileposts, and the main road that ties the Reach together.",
    mapIds: ["old_road", "whisperwood"],
    connections: ["emberward", "sunglade", "glassroot", "southfields", "ridgewatch"],
  },
  {
    id: "southfields",
    name: "Southfields",
    biome: "Farms and coast road",
    summary: "Threshing yards, orchards, and fishing paths where work and rumor travel together.",
    mapIds: ["southfields", "farmhouse", "brasscoast"],
    connections: ["emberward", "greenway", "sunglade"],
  },
  {
    id: "sunglade",
    name: "Sunglade City",
    biome: "Trade city and stone avenues",
    summary: "The Reach's biggest city, home to the archive bells, guild contracts, and market intrigue.",
    mapIds: ["sunglade_city", "city_tavern", "archive_hall"],
    connections: ["greenway", "southfields"],
  },
  {
    id: "ridgewatch",
    name: "Ridgewatch",
    biome: "Mine and cliff road",
    summary: "A mineral ridge scarred with glow-ore seams and defended by stubborn miners.",
    mapIds: ["ridgewatch_mine"],
    connections: ["greenway", "glassroot"],
  },
  {
    id: "glassroot",
    name: "Glassroot",
    biome: "Forest ruins and buried roots",
    summary: "A haunted tangle of abbey stones, bioluminescent roots, and the sealed road into the depths.",
    unlockFlag: "story.glassroot_open",
    mapIds: ["glassroot_ruins", "glassroot_depths", "moonwell_glen"],
    connections: ["greenway", "ridgewatch"],
  },
] as const;
