import type { CategoryDefinition } from "./types";

export const gameManifest = {
  app: {
    title: "Puzzle Escape Lab",
    version: "1.0.0",
    tagline: "Decode rooms, outthink rivals, and escape elegant traps.",
    description:
      "A premium single-page puzzle platform blending detective fiction, escape-room scenes, codebreaking, and IQ challenges.",
  },
  categories: [
    {
      id: "pattern-recognition",
      name: "Pattern Recognition",
      blurb: "Mensa-flavored matrices, symbol shifts, and elegant structure puzzles.",
      accent: "#73f6ce",
      icon: "PR",
      heroMetric: "8 logic tests",
      route: "/category/pattern-recognition",
    },
    {
      id: "analogies",
      name: "Analogies",
      blurb: "Relationship puzzles that reward abstraction and flexible thinking.",
      accent: "#ffcf70",
      icon: "AN",
      heroMetric: "Mind bridges",
      route: "/category/analogies",
    },
    {
      id: "odd-one-out",
      name: "Odd-One-Out",
      blurb: "Spot the intruder hidden in systems, sets, and visual families.",
      accent: "#fa8f8f",
      icon: "OO",
      heroMetric: "Set breakers",
      route: "/category/odd-one-out",
    },
    {
      id: "syllogism-deduction",
      name: "Syllogism & Deduction",
      blurb: "Logic duels, layered premises, and timeline reconstruction.",
      accent: "#8cb8ff",
      icon: "SD",
      heroMetric: "6 mind battles",
      route: "/category/syllogism-deduction",
    },
    {
      id: "truth-lie",
      name: "Truth / Lie Logic",
      blurb: "Witness statements, bluffing suspects, and strategic contradictions.",
      accent: "#a5ff8c",
      icon: "TL",
      heroMetric: "False trails",
      route: "/category/truth-lie",
    },
    {
      id: "sequence-systems",
      name: "Sequence Systems",
      blurb: "Numeric ladders, visual rhythms, route chains, and memory loops.",
      accent: "#b28dff",
      icon: "SQ",
      heroMetric: "5 sequence runs",
      route: "/category/sequence-systems",
    },
    {
      id: "grid-logic",
      name: "Grid Logic",
      blurb: "Cross-reference clues and isolate the one arrangement that works.",
      accent: "#59d8ff",
      icon: "GL",
      heroMetric: "Structured logic",
      route: "/category/grid-logic",
    },
    {
      id: "cipher-lab",
      name: "Cipher Lab",
      blurb: "Substitution alphabets, Caesar shifts, Vigenere, and code wheels.",
      accent: "#ff8de1",
      icon: "CL",
      heroMetric: "6 codebreakers",
      route: "/category/cipher-lab",
    },
    {
      id: "signal-decoding",
      name: "Signal Decoding",
      blurb: "Morse, binary, symbols, and low-fi transmission reconstruction.",
      accent: "#ffae70",
      icon: "SG",
      heroMetric: "Signals and symbols",
      route: "/category/signal-decoding",
    },
    {
      id: "observation-scenes",
      name: "Observation Scenes",
      blurb: "Clickable hotspots, hidden objects, clue hunts, and scene codes.",
      accent: "#79ffd9",
      icon: "OS",
      heroMetric: "11 scene cases",
      route: "/category/observation-scenes",
    },
    {
      id: "passcodes-locks",
      name: "Passcodes & Locks",
      blurb: "Keypads, safes, layered passphrases, and lock-chain reasoning.",
      accent: "#f7db7b",
      icon: "PL",
      heroMetric: "5 secure locks",
      route: "/category/passcodes-locks",
    },
    {
      id: "word-riddles",
      name: "Word & Riddle",
      blurb: "Acrostics, lateral thinking, verbal traps, and precise phrasing.",
      accent: "#9ad6ff",
      icon: "WR",
      heroMetric: "5 verbal twists",
      route: "/category/word-riddles",
    },
    {
      id: "meta-puzzles",
      name: "Meta Puzzles",
      blurb: "Combine earlier answers into endgame keys and master ciphers.",
      accent: "#ffd56c",
      icon: "MP",
      heroMetric: "Final synthesis",
      route: "/category/meta-puzzles",
    },
  ] satisfies CategoryDefinition[],
  progressionOverview: [
    "Solve any starter puzzle to establish your investigation streak.",
    "Cross-category milestones unlock deeper cipher, passcode, and meta cases.",
    "Escape rooms track room scenes, collected inventory, and scene discoveries locally.",
    "Hints help when needed, but they reduce score and stars for that puzzle.",
  ],
  unlockRulesSummary: [
    "Meta puzzles unlock after clusters of earlier answers are solved.",
    "Advanced passcode challenges appear after core observation and cipher clears.",
    "Each escape room opens in sequence, with later rooms asking for more solved puzzles.",
  ],
  featuredChallengeIds: [
    "lantern-matrix",
    "double-bluff-ledger",
    "moonlit-shelf",
    "atrium-safe",
    "residue-equation",
  ],
};
