import type { SceneDefinition } from "@/memory/types";

export const sceneIndex: SceneDefinition[] = [
  {
    id: "intro",
    index: 0,
    label: "Opening",
    eyebrow: "Never Wet // Project Atlas",
    title: "A calm orbital entry into a personal world of projects.",
    description:
      "Scroll to let the camera drift through a soft-lit void where each project arrives as architecture, object, and atmosphere.",
    overlayAlign: "left",
    scrollRange: [0, 0.14],
    cameraAnchorId: "intro-start",
    audioProfileId: "intro-atmosphere",
    transitionLabel: "Enter the field",
  },
  {
    id: "threshold",
    index: 1,
    label: "Threshold",
    eyebrow: "Transition corridor",
    title: "Portals wake first, then the worlds behind them.",
    description:
      "A controlled passage of rings, veils, and luminous debris sets the tone before the project chambers begin to surface.",
    overlayAlign: "left",
    scrollRange: [0.14, 0.3],
    cameraAnchorId: "threshold-approach",
    audioProfileId: "threshold-ribbon",
    transitionLabel: "Cross the veil",
  },
  {
    id: "lantern-oath",
    index: 2,
    label: "Project chamber",
    eyebrow: "Lantern Oath",
    title: "An action RPG presented as a floating hearth in the dark.",
    description:
      "A lantern monolith hangs above a fractured island while the camera tilts closer and the chamber glows warm against the colder void.",
    overlayAlign: "left",
    scrollRange: [0.3, 0.5],
    cameraAnchorId: "lantern-orbit",
    audioProfileId: "lantern-field",
    transitionLabel: "Open the hearth",
    projectId: "lantern-oath",
  },
  {
    id: "midnight-pawn",
    index: 3,
    label: "Project chamber",
    eyebrow: "Midnight Pawn",
    title: "A relic broker world treated like a gilded nocturnal vault.",
    description:
      "Polished brass frames, suspended relic trays, and a slow orbiting vault announce a merchant sim designed with atmosphere first.",
    overlayAlign: "right",
    scrollRange: [0.5, 0.7],
    cameraAnchorId: "midnight-drift",
    audioProfileId: "midnight-vault",
    transitionLabel: "Unseal the vault",
    projectId: "midnight-pawn",
  },
  {
    id: "reelspull",
    index: 4,
    label: "Project chamber",
    eyebrow: "Reels Pull",
    title: "A gacha spectacle rendered as a suspended orbital machine.",
    description:
      "A prismatic reel structure turns inside a halo of light, with poster surfaces and signal ribbons echoing the game's celebration loops.",
    overlayAlign: "left",
    scrollRange: [0.7, 0.88],
    cameraAnchorId: "reel-ascend",
    audioProfileId: "reel-signal",
    transitionLabel: "Trigger the spin",
    projectId: "reelspull",
  },
  {
    id: "outro",
    index: 5,
    label: "Outro",
    eyebrow: "Closing frame",
    title: "A final platform with clean paths back into the archive.",
    description:
      "The camera widens, the noise softens, and the world resolves into a minimal set of next steps instead of a hard stop.",
    overlayAlign: "center",
    scrollRange: [0.88, 1],
    cameraAnchorId: "outro-fade",
    audioProfileId: "outro-quiet",
    transitionLabel: "Stay in orbit",
  },
];
