import type { AudioNodeDefinition } from "./types";

export const audioManifest: {
  music: AudioNodeDefinition[];
  ambience: AudioNodeDefinition[];
  sfx: AudioNodeDefinition[];
  ui: AudioNodeDefinition[];
} = {
  music: [
    {
      key: "menu-dream",
      category: "music",
      label: "Menu Dream",
      description: "Soft title-screen pulse built from minor triads and distant chimes.",
      waveform: "sine",
      tempo: 66,
      sequence: [220, 247, 294, 247],
      volume: 0.18,
      loop: true,
    },
    {
      key: "town-lanterns",
      category: "music",
      label: "Lantern Square",
      description: "Warm, lightly hopeful town music.",
      waveform: "triangle",
      tempo: 72,
      sequence: [196, 220, 247, 262],
      volume: 0.14,
      loop: true,
    },
    {
      key: "forest-whispers",
      category: "music",
      label: "Whisperblight Canopy",
      description: "Uneasy forest loop with drifting intervals.",
      waveform: "sawtooth",
      tempo: 58,
      sequence: [165, 196, 185, 220],
      volume: 0.12,
      loop: true,
    },
    {
      key: "abbey-depths",
      category: "music",
      label: "Flooded Abbey",
      description: "Low drone for chapel ruins and vows gone wrong.",
      waveform: "triangle",
      tempo: 54,
      sequence: [147, 165, 175, 196],
      volume: 0.13,
      loop: true,
    },
    {
      key: "boss-starfall",
      category: "music",
      label: "Starfall Reckoning",
      description: "Sharper boss pulse for the final climb.",
      waveform: "square",
      tempo: 92,
      sequence: [220, 233, 196, 185, 247, 262],
      volume: 0.14,
      loop: true,
    },
  ],
  ambience: [
    {
      key: "rain-harbor",
      category: "ambience",
      label: "Rain Harbor",
      description: "Filtered noise and low bells for Thornwake.",
      waveform: "sine",
      tempo: 40,
      sequence: [110, 0, 123, 0],
      volume: 0.1,
      loop: true,
    },
    {
      key: "forest-cicada",
      category: "ambience",
      label: "Forest Hiss",
      description: "Breathing canopy ambience.",
      waveform: "triangle",
      tempo: 48,
      sequence: [98, 104, 98, 117],
      volume: 0.08,
      loop: true,
    },
    {
      key: "ruin-drip",
      category: "ambience",
      label: "Ruin Drip",
      description: "Slow water drops and cloister resonance.",
      waveform: "sine",
      tempo: 36,
      sequence: [73, 0, 82, 0],
      volume: 0.08,
      loop: true,
    },
  ],
  sfx: [
    {
      key: "battle-start",
      category: "sfx",
      label: "Battle Start",
      description: "A sharp rising warning.",
      waveform: "sawtooth",
      sequence: [220, 330, 440],
      volume: 0.18,
      loop: false,
    },
    {
      key: "hit",
      category: "sfx",
      label: "Hit",
      description: "Short impact cue.",
      waveform: "square",
      sequence: [160, 100],
      volume: 0.16,
      loop: false,
    },
    {
      key: "heal",
      category: "sfx",
      label: "Heal",
      description: "Ascending restoration tone.",
      waveform: "sine",
      sequence: [262, 330, 392],
      volume: 0.14,
      loop: false,
    },
    {
      key: "pickup",
      category: "sfx",
      label: "Item Pickup",
      description: "Quick glint for pickups.",
      waveform: "triangle",
      sequence: [392, 494],
      volume: 0.14,
      loop: false,
    },
    {
      key: "footstep-stone",
      category: "sfx",
      label: "Footstep Stone",
      description: "Short dry bootstep for roads, boards, and masonry.",
      waveform: "square",
      sequence: [120, 90],
      volume: 0.07,
      loop: false,
    },
    {
      key: "footstep-grass",
      category: "sfx",
      label: "Footstep Grass",
      description: "Soft step through roots and reeds.",
      waveform: "triangle",
      sequence: [180, 130],
      volume: 0.07,
      loop: false,
    },
    {
      key: "quest-complete",
      category: "sfx",
      label: "Quest Complete",
      description: "A triumphant three-note fanfare.",
      waveform: "triangle",
      sequence: [294, 392, 523],
      volume: 0.18,
      loop: false,
    },
    {
      key: "victory",
      category: "sfx",
      label: "Victory",
      description: "Soft but satisfying victory flourish.",
      waveform: "triangle",
      sequence: [330, 392, 494, 659],
      volume: 0.18,
      loop: false,
    },
    {
      key: "defeat",
      category: "sfx",
      label: "Defeat",
      description: "Falling loss sting.",
      waveform: "sawtooth",
      sequence: [196, 165, 123],
      volume: 0.18,
      loop: false,
    },
    {
      key: "boss-warning",
      category: "sfx",
      label: "Boss Warning",
      description: "Alarm pulse for major encounters.",
      waveform: "square",
      sequence: [110, 110, 147, 147],
      volume: 0.2,
      loop: false,
    },
  ],
  ui: [
    {
      key: "menu-confirm",
      category: "ui",
      label: "Confirm",
      description: "Button confirm tick.",
      waveform: "triangle",
      sequence: [523, 659],
      volume: 0.12,
      loop: false,
    },
    {
      key: "menu-hover",
      category: "ui",
      label: "Hover",
      description: "Short hover chirp.",
      waveform: "sine",
      sequence: [440],
      volume: 0.08,
      loop: false,
    },
    {
      key: "dialogue-blip",
      category: "ui",
      label: "Dialogue Blip",
      description: "Small typewriter-like pulse for dialogue advance.",
      waveform: "square",
      sequence: [660],
      volume: 0.06,
      loop: false,
    },
  ],
};
