import type { EventIndexEntry } from "./types";

export const eventIndex: EventIndexEntry[] = [
  {
    id: "event-marketfire-step",
    chapterId: "prologue",
    locationId: "thornwake",
    kind: "scene",
    triggerType: "step",
    sourceId: "thornwake-marketfire",
    rewards: ["Starts first battle and advances the prologue."],
  },
  {
    id: "event-council-hall",
    chapterId: "prologue",
    locationId: "thornwake",
    kind: "scene",
    triggerType: "interact",
    sourceId: "thornwake-council",
    rewards: ["Unlocks Chapter I and opens Gloamwood Reach."],
  },
  {
    id: "event-lantern-house-cache",
    chapterId: "prologue",
    locationId: "lantern-house",
    kind: "pickup",
    triggerType: "interact",
    sourceId: "lantern-house-cache",
    rewards: ["Moonwater Tonic", "Emberleaf Poultice"],
  },
  {
    id: "event-whispering-oak",
    chapterId: "chapter1",
    locationId: "gloamwood-trail",
    kind: "scene",
    triggerType: "interact",
    sourceId: "gloamwood-oak",
    rewards: ["Abbey Key", "Rainmire unlocked", "Chapter II setup"],
  },
  {
    id: "event-rainmire-flotsam",
    chapterId: "chapter1",
    locationId: "rainmire-crossing",
    kind: "pickup",
    triggerType: "interact",
    sourceId: "rainmire-flotsam",
    rewards: ["Stormglass Vial"],
  },
  {
    id: "event-abbey-betrayal",
    chapterId: "chapter2",
    locationId: "saint-veyra-abbey",
    kind: "scene",
    triggerType: "interact",
    sourceId: "abbey-betrayal-scene",
    rewards: ["Elric judgment flag", "Main quest advance"],
  },
  {
    id: "event-hollow-star-ending",
    chapterId: "chapter3",
    locationId: "skyglass-spire",
    kind: "scene",
    triggerType: "battleVictory",
    sourceId: "mirror-warden-duel",
    rewards: ["Ending choice", "Epilogue", "Story completion"],
  },
];
