import type { MapIndexEntry } from "./types";

export const mapIndex: MapIndexEntry[] = [
  {
    id: "map-thornwake",
    locationId: "thornwake",
    chapterId: "prologue",
    regionId: "lantern-coast",
    environment: "town",
    label: "Starter town hub and opening attack zone.",
    warpTargets: ["lantern-house", "gloamwood-trail"],
    eventActionIds: ["thornwake-marketfire", "thornwake-council"],
  },
  {
    id: "map-lantern-house",
    locationId: "lantern-house",
    chapterId: "prologue",
    regionId: "lantern-coast",
    environment: "interior",
    label: "Enterable interior used for rest, lore, and item pickup.",
    warpTargets: ["thornwake"],
    eventActionIds: ["thornwake-rest", "lantern-house-cache", "thornwake-ledger"],
  },
  {
    id: "map-gloamwood",
    locationId: "gloamwood-trail",
    chapterId: "chapter1",
    regionId: "gloamwood-reach",
    environment: "forest",
    label: "First route/forest zone with roaming battles and story progression.",
    warpTargets: ["thornwake", "rainmire-crossing"],
    eventActionIds: ["gloamwood-meet-nessa", "gloamwood-briar-pack", "gloamwood-root-nest", "gloamwood-oak"],
  },
  {
    id: "map-rainmire",
    locationId: "rainmire-crossing",
    chapterId: "chapter1",
    regionId: "gloamwood-reach",
    environment: "marsh",
    label: "Marsh route with bridge boss, smuggler story beats, and pickups.",
    warpTargets: ["gloamwood-trail", "saint-veyra-abbey"],
    eventActionIds: ["rainmire-fen", "rainmire-flotsam", "rainmire-troll", "rainmire-hunters"],
  },
  {
    id: "map-abbey",
    locationId: "saint-veyra-abbey",
    chapterId: "chapter2",
    regionId: "saintfall-basin",
    environment: "abbey",
    label: "Dungeon-like ruin zone with pickups, hauntings, betrayal, and vault access.",
    warpTargets: ["rainmire-crossing", "skyglass-spire"],
    eventActionIds: ["abbey-gate-scene", "abbey-reliquary", "abbey-sentinels", "abbey-betrayal-scene", "abbey-vault"],
  },
  {
    id: "map-spire",
    locationId: "skyglass-spire",
    chapterId: "chapter3",
    regionId: "skyglass-rise",
    environment: "spire",
    label: "Final ascent and boss approach zone.",
    warpTargets: ["saint-veyra-abbey"],
    eventActionIds: ["spire-threshold-scene", "spire-regent"],
  },
];
