import type { DifficultyProfile } from "./types";

export const aiIndex: Record<"easy" | "medium" | "hard", DifficultyProfile> = {
  easy: {
    label: "Easy",
    description: "Relaxed play with shorter search and more noise.",
    moveDelayMs: 320,
    randomness: 0.24,
    searchDepth: {
      chess: 1,
      connect4: 3,
      checkers: 3,
      tictactoe: 7,
      reversi: 2,
      gomoku: 1,
    },
    nodeBudget: {
      chess: 3000,
      connect4: 4000,
      checkers: 4500,
      tictactoe: 2500,
      reversi: 5000,
      gomoku: 2500,
    },
  },
  medium: {
    label: "Medium",
    description: "Balanced search for most matches.",
    moveDelayMs: 420,
    randomness: 0.1,
    searchDepth: {
      chess: 2,
      connect4: 4,
      checkers: 5,
      tictactoe: 9,
      reversi: 3,
      gomoku: 2,
    },
    nodeBudget: {
      chess: 9000,
      connect4: 11000,
      checkers: 14000,
      tictactoe: 4500,
      reversi: 14000,
      gomoku: 5000,
    },
  },
  hard: {
    label: "Hard",
    description: "Sharper tactical awareness and deeper reads.",
    moveDelayMs: 520,
    randomness: 0,
    searchDepth: {
      chess: 3,
      connect4: 5,
      checkers: 6,
      tictactoe: 10,
      reversi: 4,
      gomoku: 2,
    },
    nodeBudget: {
      chess: 28000,
      connect4: 30000,
      checkers: 32000,
      tictactoe: 7000,
      reversi: 30000,
      gomoku: 7000,
    },
  },
};
